/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/benji/.nim/lib -o /home/benji/dev/nim/website/src/nimcache/jester_errorpages.c.o /home/benji/dev/nim/website/src/nimcache/jester_errorpages.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_EiMdtE0B74IVm03tLqviMA_2, "<html xmlns=\"http://www.w3.org/1999/xhtml\"><head><title>Jester "
"route exception</title></head><body><h1>An error has occured in "
"one of your routes.</h1><p><b>Detail: </b>", 169);
STRING_LITERAL(TM_EiMdtE0B74IVm03tLqviMA_3, "</p></body></html>", 18);
STRING_LITERAL(TM_EiMdtE0B74IVm03tLqviMA_4, "<html xmlns=\"http://www.w3.org/1999/xhtml\"><head><title>", 56);
STRING_LITERAL(TM_EiMdtE0B74IVm03tLqviMA_5, "</title></head><body style=\"text-align: center;\"><h1>", 53);
STRING_LITERAL(TM_EiMdtE0B74IVm03tLqviMA_6, "</h1><hr/><p>Jester ", 20);

static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == NIM_NIL))) goto LA3_;
		copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, routeException_ZgZCwDDBjSqNeieAg5hofQ)(NimStringDesc* error, NimStringDesc* jesterVer) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	nimfr_("routeException", "errorpages.nim");
{	result = (NimStringDesc*)0;
	nimln_(14, "errorpages.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = rawNewString((error ? error->Sup.len : 0) + 187);
appendString(T1_, ((NimStringDesc*) &TM_EiMdtE0B74IVm03tLqviMA_2));
appendString(T1_, error);
appendString(T1_, ((NimStringDesc*) &TM_EiMdtE0B74IVm03tLqviMA_3));
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, error_DURUp9akZTgqHyxeWmaIXwQ)(NimStringDesc* err, NimStringDesc* jesterVer) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	nimfr_("error", "errorpages.nim");
{	result = (NimStringDesc*)0;
	nimln_(5, "errorpages.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = rawNewString((err ? err->Sup.len : 0) + (err ? err->Sup.len : 0) + (jesterVer ? jesterVer->Sup.len : 0) + 147);
appendString(T1_, ((NimStringDesc*) &TM_EiMdtE0B74IVm03tLqviMA_4));
appendString(T1_, err);
appendString(T1_, ((NimStringDesc*) &TM_EiMdtE0B74IVm03tLqviMA_5));
appendString(T1_, err);
appendString(T1_, ((NimStringDesc*) &TM_EiMdtE0B74IVm03tLqviMA_6));
appendString(T1_, jesterVer);
appendString(T1_, ((NimStringDesc*) &TM_EiMdtE0B74IVm03tLqviMA_3));
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, jester_errorpagesInit000)(void) {
	nimfr_("errorpages", "errorpages.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, jester_errorpagesDatInit000)(void) {
}

