/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/benji/.nim/lib -o /home/benji/dev/nim/website/src/nimcache/stdlib_hashes.c.o /home/benji/dev/nim/website/src/nimcache/stdlib_hashes.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, emarkamp__6dtCP6C39bxOkT4wrIPJwKghashes)(NI h, NI val);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, emarkdollar__zs9byUtT9cNi2e9clB27b2cUAhashes)(NI h);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NI, emarkamp__6dtCP6C39bxOkT4wrIPJwKghashes)(NI h, NI val) {
	NI result;
	nimfr_("!&", "hashes.nim");
	result = (NI)0;
	nimln_(52, "hashes.nim");
	result = (NI)((NU64)(h) + (NU64)(val));
	nimln_(53, "hashes.nim");
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(((NI) 10)))));
	nimln_(54, "hashes.nim");
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(((NI) 6))));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, emarkdollar__zs9byUtT9cNi2e9clB27b2cUAhashes)(NI h) {
	NI result;
	nimfr_("!$", "hashes.nim");
	result = (NI)0;
	nimln_(59, "hashes.nim");
	result = (NI)((NU64)(h) + (NU64)((NI)((NU64)(h) << (NU64)(((NI) 3)))));
	nimln_(60, "hashes.nim");
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(((NI) 11))));
	nimln_(61, "hashes.nim");
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(((NI) 15)))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x) {
	NI result;
	NI h;
	nimfr_("hash", "hashes.nim");
	result = (NI)0;
	nimln_(132, "hashes.nim");
	h = ((NI) 0);
	{
		NI i;
		NI colontmp_;
		NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_2;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(133, "hashes.nim");
		TM_7tkD9cFJSchVDwHuwaY9bP9bA_2 = subInt((x ? x->Sup.len : 0), ((NI) 1));
		colontmp_ = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_2);
		nimln_(2023, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2024, "system.nim");
			while (1) {
				NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_3;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(2025, "system.nim");
				i = res;
				nimln_(134, "hashes.nim");
				if (!x || (NU)(i) >= (NU)(x->Sup.len)) raiseIndexError();
				h = emarkamp__6dtCP6C39bxOkT4wrIPJwKghashes(h, ((NU8)(x->data[i])));
				nimln_(2026, "system.nim");
				TM_7tkD9cFJSchVDwHuwaY9bP9bA_3 = addInt(res, ((NI) 1));
				res = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_3);
			} LA3: ;
		}
	}
	nimln_(135, "hashes.nim");
	result = emarkdollar__zs9byUtT9cNi2e9clB27b2cUAhashes(h);
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreCase_uBstFm5SYVQeOL3j9c9bc58A_2)(NimStringDesc* x) {
	NI result;
	NI h;
	nimfr_("hashIgnoreCase", "hashes.nim");
	result = (NI)0;
	nimln_(199, "hashes.nim");
	h = ((NI) 0);
	{
		NI i;
		NI colontmp_;
		NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_4;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(200, "hashes.nim");
		TM_7tkD9cFJSchVDwHuwaY9bP9bA_4 = subInt((x ? x->Sup.len : 0), ((NI) 1));
		colontmp_ = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_4);
		nimln_(2023, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2024, "system.nim");
			while (1) {
				NIM_CHAR c;
				NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_6;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(2025, "system.nim");
				i = res;
				nimln_(201, "hashes.nim");
				if (!x || (NU)(i) >= (NU)(x->Sup.len)) raiseIndexError();
				c = x->data[i];
				nimln_(202, "hashes.nim");
				{
					NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_5;
					if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA6_;
					nimln_(203, "hashes.nim");
					TM_7tkD9cFJSchVDwHuwaY9bP9bA_5 = addInt(((NU8)(c)), ((NI) 32));
					c = ((NIM_CHAR) (((NI)chckRange((NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_5), ((NI) 0), ((NI) 255)))));
				}
				LA6_: ;
				nimln_(204, "hashes.nim");
				h = emarkamp__6dtCP6C39bxOkT4wrIPJwKghashes(h, ((NU8)(c)));
				nimln_(2026, "system.nim");
				TM_7tkD9cFJSchVDwHuwaY9bP9bA_6 = addInt(res, ((NI) 1));
				res = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_6);
			} LA3: ;
		}
	}
	nimln_(205, "hashes.nim");
	result = emarkdollar__zs9byUtT9cNi2e9clB27b2cUAhashes(h);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreStyle_uBstFm5SYVQeOL3j9c9bc58A_3)(NimStringDesc* x) {
	NI result;
	NI h;
	NI i;
	NI xLen;
	nimfr_("hashIgnoreStyle", "hashes.nim");
	result = (NI)0;
	nimln_(163, "hashes.nim");
	h = ((NI) 0);
	nimln_(164, "hashes.nim");
	i = ((NI) 0);
	nimln_(165, "hashes.nim");
	xLen = (x ? x->Sup.len : 0);
	{
		nimln_(166, "hashes.nim");
		while (1) {
			NIM_CHAR c;
			if (!(i < xLen)) goto LA2;
			nimln_(167, "hashes.nim");
			if (!x || (NU)(i) >= (NU)(x->Sup.len)) raiseIndexError();
			c = x->data[i];
			nimln_(168, "hashes.nim");
			{
				NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_7;
				if (!((NU8)(c) == (NU8)(95))) goto LA5_;
				nimln_(169, "hashes.nim");
				TM_7tkD9cFJSchVDwHuwaY9bP9bA_7 = addInt(i, ((NI) 1));
				i = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_7);
			}
			goto LA3_;
			LA5_: ;
			{
				NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_9;
				nimln_(171, "hashes.nim");
				{
					NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_8;
					if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA10_;
					nimln_(172, "hashes.nim");
					TM_7tkD9cFJSchVDwHuwaY9bP9bA_8 = addInt(((NU8)(c)), ((NI) 32));
					c = ((NIM_CHAR) (((NI)chckRange((NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_8), ((NI) 0), ((NI) 255)))));
				}
				LA10_: ;
				nimln_(173, "hashes.nim");
				h = emarkamp__6dtCP6C39bxOkT4wrIPJwKghashes(h, ((NU8)(c)));
				nimln_(174, "hashes.nim");
				TM_7tkD9cFJSchVDwHuwaY9bP9bA_9 = addInt(i, ((NI) 1));
				i = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_9);
			}
			LA3_: ;
		} LA2: ;
	}
	nimln_(176, "hashes.nim");
	result = emarkdollar__zs9byUtT9cNi2e9clB27b2cUAhashes(h);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_hashesInit000)(void) {
	nimfr_("hashes", "hashes.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_hashesDatInit000)(void) {
}

