/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/benji/.nim/lib -o /home/benji/dev/nim/website/src/nimcache/stdlib_asyncstreams.c.o /home/benji/dev/nim/website/src/nimcache/stdlib_asyncstreams.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow;
typedef struct tyObject_Deque_r7fe9bPx0N9axj4bqNXnnjcQ tyObject_Deque_r7fe9bPx0N9axj4bqNXnnjcQ;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_FuturecolonObjectType__9cGbW9cUmV0peAwvBhoDzUzg tyObject_FuturecolonObjectType__9cGbW9cUmV0peAwvBhoDzUzg;
typedef struct Exception Exception;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_FuturecolonObjectType__3vdYXYYEsLueJ8n9aJI0Phg tyObject_FuturecolonObjectType__3vdYXYYEsLueJ8n9aJI0Phg;
typedef struct tyObject_Env_libslashpureslashasyncstreamsdotnim__MxO8EqBd7hF9b2XW1cvEqQQ tyObject_Env_libslashpureslashasyncstreamsdotnim__MxO8EqBd7hF9b2XW1cvEqQQ;
typedef struct tyObject_Env_libslashpureslashasyncstreamsdotnim__5Q6qB0oQ7C5zpB2ZI1tnzw tyObject_Env_libslashpureslashasyncstreamsdotnim__5Q6qB0oQ7C5zpB2ZI1tnzw;
typedef struct tyTuple_2uzTbg8jwom7zHhmM2RgHg tyTuple_2uzTbg8jwom7zHhmM2RgHg;
typedef struct tyObject_Env_libslashpureslashasyncstreamsdotnim__sO5O0Qy9bzKs0atwA6HUBAw tyObject_Env_libslashpureslashasyncstreamsdotnim__sO5O0Qy9bzKs0atwA6HUBAw;
typedef struct tyObject_IndexError_b0IIwghFQBADkB2c86kXQA tyObject_IndexError_b0IIwghFQBADkB2c86kXQA;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
struct tyObject_Deque_r7fe9bPx0N9axj4bqNXnnjcQ {
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* data;
NI head;
NI tail;
NI count;
NI mask;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
struct tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow {
tyObject_Deque_r7fe9bPx0N9axj4bqNXnnjcQ queue;
NIM_BOOL finished;
tyProc_IIomJ6ptE6vfJ5zRbATgkQ cb;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q {
NIM_BOOL Field0;
NimStringDesc* Field1;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
NU raise_id;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
typedef N_CLOSURE_PTR(void, TM_LvA9bOHOh81BfXHW59b9aN6Ng_7) (void);
typedef N_CLOSURE_PTR(void, TM_LvA9bOHOh81BfXHW59b9aN6Ng_8) (void);
struct tyObject_Env_libslashpureslashasyncstreamsdotnim__MxO8EqBd7hF9b2XW1cvEqQQ {
  RootObj Sup;
NI colonstate_;
tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow* future1;
tyObject_FuturecolonObjectType__3vdYXYYEsLueJ8n9aJI0Phg* resFut2;
tyProc_IIomJ6ptE6vfJ5zRbATgkQ savedCb3;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow* future, void* ClE_0);
void* ClE_0;
} tyProc_0DUP6Cgw9aSxO4HiOHJCIDg;
struct tyObject_Env_libslashpureslashasyncstreamsdotnim__5Q6qB0oQ7C5zpB2ZI1tnzw {
  RootObj Sup;
NI colonstate_;
tyProc_0DUP6Cgw9aSxO4HiOHJCIDg cb1;
tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow* future2;
};
struct tyTuple_2uzTbg8jwom7zHhmM2RgHg {
void* Field0;
tyObject_Env_libslashpureslashasyncstreamsdotnim__sO5O0Qy9bzKs0atwA6HUBAw* Field1;
};
typedef N_CLOSURE_PTR(void, TM_LvA9bOHOh81BfXHW59b9aN6Ng_13) (tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow* future);
struct tyObject_IndexError_b0IIwghFQBADkB2c86kXQA {
  Exception Sup;
};
typedef N_CLOSURE_PTR(void, TM_LvA9bOHOh81BfXHW59b9aN6Ng_17) (void);
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_M3BGBZ2242oJbQphf8pBxQ)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, initDeque_SsGxD9c1CPCqs9bjRMMyOgCA)(NI initialSize, tyObject_Deque_r7fe9bPx0N9axj4bqNXnnjcQ* Result);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__9cGbW9cUmV0peAwvBhoDzUzg*, newFuture_bCnF9bjjSsPjDNJUMtWd8NA)(NimStringDesc* fromProc);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, fail_hp9adZHZNNdxGEBIpBPO9aLA)(tyObject_FuturecolonObjectType__9cGbW9cUmV0peAwvBhoDzUzg* future, Exception* error);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, addLast_7bxBx85Hy9cnwjgDSyknWrg)(tyObject_Deque_r7fe9bPx0N9axj4bqNXnnjcQ* deq, NimStringDesc* item);
N_LIB_PRIVATE N_NIMCALL(void, complete_KZMQLA9buvYp8Ta72fC7GPQ)(tyObject_FuturecolonObjectType__9cGbW9cUmV0peAwvBhoDzUzg* future);
static N_NIMCALL(void, Marker_tyRef_b2DiuvSHsB9aBtE9aIU9aJHfw)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__3vdYXYYEsLueJ8n9aJI0Phg*, newFuture_7pX0KGiHlnI3re3YS8XJAg)(NimStringDesc* fromProc);
N_LIB_PRIVATE N_NIMCALL(void, callbackeq__5ShITEvRtBIiaUKXXfbLdA)(tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow* future, tyProc_0DUP6Cgw9aSxO4HiOHJCIDg cb);
static N_NIMCALL(void, Marker_tyRef_3ieeSOl9cLPYOvHasDp9cqvQ)(void* p, NI op);
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous__OeMBsN8JumbjJScVtQ2Diw)(void* ClE_0);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size);
static N_INLINE(NI, len_Jc9a6cz2dfjnMTCwTJB8Aqgasyncstreams)(tyObject_Deque_r7fe9bPx0N9axj4bqNXnnjcQ* deq);
N_LIB_PRIVATE N_NIMCALL(void, callSoon_QRqbRWvB9aOehus0Vh9a8KSg)(tyProc_IIomJ6ptE6vfJ5zRbATgkQ cbproc);
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous__oquNePDKzv1I4OjBscBT9bQ)(tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow* fs, void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished_h1Y638AHuVl1w9cwuVIOZ1A)(tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow* future);
static N_INLINE(NimStringDesc*, popFirst_zXBM23N2F8AXZzk9cNvdNFgasyncstreams)(tyObject_Deque_r7fe9bPx0N9axj4bqNXnnjcQ* deq);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
static N_INLINE(NI, addInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished_83u87qNcRoPPs6sjQ3o0vA)(tyObject_FuturecolonObjectType__3vdYXYYEsLueJ8n9aJI0Phg* future);
N_LIB_PRIVATE N_NIMCALL(void, complete_5lHw1An9ae7KC1LOOjqEUFw)(tyObject_FuturecolonObjectType__3vdYXYYEsLueJ8n9aJI0Phg* future, tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q val);
TNimType NTI_9blHsNmC9ciX9ag8y9cCD0feow_;
extern TNimType NTI_r7fe9bPx0N9axj4bqNXnnjcQ_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTI_IIomJ6ptE6vfJ5zRbATgkQ_;
TNimType NTI_M3BGBZ2242oJbQphf8pBxQ_;
TNimType NTI_ubXr9bFCXs9bc35NkwsYmx2Q_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_yCEN9anxCD6mzBxGjuaRBdg_;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_MxO8EqBd7hF9b2XW1cvEqQQ_;
extern TNimType NTI_xHTZrq9aYs6boc9bCba0JbpQ_;
extern TNimType NTI_NBM29bblIdbutkGN9caorTVw_;
TNimType NTI_b2DiuvSHsB9aBtE9aIU9aJHfw_;
TNimType NTI_5Q6qB0oQ7C5zpB2ZI1tnzw_;
TNimType NTI_0DUP6Cgw9aSxO4HiOHJCIDg_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTI_58EFneeS9at7cA541QCoGAw_;
TNimType NTI_3ieeSOl9cLPYOvHasDp9cqvQ_;
extern TNimType NTI_z58cIdR0vOibqJ0QwYvB3Q_;
extern TNimType NTI_b0IIwghFQBADkB2c86kXQA_;
static NIM_CONST tyProc_IIomJ6ptE6vfJ5zRbATgkQ TM_LvA9bOHOh81BfXHW59b9aN6Ng_4 = {NIM_NIL,NIM_NIL};
STRING_LITERAL(TM_LvA9bOHOh81BfXHW59b9aN6Ng_5, "FutureStream.put", 16);
STRING_LITERAL(TM_LvA9bOHOh81BfXHW59b9aN6Ng_6, "FutureStream is finished and so no longer accepts new data.", 59);
STRING_LITERAL(TM_LvA9bOHOh81BfXHW59b9aN6Ng_10, "FutureStream.take", 17);
STRING_LITERAL(TM_LvA9bOHOh81BfXHW59b9aN6Ng_14, "Empty deque.", 12);
static N_NIMCALL(void, Marker_tyRef_M3BGBZ2242oJbQphf8pBxQ)(void* p, NI op) {
	tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow* a;
	a = (tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow*)p;
	nimGCvisit((void*)(*a).queue.data, op);
	nimGCvisit((void*)(*a).cb.ClE_0, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		nimln_(185, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln_(218, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(396, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(264, "gc.nim");
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(396, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		nimln_(265, "gc.nim");
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow*, newFutureStream_1hms9c88xi02tpp9a56wsGUA)(NimStringDesc* fromProc) {
	tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow* result;
	tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow* T1_;
	nimfr_("newFutureStream", "asyncstreams.nim");
	result = (tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow*)0;
	nimln_(27, "asyncstreams.nim");
	T1_ = (tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow*)0;
	T1_ = (tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow*) newObj((&NTI_M3BGBZ2242oJbQphf8pBxQ_), sizeof(tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow));
	(*T1_).finished = NIM_FALSE;
	asgnRef((void**) (&(*T1_).cb.ClE_0), TM_LvA9bOHOh81BfXHW59b9aN6Ng_4.ClE_0);
	(*T1_).cb.ClP_0 = TM_LvA9bOHOh81BfXHW59b9aN6Ng_4.ClP_0;
	result = T1_;
	nimln_(28, "asyncstreams.nim");
	initDeque_SsGxD9c1CPCqs9bjRMMyOgCA(((NI) 4), (&(*result).queue));
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		nimln_(185, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln_(252, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__9cGbW9cUmV0peAwvBhoDzUzg*, write_tNiYf0qZA9b4ryXCGu1QV8Q)(tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow* future, NimStringDesc* value) {
	tyObject_FuturecolonObjectType__9cGbW9cUmV0peAwvBhoDzUzg* result;
	nimfr_("write", "asyncstreams.nim");
{	result = (tyObject_FuturecolonObjectType__9cGbW9cUmV0peAwvBhoDzUzg*)0;
	nimln_(60, "asyncstreams.nim");
	result = newFuture_bCnF9bjjSsPjDNJUMtWd8NA(((NimStringDesc*) &TM_LvA9bOHOh81BfXHW59b9aN6Ng_5));
	nimln_(61, "asyncstreams.nim");
	{
		NimStringDesc* msg;
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
		NimStringDesc* T5_;
		Exception* T6_;
		if (!(*future).finished) goto LA3_;
		nimln_(62, "asyncstreams.nim");
		msg = copyString(((NimStringDesc*) &TM_LvA9bOHOh81BfXHW59b9aN6Ng_6));
		nimln_(63, "asyncstreams.nim");
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		nimln_(2785, "system.nim");
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		nimln_(63, "asyncstreams.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(msg);
		if (T5_) nimGCunrefNoCycle(T5_);
		nimln_(2780, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		T6_ = (Exception*)0;
		T6_ = &e->Sup;
		fail_hp9adZHZNNdxGEBIpBPO9aLA(result, T6_);
		nimln_(64, "asyncstreams.nim");
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(67, "asyncstreams.nim");
	addLast_7bxBx85Hy9cnwjgDSyknWrg((&(*future).queue), value);
	nimln_(68, "asyncstreams.nim");
	{
		if (!!(((*future).cb.ClP_0 == 0))) goto LA9_;
		(*future).cb.ClE_0? (*future).cb.ClP_0((*future).cb.ClE_0):((TM_LvA9bOHOh81BfXHW59b9aN6Ng_7)((*future).cb.ClP_0))();
	}
	LA9_: ;
	nimln_(69, "asyncstreams.nim");
	complete_KZMQLA9buvYp8Ta72fC7GPQ(result);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, complete_nB4B2iZbX27lb3fiFo1uwQ)(tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow* future) {
	nimfr_("complete", "asyncstreams.nim");
	nimln_(32, "asyncstreams.nim");
	(*future).finished = NIM_TRUE;
	nimln_(33, "asyncstreams.nim");
	{
		if (!!(((*future).cb.ClP_0 == 0))) goto LA3_;
		nimln_(34, "asyncstreams.nim");
		(*future).cb.ClE_0? (*future).cb.ClP_0((*future).cb.ClE_0):((TM_LvA9bOHOh81BfXHW59b9aN6Ng_8)((*future).cb.ClP_0))();
	}
	LA3_: ;
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_b2DiuvSHsB9aBtE9aIU9aJHfw)(void* p, NI op) {
	tyObject_Env_libslashpureslashasyncstreamsdotnim__MxO8EqBd7hF9b2XW1cvEqQQ* a;
	a = (tyObject_Env_libslashpureslashasyncstreamsdotnim__MxO8EqBd7hF9b2XW1cvEqQQ*)p;
	nimGCvisit((void*)(*a).future1, op);
	nimGCvisit((void*)(*a).resFut2, op);
	nimGCvisit((void*)(*a).savedCb3.ClE_0, op);
}
static N_NIMCALL(void, Marker_tyRef_3ieeSOl9cLPYOvHasDp9cqvQ)(void* p, NI op) {
	tyObject_Env_libslashpureslashasyncstreamsdotnim__5Q6qB0oQ7C5zpB2ZI1tnzw* a;
	a = (tyObject_Env_libslashpureslashasyncstreamsdotnim__5Q6qB0oQ7C5zpB2ZI1tnzw*)p;
	nimGCvisit((void*)(*a).cb1.ClE_0, op);
	nimGCvisit((void*)(*a).future2, op);
}

N_LIB_PRIVATE N_CLOSURE(void, colonanonymous__OeMBsN8JumbjJScVtQ2Diw)(void* ClE_0) {
	tyObject_Env_libslashpureslashasyncstreamsdotnim__5Q6qB0oQ7C5zpB2ZI1tnzw* colonenvP_;
	nimfr_(":anonymous", "asyncstreams.nim");
	colonenvP_ = (tyObject_Env_libslashpureslashasyncstreamsdotnim__5Q6qB0oQ7C5zpB2ZI1tnzw*) ClE_0;
	nimln_(46, "asyncstreams.nim");
	(*colonenvP_).cb1.ClE_0? (*colonenvP_).cb1.ClP_0((*colonenvP_).future2, (*colonenvP_).cb1.ClE_0):((TM_LvA9bOHOh81BfXHW59b9aN6Ng_13)((*colonenvP_).cb1.ClP_0))((*colonenvP_).future2);
	popFrame();
}

static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}

static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem(p, ((int) 0), size);
}

static N_INLINE(NI, len_Jc9a6cz2dfjnMTCwTJB8Aqgasyncstreams)(tyObject_Deque_r7fe9bPx0N9axj4bqNXnnjcQ* deq) {
	NI result;
	nimfr_("len", "deques.nim");
	result = (NI)0;
	nimln_(64, "deques.nim");
	result = (*deq).count;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, callbackeq__5ShITEvRtBIiaUKXXfbLdA)(tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow* future, tyProc_0DUP6Cgw9aSxO4HiOHJCIDg cb) {
	tyObject_Env_libslashpureslashasyncstreamsdotnim__5Q6qB0oQ7C5zpB2ZI1tnzw* colonenv_;
	tyProc_IIomJ6ptE6vfJ5zRbATgkQ T1_;
	nimfr_("callback=", "asyncstreams.nim");
	colonenv_ = (tyObject_Env_libslashpureslashasyncstreamsdotnim__5Q6qB0oQ7C5zpB2ZI1tnzw*)0;
	nimln_(215, "system.nim");
	colonenv_ = (tyObject_Env_libslashpureslashasyncstreamsdotnim__5Q6qB0oQ7C5zpB2ZI1tnzw*) newObj((&NTI_3ieeSOl9cLPYOvHasDp9cqvQ_), sizeof(tyObject_Env_libslashpureslashasyncstreamsdotnim__5Q6qB0oQ7C5zpB2ZI1tnzw));
	(*colonenv_).Sup.m_type = (&NTI_5Q6qB0oQ7C5zpB2ZI1tnzw_);
	nimln_(36, "asyncstreams.nim");
	asgnRef((void**) (&(*colonenv_).future2), future);
	nimln_(37, "asyncstreams.nim");
	asgnRef((void**) (&(*colonenv_).cb1.ClE_0), cb.ClE_0);
	(*colonenv_).cb1.ClP_0 = cb.ClP_0;
	nimln_(46, "asyncstreams.nim");
	nimZeroMem((void*)(&T1_), sizeof(tyProc_IIomJ6ptE6vfJ5zRbATgkQ));
	T1_.ClP_0 = colonanonymous__OeMBsN8JumbjJScVtQ2Diw; T1_.ClE_0 = colonenv_;
	asgnRef((void**) (&(*(*colonenv_).future2).cb.ClE_0), T1_.ClE_0);
	(*(*colonenv_).future2).cb.ClP_0 = T1_.ClP_0;
	nimln_(47, "asyncstreams.nim");
	{
		NIM_BOOL T4_;
		NI T5_;
		T4_ = (NIM_BOOL)0;
		T5_ = (NI)0;
		T5_ = len_Jc9a6cz2dfjnMTCwTJB8Aqgasyncstreams((&(*(*colonenv_).future2).queue));
		T4_ = (((NI) 0) < T5_);
		if (T4_) goto LA6_;
		T4_ = (*(*colonenv_).future2).finished;
		LA6_: ;
		if (!T4_) goto LA7_;
		nimln_(48, "asyncstreams.nim");
		callSoon_QRqbRWvB9aOehus0Vh9a8KSg((*(*colonenv_).future2).cb);
	}
	LA7_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished_h1Y638AHuVl1w9cwuVIOZ1A)(tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow* future) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NI T3_;
	nimfr_("finished", "asyncstreams.nim");
	result = (NIM_BOOL)0;
	nimln_(54, "asyncstreams.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = (*future).finished;
	if (!(T1_)) goto LA2_;
	T3_ = (NI)0;
	T3_ = len_Jc9a6cz2dfjnMTCwTJB8Aqgasyncstreams((&(*future).queue));
	T1_ = (T3_ == ((NI) 0));
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NimStringDesc*, popFirst_zXBM23N2F8AXZzk9cNvdNFgasyncstreams)(tyObject_Deque_r7fe9bPx0N9axj4bqNXnnjcQ* deq) {
	NimStringDesc* result;
	NI TM_LvA9bOHOh81BfXHW59b9aN6Ng_15;
	NI TM_LvA9bOHOh81BfXHW59b9aN6Ng_16;
	nimfr_("popFirst", "deques.nim");
	result = (NimStringDesc*)0;
	nimln_(69, "deques.nim");
	{
		NIM_BOOL T3_;
		tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
		NimStringDesc* T6_;
		nimln_(3469, "system.nim");
		nimln_(69, "deques.nim");
		T3_ = (NIM_BOOL)0;
		T3_ = unlikely(((*deq).count < ((NI) 1)));
		if (!T3_) goto LA4_;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
		nimln_(2785, "system.nim");
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
		(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
		nimln_(70, "deques.nim");
		T6_ = (NimStringDesc*)0;
		T6_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_LvA9bOHOh81BfXHW59b9aN6Ng_14));
		if (T6_) nimGCunrefNoCycle(T6_);
		nimln_(2780, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(70, "deques.nim");
		raiseException((Exception*)e, "IndexError");
	}
	LA4_: ;
	nimln_(172, "deques.nim");
	TM_LvA9bOHOh81BfXHW59b9aN6Ng_15 = subInt((*deq).count, ((NI) 1));
	(*deq).count = (NI)(TM_LvA9bOHOh81BfXHW59b9aN6Ng_15);
	nimln_(173, "deques.nim");
	if (!(*deq).data || (NU)((*deq).head) >= (NU)((*deq).data->Sup.len)) raiseIndexError();
	result = copyString((*deq).data->data[(*deq).head]);
	nimln_(167, "deques.nim");
	if (!(*deq).data || (NU)((*deq).head) >= (NU)((*deq).data->Sup.len)) raiseIndexError();
	genericReset((void*)(&(*deq).data->data[(*deq).head]), (&NTI_77mFvmsOLKik79ci2hXkHEg_));
	nimln_(175, "deques.nim");
	TM_LvA9bOHOh81BfXHW59b9aN6Ng_16 = addInt((*deq).head, ((NI) 1));
	(*deq).head = (NI)((NI)(TM_LvA9bOHOh81BfXHW59b9aN6Ng_16) & (*deq).mask);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_CLOSURE(void, colonanonymous__oquNePDKzv1I4OjBscBT9bQ)(tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow* fs, void* ClE_0) {
	tyObject_Env_libslashpureslashasyncstreamsdotnim__MxO8EqBd7hF9b2XW1cvEqQQ* colonenvP_;
	tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q res;
	nimfr_(":anonymous", "asyncstreams.nim");
	colonenvP_ = (tyObject_Env_libslashpureslashasyncstreamsdotnim__MxO8EqBd7hF9b2XW1cvEqQQ*) ClE_0;
	nimln_(85, "asyncstreams.nim");
	asgnRef((void**) (&(*(*colonenvP_).future1).cb.ClE_0), TM_LvA9bOHOh81BfXHW59b9aN6Ng_4.ClE_0);
	(*(*colonenvP_).future1).cb.ClP_0 = TM_LvA9bOHOh81BfXHW59b9aN6Ng_4.ClP_0;
	nimZeroMem((void*)(&res), sizeof(tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q));
	nimln_(89, "asyncstreams.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = finished_h1Y638AHuVl1w9cwuVIOZ1A(fs);
		if (!T3_) goto LA4_;
		nimln_(91, "asyncstreams.nim");
		res.Field0 = NIM_FALSE;
	}
	goto LA1_;
	LA4_: ;
	{
		nimln_(93, "asyncstreams.nim");
		res.Field0 = NIM_TRUE;
		nimln_(94, "asyncstreams.nim");
		res.Field1 = popFirst_zXBM23N2F8AXZzk9cNvdNFgasyncstreams((&(*fs).queue));
	}
	LA1_: ;
	nimln_(96, "asyncstreams.nim");
	{
		NIM_BOOL T9_;
		T9_ = (NIM_BOOL)0;
		T9_ = finished_83u87qNcRoPPs6sjQ3o0vA((*colonenvP_).resFut2);
		if (!!(T9_)) goto LA10_;
		nimln_(97, "asyncstreams.nim");
		complete_5lHw1An9ae7KC1LOOjqEUFw((*colonenvP_).resFut2, res);
	}
	LA10_: ;
	nimln_(100, "asyncstreams.nim");
	{
		if (!!(((*colonenvP_).savedCb3.ClP_0 == 0))) goto LA14_;
		(*colonenvP_).savedCb3.ClE_0? (*colonenvP_).savedCb3.ClP_0((*colonenvP_).savedCb3.ClE_0):((TM_LvA9bOHOh81BfXHW59b9aN6Ng_17)((*colonenvP_).savedCb3.ClP_0))();
	}
	LA14_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__3vdYXYYEsLueJ8n9aJI0Phg*, read_69b2Sr2eVU1MQ5kavztqgHg)(tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow* future) {
	tyObject_FuturecolonObjectType__3vdYXYYEsLueJ8n9aJI0Phg* result;
	tyObject_Env_libslashpureslashasyncstreamsdotnim__MxO8EqBd7hF9b2XW1cvEqQQ* colonenv_;
	tyProc_0DUP6Cgw9aSxO4HiOHJCIDg T1_;
	nimfr_("read", "asyncstreams.nim");
{	result = (tyObject_FuturecolonObjectType__3vdYXYYEsLueJ8n9aJI0Phg*)0;
	colonenv_ = (tyObject_Env_libslashpureslashasyncstreamsdotnim__MxO8EqBd7hF9b2XW1cvEqQQ*)0;
	nimln_(215, "system.nim");
	colonenv_ = (tyObject_Env_libslashpureslashasyncstreamsdotnim__MxO8EqBd7hF9b2XW1cvEqQQ*) newObj((&NTI_b2DiuvSHsB9aBtE9aIU9aJHfw_), sizeof(tyObject_Env_libslashpureslashasyncstreamsdotnim__MxO8EqBd7hF9b2XW1cvEqQQ));
	(*colonenv_).Sup.m_type = (&NTI_MxO8EqBd7hF9b2XW1cvEqQQ_);
	nimln_(71, "asyncstreams.nim");
	asgnRef((void**) (&(*colonenv_).future1), future);
	nimln_(80, "asyncstreams.nim");
	asgnRef((void**) (&(*colonenv_).resFut2), newFuture_7pX0KGiHlnI3re3YS8XJAg(((NimStringDesc*) &TM_LvA9bOHOh81BfXHW59b9aN6Ng_10)));
	nimln_(81, "asyncstreams.nim");
	asgnRef((void**) (&(*colonenv_).savedCb3.ClE_0), (*(*colonenv_).future1).cb.ClE_0);
	(*colonenv_).savedCb3.ClP_0 = (*(*colonenv_).future1).cb.ClP_0;
	nimln_(82, "asyncstreams.nim");
	nimZeroMem((void*)(&T1_), sizeof(tyProc_0DUP6Cgw9aSxO4HiOHJCIDg));
	T1_.ClP_0 = colonanonymous__oquNePDKzv1I4OjBscBT9bQ; T1_.ClE_0 = colonenv_;
	callbackeq__5ShITEvRtBIiaUKXXfbLdA((*colonenv_).future1, T1_);
	nimln_(101, "asyncstreams.nim");
	result = (*colonenv_).resFut2;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_asyncstreamsInit000)(void) {
	nimfr_("asyncstreams", "asyncstreams.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_asyncstreamsDatInit000)(void) {
static TNimNode* TM_LvA9bOHOh81BfXHW59b9aN6Ng_2[3];
static TNimNode* TM_LvA9bOHOh81BfXHW59b9aN6Ng_3[2];
static TNimNode* TM_LvA9bOHOh81BfXHW59b9aN6Ng_9[4];
static TNimNode* TM_LvA9bOHOh81BfXHW59b9aN6Ng_11[3];
static TNimNode* TM_LvA9bOHOh81BfXHW59b9aN6Ng_12[2];
static TNimNode TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[19];
NTI_9blHsNmC9ciX9ag8y9cCD0feow_.size = sizeof(tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow);
NTI_9blHsNmC9ciX9ag8y9cCD0feow_.kind = 18;
NTI_9blHsNmC9ciX9ag8y9cCD0feow_.base = 0;
TM_LvA9bOHOh81BfXHW59b9aN6Ng_2[0] = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[1];
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[1].kind = 1;
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[1].offset = offsetof(tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow, queue);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[1].typ = (&NTI_r7fe9bPx0N9axj4bqNXnnjcQ_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[1].name = "queue";
TM_LvA9bOHOh81BfXHW59b9aN6Ng_2[1] = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[2];
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[2].kind = 1;
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[2].offset = offsetof(tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow, finished);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[2].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[2].name = "finished";
TM_LvA9bOHOh81BfXHW59b9aN6Ng_2[2] = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[3];
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[3].kind = 1;
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[3].offset = offsetof(tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow, cb);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[3].typ = (&NTI_IIomJ6ptE6vfJ5zRbATgkQ_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[3].name = "cb";
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[0].len = 3; TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[0].kind = 2; TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[0].sons = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_2[0];
NTI_9blHsNmC9ciX9ag8y9cCD0feow_.node = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[0];
NTI_M3BGBZ2242oJbQphf8pBxQ_.size = sizeof(tyObject_FutureStreamcolonObjectType__9blHsNmC9ciX9ag8y9cCD0feow*);
NTI_M3BGBZ2242oJbQphf8pBxQ_.kind = 22;
NTI_M3BGBZ2242oJbQphf8pBxQ_.base = (&NTI_9blHsNmC9ciX9ag8y9cCD0feow_);
NTI_M3BGBZ2242oJbQphf8pBxQ_.marker = Marker_tyRef_M3BGBZ2242oJbQphf8pBxQ;
NTI_ubXr9bFCXs9bc35NkwsYmx2Q_.size = sizeof(tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q);
NTI_ubXr9bFCXs9bc35NkwsYmx2Q_.kind = 18;
NTI_ubXr9bFCXs9bc35NkwsYmx2Q_.base = 0;
NTI_ubXr9bFCXs9bc35NkwsYmx2Q_.flags = 2;
TM_LvA9bOHOh81BfXHW59b9aN6Ng_3[0] = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[5];
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[5].kind = 1;
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[5].offset = offsetof(tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q, Field0);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[5].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[5].name = "Field0";
TM_LvA9bOHOh81BfXHW59b9aN6Ng_3[1] = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[6];
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[6].kind = 1;
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[6].offset = offsetof(tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q, Field1);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[6].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[6].name = "Field1";
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[4].len = 2; TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[4].kind = 2; TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[4].sons = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_3[0];
NTI_ubXr9bFCXs9bc35NkwsYmx2Q_.node = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[4];
NTI_MxO8EqBd7hF9b2XW1cvEqQQ_.size = sizeof(tyObject_Env_libslashpureslashasyncstreamsdotnim__MxO8EqBd7hF9b2XW1cvEqQQ);
NTI_MxO8EqBd7hF9b2XW1cvEqQQ_.kind = 17;
NTI_MxO8EqBd7hF9b2XW1cvEqQQ_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_9[0] = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[8];
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[8].kind = 1;
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[8].offset = offsetof(tyObject_Env_libslashpureslashasyncstreamsdotnim__MxO8EqBd7hF9b2XW1cvEqQQ, colonstate_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[8].typ = (&NTI_xHTZrq9aYs6boc9bCba0JbpQ_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[8].name = ":state";
TM_LvA9bOHOh81BfXHW59b9aN6Ng_9[1] = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[9];
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[9].kind = 1;
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[9].offset = offsetof(tyObject_Env_libslashpureslashasyncstreamsdotnim__MxO8EqBd7hF9b2XW1cvEqQQ, future1);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[9].typ = (&NTI_M3BGBZ2242oJbQphf8pBxQ_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[9].name = "future1";
TM_LvA9bOHOh81BfXHW59b9aN6Ng_9[2] = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[10];
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[10].kind = 1;
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[10].offset = offsetof(tyObject_Env_libslashpureslashasyncstreamsdotnim__MxO8EqBd7hF9b2XW1cvEqQQ, resFut2);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[10].typ = (&NTI_NBM29bblIdbutkGN9caorTVw_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[10].name = "resFut2";
TM_LvA9bOHOh81BfXHW59b9aN6Ng_9[3] = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[11];
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[11].kind = 1;
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[11].offset = offsetof(tyObject_Env_libslashpureslashasyncstreamsdotnim__MxO8EqBd7hF9b2XW1cvEqQQ, savedCb3);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[11].typ = (&NTI_IIomJ6ptE6vfJ5zRbATgkQ_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[11].name = "savedCb3";
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[7].len = 4; TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[7].kind = 2; TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[7].sons = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_9[0];
NTI_MxO8EqBd7hF9b2XW1cvEqQQ_.node = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[7];
NTI_b2DiuvSHsB9aBtE9aIU9aJHfw_.size = sizeof(tyObject_Env_libslashpureslashasyncstreamsdotnim__MxO8EqBd7hF9b2XW1cvEqQQ*);
NTI_b2DiuvSHsB9aBtE9aIU9aJHfw_.kind = 22;
NTI_b2DiuvSHsB9aBtE9aIU9aJHfw_.base = (&NTI_MxO8EqBd7hF9b2XW1cvEqQQ_);
NTI_b2DiuvSHsB9aBtE9aIU9aJHfw_.marker = Marker_tyRef_b2DiuvSHsB9aBtE9aIU9aJHfw;
NTI_5Q6qB0oQ7C5zpB2ZI1tnzw_.size = sizeof(tyObject_Env_libslashpureslashasyncstreamsdotnim__5Q6qB0oQ7C5zpB2ZI1tnzw);
NTI_5Q6qB0oQ7C5zpB2ZI1tnzw_.kind = 17;
NTI_5Q6qB0oQ7C5zpB2ZI1tnzw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_11[0] = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[13];
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[13].kind = 1;
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[13].offset = offsetof(tyObject_Env_libslashpureslashasyncstreamsdotnim__5Q6qB0oQ7C5zpB2ZI1tnzw, colonstate_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[13].typ = (&NTI_xHTZrq9aYs6boc9bCba0JbpQ_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[13].name = ":state";
TM_LvA9bOHOh81BfXHW59b9aN6Ng_11[1] = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[14];
NTI_0DUP6Cgw9aSxO4HiOHJCIDg_.size = sizeof(tyTuple_2uzTbg8jwom7zHhmM2RgHg);
NTI_0DUP6Cgw9aSxO4HiOHJCIDg_.kind = 18;
NTI_0DUP6Cgw9aSxO4HiOHJCIDg_.base = 0;
TM_LvA9bOHOh81BfXHW59b9aN6Ng_12[0] = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[16];
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[16].kind = 1;
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[16].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field0);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[16].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[16].name = "Field0";
TM_LvA9bOHOh81BfXHW59b9aN6Ng_12[1] = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[17];
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[17].kind = 1;
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[17].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field1);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[17].typ = (&NTI_58EFneeS9at7cA541QCoGAw_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[17].name = "Field1";
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[15].len = 2; TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[15].kind = 2; TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[15].sons = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_12[0];
NTI_0DUP6Cgw9aSxO4HiOHJCIDg_.node = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[15];
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[14].kind = 1;
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[14].offset = offsetof(tyObject_Env_libslashpureslashasyncstreamsdotnim__5Q6qB0oQ7C5zpB2ZI1tnzw, cb1);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[14].typ = (&NTI_0DUP6Cgw9aSxO4HiOHJCIDg_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[14].name = "cb1";
TM_LvA9bOHOh81BfXHW59b9aN6Ng_11[2] = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[18];
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[18].kind = 1;
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[18].offset = offsetof(tyObject_Env_libslashpureslashasyncstreamsdotnim__5Q6qB0oQ7C5zpB2ZI1tnzw, future2);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[18].typ = (&NTI_M3BGBZ2242oJbQphf8pBxQ_);
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[18].name = "future2";
TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[12].len = 3; TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[12].kind = 2; TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[12].sons = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_11[0];
NTI_5Q6qB0oQ7C5zpB2ZI1tnzw_.node = &TM_LvA9bOHOh81BfXHW59b9aN6Ng_0[12];
NTI_3ieeSOl9cLPYOvHasDp9cqvQ_.size = sizeof(tyObject_Env_libslashpureslashasyncstreamsdotnim__5Q6qB0oQ7C5zpB2ZI1tnzw*);
NTI_3ieeSOl9cLPYOvHasDp9cqvQ_.kind = 22;
NTI_3ieeSOl9cLPYOvHasDp9cqvQ_.base = (&NTI_5Q6qB0oQ7C5zpB2ZI1tnzw_);
NTI_3ieeSOl9cLPYOvHasDp9cqvQ_.marker = Marker_tyRef_3ieeSOl9cLPYOvHasDp9cqvQ;
}

