/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/benji/.nim/lib -o /home/benji/dev/nim/website/src/nimcache/stdlib_strtabs.c.o /home/benji/dev/nim/website/src/nimcache/stdlib_strtabs.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw;
typedef struct RootObj RootObj;
typedef struct tySequence_xv3aaFd3JCw8NbmALHiezQ tySequence_xv3aaFd3JCw8NbmALHiezQ;
typedef struct tyTuple_sPaDkVPSC0MkcoXCxPH9ccA tyTuple_sPaDkVPSC0MkcoXCxPH9ccA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
typedef NU8 tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ;
struct tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw {
  RootObj Sup;
NI counter;
tySequence_xv3aaFd3JCw8NbmALHiezQ* data;
tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_sPaDkVPSC0MkcoXCxPH9ccA {
NimStringDesc* Field0;
NimStringDesc* Field1;
NIM_BOOL Field2;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct tySequence_xv3aaFd3JCw8NbmALHiezQ {
  TGenericSeq Sup;
  tyTuple_sPaDkVPSC0MkcoXCxPH9ccA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_xv3aaFd3JCw8NbmALHiezQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_pkhT5bYRU9ayIZ9cBuuCx4Xw)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*, nstnewStringTable)(tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(void, nstPut)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key, NimStringDesc* val);
N_LIB_PRIVATE N_NIMCALL(NI, rawGet_g4UMXDeIi4hi42WuIY9cM4A)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(NI, myhash_g4UMXDeIi4hi42WuIY9cM4A_2)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreCase_uBstFm5SYVQeOL3j9c9bc58A_2)(NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreStyle_uBstFm5SYVQeOL3j9c9bc58A_3)(NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, myCmp_6dqTqYQ9cC63hkWdN9br54EA)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* a, NimStringDesc* b);
N_LIB_PRIVATE N_NIMCALL(NI, cmp_xEnKsp9cfvO7Do9cTYXo8eJw)(NimStringDesc* x, NimStringDesc* y);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NI, nextTry_4tI2vxIqcy1tNTBufKNbkgstrtabs)(NI h, NI maxHash);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mustRehash_K02IbeDTRFZ9b4m0M4Kahlg)(NI length, NI counter);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_1rn449bBULy9cLwCWr7ISAqg)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_HXPVLnHem3T2vyDx7gHMBQ)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, tySequence_xv3aaFd3JCw8NbmALHiezQ** data, NimStringDesc* key, NimStringDesc* val);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_sPaDkVPSC0MkcoXCxPH9ccA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_xv3aaFd3JCw8NbmALHiezQ_;
TNimType NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_;
TNimType NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_ZT9crccxweoChVXn9cHcxIXQ_9, "\012counter < length ", 18);
static N_NIMCALL(void, Marker_tySequence_xv3aaFd3JCw8NbmALHiezQ)(void* p, NI op) {
	tySequence_xv3aaFd3JCw8NbmALHiezQ* a;
	NI T1_;
	a = (tySequence_xv3aaFd3JCw8NbmALHiezQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field0, op);
	nimGCvisit((void*)a->data[T1_].Field1, op);
	}
}
static N_NIMCALL(void, Marker_tyRef_pkhT5bYRU9ayIZ9cBuuCx4Xw)(void* p, NI op) {
	tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* a;
	a = (tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*)p;
	nimGCvisit((void*)(*a).data, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		nimln_(185, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln_(252, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*, nstnewStringTable)(tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode) {
	tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* result;
	nimfr_("newStringTable", "strtabs.nim");
	result = (tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*)0;
	nimln_(177, "strtabs.nim");
	result = (tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*) newObj((&NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_), sizeof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw));
	(*result).Sup.m_type = (&NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_);
	nimln_(178, "strtabs.nim");
	(*result).mode = mode;
	nimln_(179, "strtabs.nim");
	(*result).counter = ((NI) 0);
	nimln_(180, "strtabs.nim");
	if ((*result).data) { nimGCunrefNoCycle((*result).data); (*result).data = NIM_NIL; }
	(*result).data = (tySequence_xv3aaFd3JCw8NbmALHiezQ*) newSeqRC1((&NTI_xv3aaFd3JCw8NbmALHiezQ_), ((NI) 64));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, myhash_g4UMXDeIi4hi42WuIY9cM4A_2)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key) {
	NI result;
	nimfr_("myhash", "strtabs.nim");
	result = (NI)0;
	nimln_(76, "strtabs.nim");
	switch ((*t).mode) {
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 0):
	{
		nimln_(77, "strtabs.nim");
		result = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	}
	break;
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 1):
	{
		nimln_(78, "strtabs.nim");
		result = hashIgnoreCase_uBstFm5SYVQeOL3j9c9bc58A_2(key);
	}
	break;
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 2):
	{
		nimln_(79, "strtabs.nim");
		result = hashIgnoreStyle_uBstFm5SYVQeOL3j9c9bc58A_3(key);
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, myCmp_6dqTqYQ9cC63hkWdN9br54EA)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	nimfr_("myCmp", "strtabs.nim");
	result = (NIM_BOOL)0;
	nimln_(82, "strtabs.nim");
	switch ((*t).mode) {
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 0):
	{
		NI T2_;
		nimln_(83, "strtabs.nim");
		T2_ = (NI)0;
		T2_ = cmp_xEnKsp9cfvO7Do9cTYXo8eJw(a, b);
		result = (T2_ == ((NI) 0));
	}
	break;
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 1):
	{
		NI T4_;
		nimln_(84, "strtabs.nim");
		T4_ = (NI)0;
		T4_ = nsuCmpIgnoreCase(a, b);
		result = (T4_ == ((NI) 0));
	}
	break;
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 2):
	{
		NI T6_;
		nimln_(85, "strtabs.nim");
		T6_ = (NI)0;
		T6_ = nsuCmpIgnoreStyle(a, b);
		result = (T6_ == ((NI) 0));
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, nextTry_4tI2vxIqcy1tNTBufKNbkgstrtabs)(NI h, NI maxHash) {
	NI result;
	NI TM_ZT9crccxweoChVXn9cHcxIXQ_7;
	NI TM_ZT9crccxweoChVXn9cHcxIXQ_8;
	nimfr_("nextTry", "strtabs.nim");
	result = (NI)0;
	nimln_(92, "strtabs.nim");
	TM_ZT9crccxweoChVXn9cHcxIXQ_7 = mulInt(((NI) 5), h);
	TM_ZT9crccxweoChVXn9cHcxIXQ_8 = addInt((NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_7), ((NI) 1));
	result = (NI)((NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_8) & maxHash);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, rawGet_g4UMXDeIi4hi42WuIY9cM4A)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key) {
	NI result;
	NI h;
	NI T1_;
	NI T2_;
	nimfr_("rawGet", "strtabs.nim");
{	result = (NI)0;
	nimln_(95, "strtabs.nim");
	T1_ = (NI)0;
	T1_ = myhash_g4UMXDeIi4hi42WuIY9cM4A_2(t, key);
	T2_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
	h = (NI)(T1_ & T2_);
	{
		nimln_(96, "strtabs.nim");
		while (1) {
			NI T10_;
			if (!(*t).data || (NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			if (!(*t).data->data[h].Field2) goto LA4;
			nimln_(97, "strtabs.nim");
			{
				NIM_BOOL T7_;
				if (!(*t).data || (NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				T7_ = (NIM_BOOL)0;
				T7_ = myCmp_6dqTqYQ9cC63hkWdN9br54EA(t, (*t).data->data[h].Field0, key);
				if (!T7_) goto LA8_;
				nimln_(98, "strtabs.nim");
				result = h;
				goto BeforeRet_;
			}
			LA8_: ;
			nimln_(99, "strtabs.nim");
			T10_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
			h = nextTry_4tI2vxIqcy1tNTBufKNbkgstrtabs(h, T10_);
		} LA4: ;
	}
	nimln_(100, "strtabs.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mustRehash_K02IbeDTRFZ9b4m0M4Kahlg)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL T5_;
	NI TM_ZT9crccxweoChVXn9cHcxIXQ_10;
	NI TM_ZT9crccxweoChVXn9cHcxIXQ_11;
	NI TM_ZT9crccxweoChVXn9cHcxIXQ_12;
	nimfr_("mustRehash", "strtabs.nim");
	result = (NIM_BOOL)0;
	nimln_(88, "strtabs.nim");
	{
		if (!!((counter < length))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_ZT9crccxweoChVXn9cHcxIXQ_9));
	}
	LA3_: ;
	nimln_(89, "strtabs.nim");
	T5_ = (NIM_BOOL)0;
	TM_ZT9crccxweoChVXn9cHcxIXQ_10 = mulInt(length, ((NI) 2));
	TM_ZT9crccxweoChVXn9cHcxIXQ_11 = mulInt(counter, ((NI) 3));
	T5_ = ((NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_10) < (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_11));
	if (T5_) goto LA6_;
	TM_ZT9crccxweoChVXn9cHcxIXQ_12 = subInt(length, counter);
	T5_ = ((NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_12) < ((NI) 4));
	LA6_: ;
	result = T5_;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, rawInsert_HXPVLnHem3T2vyDx7gHMBQ)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, tySequence_xv3aaFd3JCw8NbmALHiezQ** data, NimStringDesc* key, NimStringDesc* val) {
	NI h;
	NI T1_;
	NI T2_;
	NimStringDesc* T6_;
	NimStringDesc* T7_;
	nimfr_("rawInsert", "strtabs.nim");
	nimln_(132, "strtabs.nim");
	T1_ = (NI)0;
	T1_ = myhash_g4UMXDeIi4hi42WuIY9cM4A_2(t, key);
	T2_ = ((*data) ? ((*data)->Sup.len-1) : -1);
	h = (NI)(T1_ & T2_);
	{
		nimln_(133, "strtabs.nim");
		while (1) {
			NI T5_;
			if (!(*data) || (NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
			if (!(*data)->data[h].Field2) goto LA4;
			nimln_(134, "strtabs.nim");
			T5_ = ((*data) ? ((*data)->Sup.len-1) : -1);
			h = nextTry_4tI2vxIqcy1tNTBufKNbkgstrtabs(h, T5_);
		} LA4: ;
	}
	if (!(*data) || (NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(135, "strtabs.nim");
	T6_ = (NimStringDesc*)0;
	T6_ = (*data)->data[h].Field0; (*data)->data[h].Field0 = copyStringRC1(key);
	if (T6_) nimGCunrefNoCycle(T6_);
	if (!(*data) || (NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(136, "strtabs.nim");
	T7_ = (NimStringDesc*)0;
	T7_ = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(val);
	if (T7_) nimGCunrefNoCycle(T7_);
	if (!(*data) || (NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(137, "strtabs.nim");
	(*data)->data[h].Field2 = NIM_TRUE;
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(396, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(396, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			nimln_(185, "gc.nim");
			(*c_2).refcount -= ((NI) 8);
			nimln_(276, "gc.nim");
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, enlarge_1rn449bBULy9cLwCWr7ISAqg)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t) {
	tySequence_xv3aaFd3JCw8NbmALHiezQ* n;
	NI T1_;
	NI TM_ZT9crccxweoChVXn9cHcxIXQ_13;
	tySequence_xv3aaFd3JCw8NbmALHiezQ* T10_;
	nimfr_("enlarge", "strtabs.nim");
	n = (tySequence_xv3aaFd3JCw8NbmALHiezQ*)0;
	nimln_(141, "strtabs.nim");
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	TM_ZT9crccxweoChVXn9cHcxIXQ_13 = mulInt(T1_, ((NI) 2));
	n = (tySequence_xv3aaFd3JCw8NbmALHiezQ*) newSeq((&NTI_xv3aaFd3JCw8NbmALHiezQ_), ((NI)chckRange((NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_13), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i;
		NI colontmp_;
		NI T3_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(142, "strtabs.nim");
		T3_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
		colontmp_ = T3_;
		nimln_(2010, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2011, "system.nim");
			while (1) {
				NI TM_ZT9crccxweoChVXn9cHcxIXQ_14;
				if (!(res <= colontmp_)) goto LA5;
				nimln_(2012, "system.nim");
				i = res;
				nimln_(143, "strtabs.nim");
				{
					if (!(*t).data || (NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					if (!(*t).data->data[i].Field2) goto LA8_;
					if (!(*t).data || (NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					if (!(*t).data || (NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					rawInsert_HXPVLnHem3T2vyDx7gHMBQ(t, (&n), (*t).data->data[i].Field0, (*t).data->data[i].Field1);
				}
				LA8_: ;
				nimln_(2013, "system.nim");
				TM_ZT9crccxweoChVXn9cHcxIXQ_14 = addInt(res, ((NI) 1));
				res = (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_14);
			} LA5: ;
		}
	}
	nimln_(144, "strtabs.nim");
	T10_ = (tySequence_xv3aaFd3JCw8NbmALHiezQ*)0;
	T10_ = (*t).data;
	asgnRefNoCycle((void**) (&(*t).data), n);
	n = T10_;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, nstPut)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key, NimStringDesc* val) {
	NI index;
	nimfr_("[]=", "strtabs.nim");
	nimln_(148, "strtabs.nim");
	index = rawGet_g4UMXDeIi4hi42WuIY9cM4A(t, key);
	nimln_(149, "strtabs.nim");
	{
		NimStringDesc* T5_;
		if (!(((NI) 0) <= index)) goto LA3_;
		if (!(*t).data || (NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		nimln_(150, "strtabs.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = (*t).data->data[index].Field1; (*t).data->data[index].Field1 = copyStringRC1(val);
		if (T5_) nimGCunrefNoCycle(T5_);
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_ZT9crccxweoChVXn9cHcxIXQ_15;
		nimln_(152, "strtabs.nim");
		{
			NI T9_;
			NIM_BOOL T10_;
			T9_ = ((*t).data ? (*t).data->Sup.len : 0);
			T10_ = (NIM_BOOL)0;
			T10_ = mustRehash_K02IbeDTRFZ9b4m0M4Kahlg(T9_, (*t).counter);
			if (!T10_) goto LA11_;
			enlarge_1rn449bBULy9cLwCWr7ISAqg(t);
		}
		LA11_: ;
		nimln_(153, "strtabs.nim");
		rawInsert_HXPVLnHem3T2vyDx7gHMBQ(t, (&(*t).data), key, val);
		nimln_(154, "strtabs.nim");
		TM_ZT9crccxweoChVXn9cHcxIXQ_15 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_15);
	}
	LA1_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*, nstnewStringTableWithTableConstr)(tyTuple_UV3llMMYFckfui8YMBuUZA* keyValuePairs, NI keyValuePairsLen_0, tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode) {
	tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* result;
	nimfr_("newStringTable", "strtabs.nim");
	result = (tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*)0;
	nimln_(211, "strtabs.nim");
	result = nstnewStringTable(mode);
	{
		NimStringDesc* key;
		NimStringDesc* val;
		NI i;
		key = (NimStringDesc*)0;
		val = (NimStringDesc*)0;
		nimln_(2163, "system.nim");
		i = ((NI) 0);
		{
			nimln_(2164, "system.nim");
			while (1) {
				NI TM_ZT9crccxweoChVXn9cHcxIXQ_16;
				if (!(i < keyValuePairsLen_0)) goto LA3;
				nimln_(2165, "system.nim");
				if ((NU)(i) >= (NU)(keyValuePairsLen_0)) raiseIndexError();
				key = keyValuePairs[i].Field0;
				if ((NU)(i) >= (NU)(keyValuePairsLen_0)) raiseIndexError();
				val = keyValuePairs[i].Field1;
				nimln_(212, "strtabs.nim");
				nstPut(result, key, val);
				nimln_(2166, "system.nim");
				TM_ZT9crccxweoChVXn9cHcxIXQ_16 = addInt(i, ((NI) 1));
				i = (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_16);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getOrDefault_sPC3Tb9bX9b1TxdHlL7x9cN3Q)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key, NimStringDesc* default_0) {
	NimStringDesc* result;
	NI index;
	nimfr_("getOrDefault", "strtabs.nim");
	result = (NimStringDesc*)0;
	nimln_(119, "strtabs.nim");
	index = rawGet_g4UMXDeIi4hi42WuIY9cM4A(t, key);
	nimln_(120, "strtabs.nim");
	{
		if (!(((NI) 0) <= index)) goto LA3_;
		if (!(*t).data || (NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		result = copyString((*t).data->data[index].Field1);
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(121, "strtabs.nim");
		result = copyString(default_0);
	}
	LA1_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_strtabsInit000)(void) {
	nimfr_("strtabs", "strtabs.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_strtabsDatInit000)(void) {
static TNimNode* TM_ZT9crccxweoChVXn9cHcxIXQ_2[3];
static TNimNode* TM_ZT9crccxweoChVXn9cHcxIXQ_3[3];
static TNimNode* TM_ZT9crccxweoChVXn9cHcxIXQ_4[3];
NI TM_ZT9crccxweoChVXn9cHcxIXQ_6;
static char* NIM_CONST TM_ZT9crccxweoChVXn9cHcxIXQ_5[3] = {
"modeCaseSensitive", 
"modeCaseInsensitive", 
"modeStyleInsensitive"};
static TNimNode TM_ZT9crccxweoChVXn9cHcxIXQ_0[12];
NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_.size = sizeof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw);
NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_.kind = 17;
NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_ZT9crccxweoChVXn9cHcxIXQ_2[0] = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[1];
TM_ZT9crccxweoChVXn9cHcxIXQ_0[1].kind = 1;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[1].offset = offsetof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw, counter);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[1].name = "counter";
TM_ZT9crccxweoChVXn9cHcxIXQ_2[1] = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[2];
NTI_sPaDkVPSC0MkcoXCxPH9ccA_.size = sizeof(tyTuple_sPaDkVPSC0MkcoXCxPH9ccA);
NTI_sPaDkVPSC0MkcoXCxPH9ccA_.kind = 18;
NTI_sPaDkVPSC0MkcoXCxPH9ccA_.base = 0;
NTI_sPaDkVPSC0MkcoXCxPH9ccA_.flags = 2;
TM_ZT9crccxweoChVXn9cHcxIXQ_3[0] = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[4];
TM_ZT9crccxweoChVXn9cHcxIXQ_0[4].kind = 1;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[4].offset = offsetof(tyTuple_sPaDkVPSC0MkcoXCxPH9ccA, Field0);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[4].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[4].name = "Field0";
TM_ZT9crccxweoChVXn9cHcxIXQ_3[1] = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[5];
TM_ZT9crccxweoChVXn9cHcxIXQ_0[5].kind = 1;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[5].offset = offsetof(tyTuple_sPaDkVPSC0MkcoXCxPH9ccA, Field1);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[5].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[5].name = "Field1";
TM_ZT9crccxweoChVXn9cHcxIXQ_3[2] = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[6];
TM_ZT9crccxweoChVXn9cHcxIXQ_0[6].kind = 1;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[6].offset = offsetof(tyTuple_sPaDkVPSC0MkcoXCxPH9ccA, Field2);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[6].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[6].name = "Field2";
TM_ZT9crccxweoChVXn9cHcxIXQ_0[3].len = 3; TM_ZT9crccxweoChVXn9cHcxIXQ_0[3].kind = 2; TM_ZT9crccxweoChVXn9cHcxIXQ_0[3].sons = &TM_ZT9crccxweoChVXn9cHcxIXQ_3[0];
NTI_sPaDkVPSC0MkcoXCxPH9ccA_.node = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[3];
NTI_xv3aaFd3JCw8NbmALHiezQ_.size = sizeof(tySequence_xv3aaFd3JCw8NbmALHiezQ*);
NTI_xv3aaFd3JCw8NbmALHiezQ_.kind = 24;
NTI_xv3aaFd3JCw8NbmALHiezQ_.base = (&NTI_sPaDkVPSC0MkcoXCxPH9ccA_);
NTI_xv3aaFd3JCw8NbmALHiezQ_.flags = 2;
NTI_xv3aaFd3JCw8NbmALHiezQ_.marker = Marker_tySequence_xv3aaFd3JCw8NbmALHiezQ;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[2].kind = 1;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[2].offset = offsetof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw, data);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[2].typ = (&NTI_xv3aaFd3JCw8NbmALHiezQ_);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[2].name = "data";
TM_ZT9crccxweoChVXn9cHcxIXQ_2[2] = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[7];
NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_.size = sizeof(tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ);
NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_.kind = 14;
NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_.base = 0;
NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_.flags = 3;
for (TM_ZT9crccxweoChVXn9cHcxIXQ_6 = 0; TM_ZT9crccxweoChVXn9cHcxIXQ_6 < 3; TM_ZT9crccxweoChVXn9cHcxIXQ_6++) {
TM_ZT9crccxweoChVXn9cHcxIXQ_0[TM_ZT9crccxweoChVXn9cHcxIXQ_6+8].kind = 1;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[TM_ZT9crccxweoChVXn9cHcxIXQ_6+8].offset = TM_ZT9crccxweoChVXn9cHcxIXQ_6;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[TM_ZT9crccxweoChVXn9cHcxIXQ_6+8].name = TM_ZT9crccxweoChVXn9cHcxIXQ_5[TM_ZT9crccxweoChVXn9cHcxIXQ_6];
TM_ZT9crccxweoChVXn9cHcxIXQ_4[TM_ZT9crccxweoChVXn9cHcxIXQ_6] = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[TM_ZT9crccxweoChVXn9cHcxIXQ_6+8];
}
TM_ZT9crccxweoChVXn9cHcxIXQ_0[11].len = 3; TM_ZT9crccxweoChVXn9cHcxIXQ_0[11].kind = 2; TM_ZT9crccxweoChVXn9cHcxIXQ_0[11].sons = &TM_ZT9crccxweoChVXn9cHcxIXQ_4[0];
NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_.node = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[11];
TM_ZT9crccxweoChVXn9cHcxIXQ_0[7].kind = 1;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[7].offset = offsetof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw, mode);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[7].typ = (&NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[7].name = "mode";
TM_ZT9crccxweoChVXn9cHcxIXQ_0[0].len = 3; TM_ZT9crccxweoChVXn9cHcxIXQ_0[0].kind = 2; TM_ZT9crccxweoChVXn9cHcxIXQ_0[0].sons = &TM_ZT9crccxweoChVXn9cHcxIXQ_2[0];
NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_.node = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[0];
NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_.size = sizeof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*);
NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_.kind = 22;
NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_.base = (&NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_);
NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_.marker = Marker_tyRef_pkhT5bYRU9ayIZ9cBuuCx4Xw;
}

