/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/benji/.nim/lib -o /home/benji/dev/nim/website/src/nimcache/stdlib_nativesockets.c.o /home/benji/dev/nim/website/src/nimcache/stdlib_nativesockets.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/socket.h>
#include <netdb.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyTuple_TpwiSlpJ9ammzps6Ja8XpjQ tyTuple_TpwiSlpJ9ammzps6Ja8XpjQ;
typedef NU8 tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg;
typedef NU8 tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_TpwiSlpJ9ammzps6Ja8XpjQ {
int Field0;
NimStringDesc* Field1;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 tyArray_cdsir9aPB24hAk6k77P9b9bCA[8];
typedef NIM_CHAR tyArray_NSMq3FMCIrS8gSbyinBZ8w[14];
N_LIB_PRIVATE N_NIMCALL(short, toInt_OxnVJkB3zYuSbbBvLQDSVA)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(int, toInt_8FqW9bXNjjJADB8XlKnpNLg)(tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw typ);
N_LIB_PRIVATE N_NIMCALL(int, toInt_9cDpnbeIxivYaLcJBJkQ2nQ)(tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg p);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError_bEwAamo1N7TKcaU9akpiyIg)(NI32 errorCode, NimStringDesc* additionalInfo);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError_tNPXXFl9cb3BG0pJKzUn9bew)(void);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__rzAI8EMyNBAQwGODeohhAA)(NU64 x);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
int osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w;
sa_family_t nativeAfInet_rQwsjQjVqXvdaL9aZofzWwg;
sa_family_t nativeAfInet6_Da6PongZL9aJxBrf7qeBmfA;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_Q79bEtFARvq0ekDNtvj3Vqg_;
TNimType NTI_NQT1bItGG2X9byGdrWX7ujw_;
TNimType NTI_dqJ1OqRGclxIMMdSLRzzXg_;
TNimType NTI_TpwiSlpJ9ammzps6Ja8XpjQ_;
extern TNimType NTI_nlCscttRCss70IBTyuBqnA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_11, "", 0);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(short, toInt_OxnVJkB3zYuSbbBvLQDSVA)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain) {
	short result;
	nimfr_("toInt", "nativesockets.nim");
	result = (short)0;
	nimln_(126, "nativesockets.nim");
	switch (domain) {
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 0):
	{
		nimln_(127, "nativesockets.nim");
		result = ((short) 0);
	}
	break;
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 1):
	{
		nimln_(128, "nativesockets.nim");
		result = ((short) 1);
	}
	break;
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2):
	{
		nimln_(129, "nativesockets.nim");
		result = ((short) 2);
	}
	break;
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23):
	{
		nimln_(130, "nativesockets.nim");
		result = ((short) 10);
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, toInt_8FqW9bXNjjJADB8XlKnpNLg)(tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw typ) {
	int result;
	nimfr_("toInt", "nativesockets.nim");
	result = (int)0;
	nimln_(142, "nativesockets.nim");
	switch (typ) {
	case ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 1):
	{
		nimln_(143, "nativesockets.nim");
		result = ((int) 1);
	}
	break;
	case ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 2):
	{
		nimln_(144, "nativesockets.nim");
		result = ((int) 2);
	}
	break;
	case ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 5):
	{
		nimln_(145, "nativesockets.nim");
		result = ((int) 5);
	}
	break;
	case ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 3):
	{
		nimln_(146, "nativesockets.nim");
		result = ((int) 3);
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, toInt_9cDpnbeIxivYaLcJBJkQ2nQ)(tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg p) {
	int result;
	nimfr_("toInt", "nativesockets.nim");
	result = (int)0;
	nimln_(149, "nativesockets.nim");
	switch (p) {
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 6):
	{
		nimln_(150, "nativesockets.nim");
		result = ((int) 6);
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 17):
	{
		nimln_(151, "nativesockets.nim");
		result = ((int) 17);
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 18):
	{
		nimln_(152, "nativesockets.nim");
		result = ((int) 0);
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 19):
	{
		nimln_(153, "nativesockets.nim");
		result = ((int) 41);
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 20):
	{
		nimln_(154, "nativesockets.nim");
		result = ((int) 255);
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 21):
	{
		nimln_(155, "nativesockets.nim");
		result = ((int) 1);
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, createNativeSocket_BcG9aGQhTam9ajUKte8LeMdQ)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol) {
	int result;
	short T1_;
	int T2_;
	int T3_;
	nimfr_("createNativeSocket", "nativesockets.nim");
	result = (int)0;
	nimln_(187, "nativesockets.nim");
	nimln_(188, "nativesockets.nim");
	T1_ = (short)0;
	T1_ = toInt_OxnVJkB3zYuSbbBvLQDSVA(domain);
	T2_ = (int)0;
	T2_ = toInt_8FqW9bXNjjJADB8XlKnpNLg(sockType);
	T3_ = (int)0;
	T3_ = toInt_9cDpnbeIxivYaLcJBJkQ2nQ(protocol);
	result = socket(((int) (T1_)), T2_, T3_);
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, setSockOptInt_AD4OLBf5FHlJkAgq7B9aY5A)(int socket, NI level, NI optname, NI optval) {
	int value;
	nimfr_("setSockOptInt", "nativesockets.nim");
	nimln_(591, "nativesockets.nim");
	value = ((int)chckRange(optval, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(592, "nativesockets.nim");
	{
		int T3_;
		NI32 T6_;
		nimln_(593, "nativesockets.nim");
		nimln_(592, "nativesockets.nim");
		T3_ = (int)0;
		T3_ = setsockopt(socket, ((int)chckRange(level, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(optname, ((int) (-2147483647 -1)), ((int) 2147483647))), ((void*) ((&value))), ((socklen_t) 4));
		if (!(T3_ < ((NI32) 0))) goto LA4_;
		nimln_(594, "nativesockets.nim");
		T6_ = (NI32)0;
		T6_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_11));
	}
	LA4_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NU16, ntohs_hTWZ9cGeQnQNEThS6k8qUKg)(NU16 x) {
	NU16 result;
	nimfr_("ntohs", "nativesockets.nim");
	result = (NU16)0;
	nimln_(291, "nativesockets.nim");
	result = (NU16)((NU16)((NU16)(x) >> (NU16)(((NU16) 8))) | (NU16)((NU16)(x) << (NU16)(((NU16) 8))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NU32, ntohl_RStKcIp64i7w9c4KBI2z46w)(NU32 x) {
	NU32 result;
	nimfr_("ntohl", "nativesockets.nim");
	result = (NU32)0;
	nimln_(274, "nativesockets.nim");
	nimln_(273, "nativesockets.nim");
	nimln_(272, "nativesockets.nim");
	nimln_(273, "nativesockets.nim");
	nimln_(274, "nativesockets.nim");
	nimln_(275, "nativesockets.nim");
	result = (NU32)((NU32)((NU32)((NU32)((NU32)(x) >> (NU32)(((NU32) 24))) | (NU32)((NU32)((NU32)(x) >> (NU32)(((NU32) 8))) & ((NU32) 65280))) | (NU32)((NU32)((NU32)(x) << (NU32)(((NU32) 8))) & ((NU32) 16711680))) | (NU32)((NU32)(x) << (NU32)(((NU32) 24))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, bindAddr_zpvqU0KQkzbkoKaehnMX2A)(int socket, struct sockaddr* name, socklen_t namelen) {
	int result;
	nimfr_("bindAddr", "nativesockets.nim");
	result = (int)0;
	nimln_(228, "nativesockets.nim");
	result = bind(socket, name, namelen);
	popFrame();
	return result;
}

static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}

static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem(p, ((int) 0), size);
}

static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == NIM_NIL);
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(struct addrinfo*, getAddrInfo_fNPnGAYqSzdc2OjHEcTTAw)(NimStringDesc* address, NU16 port, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol) {
	struct addrinfo* result;
	struct addrinfo hints;
	short T1_;
	int gaiResult;
	NimStringDesc* T6_;
	nimfr_("getAddrInfo", "nativesockets.nim");
	result = (struct addrinfo*)0;
	nimZeroMem((void*)(&hints), sizeof(struct addrinfo));
	nimln_(246, "nativesockets.nim");
	result = NIM_NIL;
	nimln_(247, "nativesockets.nim");
	T1_ = (short)0;
	T1_ = toInt_OxnVJkB3zYuSbbBvLQDSVA(domain);
	hints.ai_family = ((int) (T1_));
	nimln_(248, "nativesockets.nim");
	hints.ai_socktype = toInt_8FqW9bXNjjJADB8XlKnpNLg(sockType);
	nimln_(249, "nativesockets.nim");
	hints.ai_protocol = toInt_9cDpnbeIxivYaLcJBJkQ2nQ(protocol);
	nimln_(254, "nativesockets.nim");
	{
		if (!(domain == ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23))) goto LA4_;
		nimln_(255, "nativesockets.nim");
		hints.ai_flags = ((int) 8);
	}
	LA4_: ;
	nimln_(256, "nativesockets.nim");
	T6_ = (NimStringDesc*)0;
	T6_ = dollar__rzAI8EMyNBAQwGODeohhAA(port);
	gaiResult = getaddrinfo(nimToCStringConv(address), nimToCStringConv(T6_), (&hints), &result);
	nimln_(257, "nativesockets.nim");
	{
		NI32 T11_;
		NCSTRING T12_;
		NimStringDesc* T13_;
		nimln_(396, "system.nim");
		if (!!((gaiResult == ((NI32) 0)))) goto LA9_;
		nimln_(261, "nativesockets.nim");
		T11_ = (NI32)0;
		T11_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		T12_ = (NCSTRING)0;
		T12_ = (char *)gai_strerror(gaiResult);
		T13_ = (NimStringDesc*)0;
		T13_ = cstrToNimstr(T12_);
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T11_, T13_);
	}
	LA9_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, listen_BNAD35QpM7R1C7EJRtAZ3Q)(int socket, int backlog) {
	int result;
	nimfr_("listen", "nativesockets.nim");
	result = (int)0;
	nimln_(237, "nativesockets.nim");
	result = listen(socket, backlog);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, setBlocking_RBApwF6paZ4dy39bsxU85TA)(int s, NIM_BOOL blocking) {
	NI x;
	int T1_;
	nimfr_("setBlocking", "nativesockets.nim");
	nimln_(605, "nativesockets.nim");
	T1_ = (int)0;
	T1_ = fcntl(s, ((int) 3), ((NI) 0));
	x = ((NI) (T1_));
	nimln_(606, "nativesockets.nim");
	{
		NI32 T6_;
		if (!(x == ((NI) -1))) goto LA4_;
		nimln_(607, "nativesockets.nim");
		T6_ = (NI32)0;
		T6_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_11));
	}
	goto LA2_;
	LA4_: ;
	{
		NI mode;
		nimln_(609, "nativesockets.nim");
		{
			if (!blocking) goto LA10_;
			mode = (NI)(x & ((NI) -2049));
		}
		goto LA8_;
		LA10_: ;
		{
			mode = (NI)(x | ((NI) 2048));
		}
		LA8_: ;
		nimln_(610, "nativesockets.nim");
		{
			int T15_;
			NI32 T18_;
			T15_ = (int)0;
			T15_ = fcntl(s, ((int) 4), mode);
			if (!(T15_ == ((NI32) -1))) goto LA16_;
			nimln_(611, "nativesockets.nim");
			T18_ = (NI32)0;
			T18_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T18_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_11));
		}
		LA16_: ;
	}
	LA2_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, close_ODRNWwddsp7NVetdw9cXCVg)(int socket) {
	int T1_;
	nimfr_("close", "nativesockets.nim");
	nimln_(223, "nativesockets.nim");
	T1_ = (int)0;
	T1_ = close(socket);
	T1_;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, accept_nmCCLPlzBoP6AGJgbJepfQ)(int fd, tyTuple_TpwiSlpJ9ammzps6Ja8XpjQ* Result) {
	struct sockaddr_in sockAddress;
	socklen_t addrLen;
	int sock;
	nimfr_("accept", "nativesockets.nim");
{	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_TpwiSlpJ9ammzps6Ja8XpjQ_));
	nimZeroMem((void*)(&sockAddress), sizeof(struct sockaddr_in));
	nimln_(711, "nativesockets.nim");
	addrLen = ((socklen_t) (((NI)sizeof(struct sockaddr_in))));
	nimln_(712, "nativesockets.nim");
	sock = accept(fd, ((struct sockaddr*) ((&sockAddress))), (&addrLen));
	nimln_(714, "nativesockets.nim");
	{
		if (!(sock == osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w)) goto LA3_;
		nimln_(715, "nativesockets.nim");
		(*Result).Field0 = osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w;
		unsureAsgnRef((void**) (&(*Result).Field1), copyString(((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_11)));
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		NCSTRING T6_;
		nimln_(717, "nativesockets.nim");
		(*Result).Field0 = sock;
		T6_ = (NCSTRING)0;
		T6_ = inet_ntoa(sockAddress.sin_addr);
		unsureAsgnRef((void**) (&(*Result).Field1), cstrToNimstr(T6_));
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_nativesocketsInit000)(void) {
	nimfr_("nativesockets", "nativesockets.nim");
	nimln_(105, "nativesockets.nim");
	osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w = ((int) -1);
	nimln_(106, "nativesockets.nim");
	nativeAfInet_rQwsjQjVqXvdaL9aZofzWwg = ((sa_family_t) 2);
	nimln_(107, "nativesockets.nim");
	nativeAfInet6_Da6PongZL9aJxBrf7qeBmfA = ((sa_family_t) 10);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_nativesocketsDatInit000)(void) {
static TNimNode* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_2[4];
NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4;
static char* NIM_CONST TM_f9bP3LqjpgpB9cXL8Nnak7tQ_3[4] = {
"AF_UNSPEC", 
"AF_UNIX", 
"AF_INET", 
"AF_INET6"};
static TNimNode* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_5[4];
NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7;
static char* NIM_CONST TM_f9bP3LqjpgpB9cXL8Nnak7tQ_6[4] = {
"SOCK_STREAM", 
"SOCK_DGRAM", 
"SOCK_RAW", 
"SOCK_SEQPACKET"};
static TNimNode* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8[6];
NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10;
static char* NIM_CONST TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9[6] = {
"IPPROTO_TCP", 
"IPPROTO_UDP", 
"IPPROTO_IP", 
"IPPROTO_IPV6", 
"IPPROTO_RAW", 
"IPPROTO_ICMP"};
static TNimNode* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_12[2];
static TNimNode TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[20];
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.size = sizeof(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg);
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.kind = 14;
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.base = 0;
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.flags = 3;
for (TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4 = 0; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4 < 4; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4++) {
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4+0].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4+0].offset = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4+0].name = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_3[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_2[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4+0];
}
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[0].offset = 0;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[1].offset = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[2].offset = 2;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[3].offset = 23;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4].len = 4; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4].kind = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4].sons = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_2[0];
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.node = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4];
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.flags = 1<<2;
NTI_NQT1bItGG2X9byGdrWX7ujw_.size = sizeof(tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw);
NTI_NQT1bItGG2X9byGdrWX7ujw_.kind = 14;
NTI_NQT1bItGG2X9byGdrWX7ujw_.base = 0;
NTI_NQT1bItGG2X9byGdrWX7ujw_.flags = 3;
for (TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7 = 0; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7 < 4; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7++) {
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7+5].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7+5].offset = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7+5].name = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_6[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_5[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7+5];
}
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[5].offset = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[6].offset = 2;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[7].offset = 3;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[8].offset = 5;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[9].len = 4; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[9].kind = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[9].sons = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_5[0];
NTI_NQT1bItGG2X9byGdrWX7ujw_.node = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[9];
NTI_NQT1bItGG2X9byGdrWX7ujw_.flags = 1<<2;
NTI_dqJ1OqRGclxIMMdSLRzzXg_.size = sizeof(tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg);
NTI_dqJ1OqRGclxIMMdSLRzzXg_.kind = 14;
NTI_dqJ1OqRGclxIMMdSLRzzXg_.base = 0;
NTI_dqJ1OqRGclxIMMdSLRzzXg_.flags = 3;
for (TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10 = 0; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10 < 6; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10++) {
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10+10].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10+10].offset = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10+10].name = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10+10];
}
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[10].offset = 6;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[11].offset = 17;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[12].offset = 18;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[13].offset = 19;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[14].offset = 20;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[15].offset = 21;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16].len = 6; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16].kind = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16].sons = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8[0];
NTI_dqJ1OqRGclxIMMdSLRzzXg_.node = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16];
NTI_dqJ1OqRGclxIMMdSLRzzXg_.flags = 1<<2;
NTI_TpwiSlpJ9ammzps6Ja8XpjQ_.size = sizeof(tyTuple_TpwiSlpJ9ammzps6Ja8XpjQ);
NTI_TpwiSlpJ9ammzps6Ja8XpjQ_.kind = 18;
NTI_TpwiSlpJ9ammzps6Ja8XpjQ_.base = 0;
NTI_TpwiSlpJ9ammzps6Ja8XpjQ_.flags = 2;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_12[0] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[18];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[18].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[18].offset = offsetof(tyTuple_TpwiSlpJ9ammzps6Ja8XpjQ, Field0);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[18].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[18].name = "Field0";
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_12[1] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[19];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[19].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[19].offset = offsetof(tyTuple_TpwiSlpJ9ammzps6Ja8XpjQ, Field1);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[19].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[19].name = "Field1";
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[17].len = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[17].kind = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[17].sons = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_12[0];
NTI_TpwiSlpJ9ammzps6Ja8XpjQ_.node = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[17];
}

