/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/benji/.nim/lib -o /home/benji/dev/nim/website/src/nimcache/stdlib_options.c.o /home/benji/dev/nim/website/src/nimcache/stdlib_options.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_Option_aZ6xLgAfL0iDb1X0bji3cQ tyObject_Option_aZ6xLgAfL0iDb1X0bji3cQ;
typedef struct tyObject_Table_Ji6x6JQ0gVMaFr8AIk18Ug tyObject_Table_Ji6x6JQ0gVMaFr8AIk18Ug;
typedef struct tySequence_SFipDZIkFtPcrLs0AGBBjQ tySequence_SFipDZIkFtPcrLs0AGBBjQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ;
typedef struct tySequence_4eQHGndY6XBYpFOH09apV8Q tySequence_4eQHGndY6XBYpFOH09apV8Q;
typedef struct tyObject_Option_veolIg1VCBBP47eu1cVRKw tyObject_Option_veolIg1VCBBP47eu1cVRKw;
typedef struct tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_Option_vK1KzfYf1DGLiUIpLm9cS0A tyObject_Option_vK1KzfYf1DGLiUIpLm9cS0A;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
typedef struct tyObject_Option_b3qcYYMISNgGVYTnldWqsA tyObject_Option_b3qcYYMISNgGVYTnldWqsA;
typedef struct tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA;
typedef struct tyTuple_8ZxhPt1NwfElsJs8zUSV9bg tyTuple_8ZxhPt1NwfElsJs8zUSV9bg;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
struct tyObject_Table_Ji6x6JQ0gVMaFr8AIk18Ug {
tySequence_SFipDZIkFtPcrLs0AGBBjQ* data;
NI counter;
};
struct tyObject_Option_aZ6xLgAfL0iDb1X0bji3cQ {
tyObject_Table_Ji6x6JQ0gVMaFr8AIk18Ug val;
NIM_BOOL has;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ {
tySequence_4eQHGndY6XBYpFOH09apV8Q* val;
NIM_BOOL has;
};
typedef NU8 tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA;
struct tyObject_Option_veolIg1VCBBP47eu1cVRKw {
tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA val;
NIM_BOOL has;
};
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
NU raise_id;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
struct tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g {
  tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA Sup;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_Option_vK1KzfYf1DGLiUIpLm9cS0A {
NimStringDesc* val;
NIM_BOOL has;
};
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct tyObject_Option_b3qcYYMISNgGVYTnldWqsA {
tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* val;
};
struct tyTuple_8ZxhPt1NwfElsJs8zUSV9bg {
NI Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence_4eQHGndY6XBYpFOH09apV8Q {
  TGenericSeq Sup;
  tyTuple_UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE];
};
struct tySequence_SFipDZIkFtPcrLs0AGBBjQ {
  TGenericSeq Sup;
  tyTuple_8ZxhPt1NwfElsJs8zUSV9bg data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, isNone_mXASObalAZ49cPCDV5Ve2swoptions)(tyObject_Option_veolIg1VCBBP47eu1cVRKw self);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_E31uzfKZFyNg6dDBfxT70Q)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL, isSome_MWswSRVlTY5VlBbr79bciVwoptions)(tyObject_Option_vK1KzfYf1DGLiUIpLm9cS0A self);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(NIM_BOOL, isNone_c78H79abraj8cJjna9azWoIgmain)(tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ self);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(NIM_BOOL, isNone_o8E55AD4FrHjGtktLKFLQwparser)(tyObject_Option_b3qcYYMISNgGVYTnldWqsA self);
static N_INLINE(NIM_BOOL, isSome_c78H79abraj8cJjna9azWoIgoptions)(tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ self);
N_LIB_PRIVATE N_NIMCALL(void, none_z9c1eMXDkQ2GS4AXUSa9bt9aQ)(tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ* Result);
N_LIB_PRIVATE N_NIMCALL(void, none_E1s5w9aJnBUa4GIqkrycudQ)(tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ* Result);
TNimType NTI_aZ6xLgAfL0iDb1X0bji3cQ_;
extern TNimType NTI_Ji6x6JQ0gVMaFr8AIk18Ug_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_6yaJiiZDak2uE9c2u3J9cmPQ_;
extern TNimType NTI_4eQHGndY6XBYpFOH09apV8Q_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
TNimType NTI_bf8oYOS2OmekHPekjQ7N3g_;
TNimType NTI_E31uzfKZFyNg6dDBfxT70Q_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_vK1KzfYf1DGLiUIpLm9cS0A_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_b3qcYYMISNgGVYTnldWqsA_;
extern TNimType NTI_FbZeO4trJhT2CCJ9aLxejqw_;
STRING_LITERAL(TM_4DNs4bMUkswhWc4o4dM9bbg_4, "Can\'t obtain a value from a `none`", 34);
STRING_LITERAL(TM_4DNs4bMUkswhWc4o4dM9bbg_6, "\012not (val == nil) ", 18);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NIM_BOOL, isNone_mXASObalAZ49cPCDV5Ve2swoptions)(tyObject_Option_veolIg1VCBBP47eu1cVRKw self) {
	NIM_BOOL result;
	nimfr_("isNone", "options.nim");
	result = (NIM_BOOL)0;
	nimln_(121, "options.nim");
	result = !(self.has);
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_E31uzfKZFyNg6dDBfxT70Q)(void* p, NI op) {
	tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g* a;
	a = (tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g*)p;
	nimGCvisit((void*)(*a).Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.up, op);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		nimln_(185, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln_(252, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA, get_uuzg8gUexifnLFZRyocA5w)(tyObject_Option_veolIg1VCBBP47eu1cVRKw self) {
	tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA result;
	nimfr_("get", "options.nim");
	result = (tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA)0;
	nimln_(129, "options.nim");
	nimln_(131, "options.nim");
	{
		NIM_BOOL T3_;
		tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g* T6_;
		NimStringDesc* T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = isNone_mXASObalAZ49cPCDV5Ve2swoptions(self);
		if (!T3_) goto LA4_;
		T6_ = (tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g*)0;
		T6_ = (tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g*) newObj((&NTI_E31uzfKZFyNg6dDBfxT70Q_), sizeof(tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g));
		(*T6_).Sup.Sup.Sup.m_type = (&NTI_bf8oYOS2OmekHPekjQ7N3g_);
		T7_ = (NimStringDesc*)0;
		T7_ = (*T6_).Sup.Sup.message; (*T6_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM_4DNs4bMUkswhWc4o4dM9bbg_4));
		if (T7_) nimGCunrefNoCycle(T7_);
		nimln_(132, "options.nim");
		raiseException((Exception*)T6_, "UnpackError:ObjectType");
	}
	LA4_: ;
	result = self.val;
	popFrame();
	return result;
}

static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}

static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem(p, ((int) 0), size);
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Option_veolIg1VCBBP47eu1cVRKw, some_d2G9cw9cT6OB5mDGDhM4sxKQ)(tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA val) {
	tyObject_Option_veolIg1VCBBP47eu1cVRKw result;
	nimfr_("some", "options.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_Option_veolIg1VCBBP47eu1cVRKw));
	nimln_(92, "options.nim");
	result.has = NIM_TRUE;
	nimln_(93, "options.nim");
	result.val = val;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Option_veolIg1VCBBP47eu1cVRKw, none_nl9abCnT3LoTjtAyW9cgbQ8Q)(void) {
	tyObject_Option_veolIg1VCBBP47eu1cVRKw result;
	nimfr_("none", "options.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_Option_veolIg1VCBBP47eu1cVRKw));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isSome_MWswSRVlTY5VlBbr79bciVwoptions)(tyObject_Option_vK1KzfYf1DGLiUIpLm9cS0A self) {
	NIM_BOOL result;
	nimfr_("isSome", "options.nim");
	result = (NIM_BOOL)0;
	nimln_(115, "options.nim");
	result = self.has;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, get_5oEMi7WPQGupN9bcpJno8Iw)(tyObject_Option_vK1KzfYf1DGLiUIpLm9cS0A self, NimStringDesc* otherwise) {
	NimStringDesc* result;
	nimfr_("get", "options.nim");
	result = (NimStringDesc*)0;
	nimln_(136, "options.nim");
	nimln_(137, "options.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isSome_MWswSRVlTY5VlBbr79bciVwoptions(self);
		if (!T3_) goto LA4_;
		result = copyString(self.val);
	}
	goto LA1_;
	LA4_: ;
	{
		result = copyString(otherwise);
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, some_FHoRgml9aRf9abaoT1n9bWIBw)(NimStringDesc* val, tyObject_Option_vK1KzfYf1DGLiUIpLm9cS0A* Result) {
	nimfr_("some", "options.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_vK1KzfYf1DGLiUIpLm9cS0A_));
	nimln_(92, "options.nim");
	(*Result).has = NIM_TRUE;
	nimln_(93, "options.nim");
	unsureAsgnRef((void**) (&(*Result).val), copyString(val));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, none_wA9cpF6h9ap0DrlooJGIDvpQ)(tyObject_Option_vK1KzfYf1DGLiUIpLm9cS0A* Result) {
	nimfr_("none", "options.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_vK1KzfYf1DGLiUIpLm9cS0A_));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, some_2lqcNt6JQWFNZfQaN14d6g)(tySequence_4eQHGndY6XBYpFOH09apV8Q* val, tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ* Result) {
	nimfr_("some", "options.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_6yaJiiZDak2uE9c2u3J9cmPQ_));
	nimln_(92, "options.nim");
	(*Result).has = NIM_TRUE;
	nimln_(93, "options.nim");
	genericSeqAssign((&(*Result).val), val, (&NTI_4eQHGndY6XBYpFOH09apV8Q_));
	popFrame();
}

static N_INLINE(NIM_BOOL, isNone_c78H79abraj8cJjna9azWoIgmain)(tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ self) {
	NIM_BOOL result;
	nimfr_("isNone", "options.nim");
	result = (NIM_BOOL)0;
	nimln_(121, "options.nim");
	result = !(self.has);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_4eQHGndY6XBYpFOH09apV8Q*, get_lDqKZotcOdDzt4Y0hBbo9aA)(tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ self) {
	tySequence_4eQHGndY6XBYpFOH09apV8Q* result;
	nimfr_("get", "options.nim");
	result = (tySequence_4eQHGndY6XBYpFOH09apV8Q*)0;
	nimln_(129, "options.nim");
	nimln_(131, "options.nim");
	{
		NIM_BOOL T3_;
		tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g* T6_;
		NimStringDesc* T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = isNone_c78H79abraj8cJjna9azWoIgmain(self);
		if (!T3_) goto LA4_;
		T6_ = (tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g*)0;
		T6_ = (tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g*) newObj((&NTI_E31uzfKZFyNg6dDBfxT70Q_), sizeof(tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g));
		(*T6_).Sup.Sup.Sup.m_type = (&NTI_bf8oYOS2OmekHPekjQ7N3g_);
		T7_ = (NimStringDesc*)0;
		T7_ = (*T6_).Sup.Sup.message; (*T6_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM_4DNs4bMUkswhWc4o4dM9bbg_4));
		if (T7_) nimGCunrefNoCycle(T7_);
		nimln_(132, "options.nim");
		raiseException((Exception*)T6_, "UnpackError:ObjectType");
	}
	LA4_: ;
	genericSeqAssign((&result), self.val, (&NTI_4eQHGndY6XBYpFOH09apV8Q_));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, some_qqLEHusgxfhtb06XnUh3TA)(tySequence_4eQHGndY6XBYpFOH09apV8Q* val, tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ* Result) {
	nimfr_("some", "options.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_6yaJiiZDak2uE9c2u3J9cmPQ_));
	nimln_(92, "options.nim");
	(*Result).has = NIM_TRUE;
	nimln_(93, "options.nim");
	genericSeqAssign((&(*Result).val), val, (&NTI_4eQHGndY6XBYpFOH09apV8Q_));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, some_yBwTCVjEvMMiOyY5DAKFew)(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* val, tyObject_Option_b3qcYYMISNgGVYTnldWqsA* Result) {
	nimfr_("some", "options.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_b3qcYYMISNgGVYTnldWqsA_));
	nimln_(89, "options.nim");
	{
		if (!!(!((val == NIM_NIL)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4DNs4bMUkswhWc4o4dM9bbg_6));
	}
	LA3_: ;
	nimln_(90, "options.nim");
	unsureAsgnRef((void**) (&(*Result).val), val);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, none_9cgaikw4mVJpxlh880oaOrg)(tyObject_Option_b3qcYYMISNgGVYTnldWqsA* Result) {
	nimfr_("none", "options.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_b3qcYYMISNgGVYTnldWqsA_));
	popFrame();
}

static N_INLINE(NIM_BOOL, isNone_o8E55AD4FrHjGtktLKFLQwparser)(tyObject_Option_b3qcYYMISNgGVYTnldWqsA self) {
	NIM_BOOL result;
	nimfr_("isNone", "options.nim");
	result = (NIM_BOOL)0;
	nimln_(119, "options.nim");
	result = (self.val == NIM_NIL);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA*, get_nFXXgu2OkDRFqGNpMbT9atw)(tyObject_Option_b3qcYYMISNgGVYTnldWqsA self) {
	tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* result;
	nimfr_("get", "options.nim");
	result = (tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA*)0;
	nimln_(129, "options.nim");
	nimln_(131, "options.nim");
	{
		NIM_BOOL T3_;
		tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g* T6_;
		NimStringDesc* T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = isNone_o8E55AD4FrHjGtktLKFLQwparser(self);
		if (!T3_) goto LA4_;
		T6_ = (tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g*)0;
		T6_ = (tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g*) newObj((&NTI_E31uzfKZFyNg6dDBfxT70Q_), sizeof(tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g));
		(*T6_).Sup.Sup.Sup.m_type = (&NTI_bf8oYOS2OmekHPekjQ7N3g_);
		T7_ = (NimStringDesc*)0;
		T7_ = (*T6_).Sup.Sup.message; (*T6_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM_4DNs4bMUkswhWc4o4dM9bbg_4));
		if (T7_) nimGCunrefNoCycle(T7_);
		nimln_(132, "options.nim");
		raiseException((Exception*)T6_, "UnpackError:ObjectType");
	}
	LA4_: ;
	result = self.val;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isSome_c78H79abraj8cJjna9azWoIgoptions)(tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ self) {
	NIM_BOOL result;
	nimfr_("isSome", "options.nim");
	result = (NIM_BOOL)0;
	nimln_(115, "options.nim");
	result = self.has;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_4eQHGndY6XBYpFOH09apV8Q*, get_dx4vnUIFtfW6NJ9atlQ9cOUQ)(tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ self, tySequence_4eQHGndY6XBYpFOH09apV8Q* otherwise) {
	tySequence_4eQHGndY6XBYpFOH09apV8Q* result;
	nimfr_("get", "options.nim");
	result = (tySequence_4eQHGndY6XBYpFOH09apV8Q*)0;
	nimln_(136, "options.nim");
	nimln_(137, "options.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isSome_c78H79abraj8cJjna9azWoIgoptions(self);
		if (!T3_) goto LA4_;
		genericSeqAssign((&result), self.val, (&NTI_4eQHGndY6XBYpFOH09apV8Q_));
	}
	goto LA1_;
	LA4_: ;
	{
		genericSeqAssign((&result), otherwise, (&NTI_4eQHGndY6XBYpFOH09apV8Q_));
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, none_z9c1eMXDkQ2GS4AXUSa9bt9aQ)(tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ* Result) {
	nimfr_("none", "options.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_6yaJiiZDak2uE9c2u3J9cmPQ_));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, none_0DysAzVoluISSrh3B4CvOg)(tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ* Result) {
	nimfr_("none", "options.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_6yaJiiZDak2uE9c2u3J9cmPQ_));
	nimln_(108, "options.nim");
	nimln_(109, "options.nim");
	none_z9c1eMXDkQ2GS4AXUSa9bt9aQ(Result);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, none_E1s5w9aJnBUa4GIqkrycudQ)(tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ* Result) {
	nimfr_("none", "options.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_6yaJiiZDak2uE9c2u3J9cmPQ_));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, none_pOltaPAafUwAfPIk7HoV4g)(tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ* Result) {
	nimfr_("none", "options.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_6yaJiiZDak2uE9c2u3J9cmPQ_));
	nimln_(108, "options.nim");
	nimln_(109, "options.nim");
	none_E1s5w9aJnBUa4GIqkrycudQ(Result);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_optionsInit000)(void) {
	nimfr_("options", "options.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_optionsDatInit000)(void) {
static TNimNode* TM_4DNs4bMUkswhWc4o4dM9bbg_2[2];
static TNimNode* TM_4DNs4bMUkswhWc4o4dM9bbg_3[2];
static TNimNode* TM_4DNs4bMUkswhWc4o4dM9bbg_5[2];
static TNimNode TM_4DNs4bMUkswhWc4o4dM9bbg_0[11];
NTI_aZ6xLgAfL0iDb1X0bji3cQ_.size = sizeof(tyObject_Option_aZ6xLgAfL0iDb1X0bji3cQ);
NTI_aZ6xLgAfL0iDb1X0bji3cQ_.kind = 18;
NTI_aZ6xLgAfL0iDb1X0bji3cQ_.base = 0;
NTI_aZ6xLgAfL0iDb1X0bji3cQ_.flags = 2;
TM_4DNs4bMUkswhWc4o4dM9bbg_2[0] = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[1];
TM_4DNs4bMUkswhWc4o4dM9bbg_0[1].kind = 1;
TM_4DNs4bMUkswhWc4o4dM9bbg_0[1].offset = offsetof(tyObject_Option_aZ6xLgAfL0iDb1X0bji3cQ, val);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[1].typ = (&NTI_Ji6x6JQ0gVMaFr8AIk18Ug_);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[1].name = "val";
TM_4DNs4bMUkswhWc4o4dM9bbg_2[1] = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[2];
TM_4DNs4bMUkswhWc4o4dM9bbg_0[2].kind = 1;
TM_4DNs4bMUkswhWc4o4dM9bbg_0[2].offset = offsetof(tyObject_Option_aZ6xLgAfL0iDb1X0bji3cQ, has);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[2].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[2].name = "has";
TM_4DNs4bMUkswhWc4o4dM9bbg_0[0].len = 2; TM_4DNs4bMUkswhWc4o4dM9bbg_0[0].kind = 2; TM_4DNs4bMUkswhWc4o4dM9bbg_0[0].sons = &TM_4DNs4bMUkswhWc4o4dM9bbg_2[0];
NTI_aZ6xLgAfL0iDb1X0bji3cQ_.node = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[0];
NTI_6yaJiiZDak2uE9c2u3J9cmPQ_.size = sizeof(tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ);
NTI_6yaJiiZDak2uE9c2u3J9cmPQ_.kind = 18;
NTI_6yaJiiZDak2uE9c2u3J9cmPQ_.base = 0;
NTI_6yaJiiZDak2uE9c2u3J9cmPQ_.flags = 2;
TM_4DNs4bMUkswhWc4o4dM9bbg_3[0] = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[4];
TM_4DNs4bMUkswhWc4o4dM9bbg_0[4].kind = 1;
TM_4DNs4bMUkswhWc4o4dM9bbg_0[4].offset = offsetof(tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ, val);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[4].typ = (&NTI_4eQHGndY6XBYpFOH09apV8Q_);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[4].name = "val";
TM_4DNs4bMUkswhWc4o4dM9bbg_3[1] = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[5];
TM_4DNs4bMUkswhWc4o4dM9bbg_0[5].kind = 1;
TM_4DNs4bMUkswhWc4o4dM9bbg_0[5].offset = offsetof(tyObject_Option_6yaJiiZDak2uE9c2u3J9cmPQ, has);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[5].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[5].name = "has";
TM_4DNs4bMUkswhWc4o4dM9bbg_0[3].len = 2; TM_4DNs4bMUkswhWc4o4dM9bbg_0[3].kind = 2; TM_4DNs4bMUkswhWc4o4dM9bbg_0[3].sons = &TM_4DNs4bMUkswhWc4o4dM9bbg_3[0];
NTI_6yaJiiZDak2uE9c2u3J9cmPQ_.node = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[3];
NTI_bf8oYOS2OmekHPekjQ7N3g_.size = sizeof(tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g);
NTI_bf8oYOS2OmekHPekjQ7N3g_.kind = 17;
NTI_bf8oYOS2OmekHPekjQ7N3g_.base = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[6].len = 0; TM_4DNs4bMUkswhWc4o4dM9bbg_0[6].kind = 2;
NTI_bf8oYOS2OmekHPekjQ7N3g_.node = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[6];
NTI_E31uzfKZFyNg6dDBfxT70Q_.size = sizeof(tyObject_UnpackErrorcolonObjectType__bf8oYOS2OmekHPekjQ7N3g*);
NTI_E31uzfKZFyNg6dDBfxT70Q_.kind = 22;
NTI_E31uzfKZFyNg6dDBfxT70Q_.base = (&NTI_bf8oYOS2OmekHPekjQ7N3g_);
NTI_E31uzfKZFyNg6dDBfxT70Q_.marker = Marker_tyRef_E31uzfKZFyNg6dDBfxT70Q;
NTI_vK1KzfYf1DGLiUIpLm9cS0A_.size = sizeof(tyObject_Option_vK1KzfYf1DGLiUIpLm9cS0A);
NTI_vK1KzfYf1DGLiUIpLm9cS0A_.kind = 18;
NTI_vK1KzfYf1DGLiUIpLm9cS0A_.base = 0;
NTI_vK1KzfYf1DGLiUIpLm9cS0A_.flags = 2;
TM_4DNs4bMUkswhWc4o4dM9bbg_5[0] = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[8];
TM_4DNs4bMUkswhWc4o4dM9bbg_0[8].kind = 1;
TM_4DNs4bMUkswhWc4o4dM9bbg_0[8].offset = offsetof(tyObject_Option_vK1KzfYf1DGLiUIpLm9cS0A, val);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[8].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[8].name = "val";
TM_4DNs4bMUkswhWc4o4dM9bbg_5[1] = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[9];
TM_4DNs4bMUkswhWc4o4dM9bbg_0[9].kind = 1;
TM_4DNs4bMUkswhWc4o4dM9bbg_0[9].offset = offsetof(tyObject_Option_vK1KzfYf1DGLiUIpLm9cS0A, has);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[9].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[9].name = "has";
TM_4DNs4bMUkswhWc4o4dM9bbg_0[7].len = 2; TM_4DNs4bMUkswhWc4o4dM9bbg_0[7].kind = 2; TM_4DNs4bMUkswhWc4o4dM9bbg_0[7].sons = &TM_4DNs4bMUkswhWc4o4dM9bbg_5[0];
NTI_vK1KzfYf1DGLiUIpLm9cS0A_.node = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[7];
NTI_b3qcYYMISNgGVYTnldWqsA_.size = sizeof(tyObject_Option_b3qcYYMISNgGVYTnldWqsA);
NTI_b3qcYYMISNgGVYTnldWqsA_.kind = 18;
NTI_b3qcYYMISNgGVYTnldWqsA_.base = 0;
NTI_b3qcYYMISNgGVYTnldWqsA_.flags = 2;
TM_4DNs4bMUkswhWc4o4dM9bbg_0[10].kind = 1;
TM_4DNs4bMUkswhWc4o4dM9bbg_0[10].offset = offsetof(tyObject_Option_b3qcYYMISNgGVYTnldWqsA, val);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[10].typ = (&NTI_FbZeO4trJhT2CCJ9aLxejqw_);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[10].name = "val";
NTI_b3qcYYMISNgGVYTnldWqsA_.node = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[10];
}

