/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/benji/.nim/lib -o /home/benji/dev/nim/website/src/nimcache/stdlib_asyncdispatch.c.o /home/benji/dev/nim/website/src/nimcache/stdlib_asyncdispatch.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg;
typedef struct RootObj RootObj;
typedef struct tySequence_M89cHurEB0l2lhCwhToV4tw tySequence_M89cHurEB0l2lhCwhToV4tw;
typedef struct tyObject_Deque_oL07LSXp3QMM0uEpFQiyQg tyObject_Deque_oL07LSXp3QMM0uEpFQiyQg;
typedef struct tySequence_WF89a8QyKeDCh4DYWTmSiBg tySequence_WF89a8QyKeDCh4DYWTmSiBg;
typedef struct tyTuple_V1aU9c9b1eMroa29cC237x0yQ tyTuple_V1aU9c9b1eMroa29cC237x0yQ;
typedef struct tyObject_FuturecolonObjectType__9cGbW9cUmV0peAwvBhoDzUzg tyObject_FuturecolonObjectType__9cGbW9cUmV0peAwvBhoDzUzg;
typedef struct tyObject_SelectorImpl_jkoZicTBtYdKkYck5SFJEQ tyObject_SelectorImpl_jkoZicTBtYdKkYck5SFJEQ;
typedef struct tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA;
typedef struct tySequence_lBAKjtL5n9bzoWNSpC1Vu3A tySequence_lBAKjtL5n9bzoWNSpC1Vu3A;
typedef struct tyTuple_2uzTbg8jwom7zHhmM2RgHg tyTuple_2uzTbg8jwom7zHhmM2RgHg;
typedef struct tyObject_Env_libslashpureslashasyncdispatchdotnim__sO5O0Qy9bzKs0atwA6HUBAw tyObject_Env_libslashpureslashasyncdispatchdotnim__sO5O0Qy9bzKs0atwA6HUBAw;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tySequence_5L9b5Ztm9adPEys1vE9cEPQJA tySequence_5L9b5Ztm9adPEys1vE9cEPQJA;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_ReadyKey_vOvPQEijZeFv1xAgbh5rNw tyObject_ReadyKey_vOvPQEijZeFv1xAgbh5rNw;
typedef struct tyObject_SelectorKey_561GPxg10TdJiEAAWoraPw tyObject_SelectorKey_561GPxg10TdJiEAAWoraPw;
typedef struct tyObject_IndexError_b0IIwghFQBADkB2c86kXQA tyObject_IndexError_b0IIwghFQBADkB2c86kXQA;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_Deque_oL07LSXp3QMM0uEpFQiyQg {
tySequence_WF89a8QyKeDCh4DYWTmSiBg* data;
NI head;
NI tail;
NI count;
NI mask;
};
struct tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg {
  RootObj Sup;
tySequence_M89cHurEB0l2lhCwhToV4tw* timers;
tyObject_Deque_oL07LSXp3QMM0uEpFQiyQg callbacks;
};
struct tyTuple_V1aU9c9b1eMroa29cC237x0yQ {
NF Field0;
tyObject_FuturecolonObjectType__9cGbW9cUmV0peAwvBhoDzUzg* Field1;
};
struct tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ {
  tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg Sup;
tyObject_SelectorImpl_jkoZicTBtYdKkYck5SFJEQ* selector;
};
struct tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA {
tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* readList;
tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* writeList;
};
struct tyTuple_2uzTbg8jwom7zHhmM2RgHg {
void* Field0;
tyObject_Env_libslashpureslashasyncdispatchdotnim__sO5O0Qy9bzKs0atwA6HUBAw* Field1;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (int fd, void* ClE_0);
void* ClE_0;
} tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyProc_IIomJ6ptE6vfJ5zRbATgkQ cbproc, void* ClE_0);
void* ClE_0;
} tyProc_Ig6kXMs9apW5862wHsbFhGw;
typedef N_CLOSURE_PTR(void, TM_gfe9a52b5gJr8GSrnr883iA_8) (tyProc_IIomJ6ptE6vfJ5zRbATgkQ cbproc, void* ClE_0);
typedef NU32 tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg;
struct tyObject_SelectorImpl_jkoZicTBtYdKkYck5SFJEQ {
int epollFD;
NI maxFD;
tySequence_5L9b5Ztm9adPEys1vE9cEPQJA* fds;
NI count;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
NU raise_id;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
struct tyObject_ReadyKey_vOvPQEijZeFv1xAgbh5rNw {
NI fd;
tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg events;
NI32 errorCode;
};
typedef tyObject_ReadyKey_vOvPQEijZeFv1xAgbh5rNw tyArray_ldWGqPJo6WgJz7q23H0LJQ[64];
typedef NU8 tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg;
struct tyObject_SelectorKey_561GPxg10TdJiEAAWoraPw {
NI ident;
tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg events;
NI param;
tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA data;
};
typedef N_CLOSURE_PTR(NIM_BOOL, TM_gfe9a52b5gJr8GSrnr883iA_11) (int fd);
typedef N_CLOSURE_PTR(NIM_BOOL, TM_gfe9a52b5gJr8GSrnr883iA_14) (int fd);
typedef N_CLOSURE_PTR(NIM_BOOL, TM_gfe9a52b5gJr8GSrnr883iA_16) (int fd);
typedef N_CLOSURE_PTR(NIM_BOOL, TM_gfe9a52b5gJr8GSrnr883iA_18) (int fd);
struct tyObject_IndexError_b0IIwghFQBADkB2c86kXQA {
  Exception Sup;
};
typedef N_CLOSURE_PTR(void, TM_gfe9a52b5gJr8GSrnr883iA_24) (void);
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence_lBAKjtL5n9bzoWNSpC1Vu3A {
  TGenericSeq Sup;
  tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg data[SEQ_DECL_SIZE];
};
struct tySequence_M89cHurEB0l2lhCwhToV4tw {
  TGenericSeq Sup;
  tyTuple_V1aU9c9b1eMroa29cC237x0yQ data[SEQ_DECL_SIZE];
};
struct tySequence_WF89a8QyKeDCh4DYWTmSiBg {
  TGenericSeq Sup;
  tyProc_IIomJ6ptE6vfJ5zRbATgkQ data[SEQ_DECL_SIZE];
};
struct tySequence_5L9b5Ztm9adPEys1vE9cEPQJA {
  TGenericSeq Sup;
  tyObject_SelectorKey_561GPxg10TdJiEAAWoraPw data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_lBAKjtL5n9bzoWNSpC1Vu3A)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_LEZ1ZCj9cVMqh7s39cnMX6rw)(void* p, NI op);
static N_NIMCALL(void, TM_gfe9a52b5gJr8GSrnr883iA_6)(void);
N_NIMCALL(void, nimRegisterThreadLocalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(void, setGlobalDispatcher_B0fc5XJSGCrNP8vJ8CrdTQ)(tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* disp);
static N_INLINE(NI, len_eobMY9cShy0eccPQzqc9aNWAasyncdispatch)(tyObject_Deque_oL07LSXp3QMM0uEpFQiyQg* deq);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, initCallSoonProc_jSFKlHW9aWQ06mz9a6ZF5Ylw)(void);
N_LIB_PRIVATE N_NIMCALL(void, getCallSoonProc_EMWMqpRRzDYLwdGrzAQBuA)(tyProc_Ig6kXMs9apW5862wHsbFhGw* Result);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, setCallSoonProc_tp3fL2WDe4gS3fslj7T9aRQ)(tyProc_Ig6kXMs9apW5862wHsbFhGw p);
N_LIB_PRIVATE N_NIMCALL(void, callSoon_CG9b1A8l29b5aBkZZ705M8Aw)(tyProc_IIomJ6ptE6vfJ5zRbATgkQ cbproc);
N_LIB_PRIVATE N_NIMCALL(void, addLast_SSmT9cggOhc9bhKPDkCvVUNQ)(tyObject_Deque_oL07LSXp3QMM0uEpFQiyQg* deq, tyProc_IIomJ6ptE6vfJ5zRbATgkQ item);
N_LIB_PRIVATE N_NIMCALL(tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ*, getGlobalDispatcher_9aj3b7Sd9ahqKV8UGXYgrIUg)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ*, newDispatcher_9aj3b7Sd9ahqKV8UGXYgrIUg_2)(void);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_SelectorImpl_jkoZicTBtYdKkYck5SFJEQ*, newSelector_AXPs0bmJ1uqvbTr1L9cVwaQ)(void);
static N_INLINE(void, newHeapQueue_ewUAKSLI6qNWQ9cLOnliEVwasyncdispatch)(tySequence_M89cHurEB0l2lhCwhToV4tw** h);
N_LIB_PRIVATE N_NIMCALL(tySequence_M89cHurEB0l2lhCwhToV4tw*, newSeq_Rm0ZTAicpkceAAB6E8ahHQ)(NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(void, initDeque_f4iX3P4fP4FRfjhhAZK9c2A)(NI initialSize, tyObject_Deque_oL07LSXp3QMM0uEpFQiyQg* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void*, nimNewSeqOfCap)(TNimType* typ, NI cap);
N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(NI, registerTimer_EmLUmfNLO4HnzujSxzf9cGw)(tyObject_SelectorImpl_jkoZicTBtYdKkYck5SFJEQ* s, NI timeout, NIM_BOOL oneshot, tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA data);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, runOnce_mXlNJtuWiqnwbU9ceoRo80w)(NI timeout);
static N_INLINE(NI, len_MbUHcYx9cYb9bcgf9c9bDUNdKwasyncdispatch)(tySequence_M89cHurEB0l2lhCwhToV4tw* h);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(NI, selectInto_BIf7EhnceBzzQiu9bhuSZTg)(tyObject_SelectorImpl_jkoZicTBtYdKkYck5SFJEQ* s, NI timeout, tyObject_ReadyKey_vOvPQEijZeFv1xAgbh5rNw* results, NI resultsLen_0);
static N_INLINE(NI, adjustedTimeout_LT9aDRhTy2nNhlVT0Hheu2Aasyncdispatch)(tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg* p, NI timeout);
static N_INLINE(void, X5BX5D__cmoQguFTMZvztzMw2X8QZAasyncdispatch)(tySequence_M89cHurEB0l2lhCwhToV4tw* h, NI i, tyTuple_V1aU9c9b1eMroa29cC237x0yQ* Result);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(NF, ntepochTime)(void);
static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgasyncdispatch)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, raiseIOSelectorsError_o9b1ajHBhCZ9cfHDVe9aM1OwA)(NimStringDesc* message);
static N_INLINE(NIM_BOOL, contains_pMqMlNzgkWdYwQvvCFhCMgasyncdispatch)(tyObject_SelectorImpl_jkoZicTBtYdKkYck5SFJEQ* s, NI fd);
N_LIB_PRIVATE N_NIMCALL(tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA*, getData_FpLJNwB9bUrgExzpwKg6rew)(tyObject_SelectorImpl_jkoZicTBtYdKkYck5SFJEQ* s, NI fd);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*, amp__D4JPmvcY0m7CVNPd6sHPwA)(tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* x, tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* y);
N_LIB_PRIVATE N_NIMCALL(void, unregister_hmdECQbyOCuscYhV5uVu2A)(tyObject_SelectorImpl_jkoZicTBtYdKkYck5SFJEQ* s, NI fd);
N_LIB_PRIVATE N_NIMCALL(void, updateHandle_rfvt9cp8cKSo9adyku8uXZCQ)(tyObject_SelectorImpl_jkoZicTBtYdKkYck5SFJEQ* s, int fd, tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg events);
static N_INLINE(void, processTimers_sL9cc2OYri9cNGOu9bRViHxdQasyncdispatch)(tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg* p, NIM_BOOL* didSomeWork);
N_LIB_PRIVATE N_NIMCALL(void, complete_KZMQLA9buvYp8Ta72fC7GPQ)(tyObject_FuturecolonObjectType__9cGbW9cUmV0peAwvBhoDzUzg* future);
N_LIB_PRIVATE N_NIMCALL(void, pop_xtxhYsoSatoaHzG9caytweQ)(tySequence_M89cHurEB0l2lhCwhToV4tw** heap, tyTuple_V1aU9c9b1eMroa29cC237x0yQ* Result);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, processPendingCallbacks_SmnbicdBxLog3d0rzfeG3w)(tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg* p, NIM_BOOL* didSomeWork);
static N_INLINE(void, popFirst_6o7f87XVqquM38FyoAMGhAasyncdispatch)(tyObject_Deque_oL07LSXp3QMM0uEpFQiyQg* deq, tyProc_IIomJ6ptE6vfJ5zRbATgkQ* Result);
N_LIB_PRIVATE N_NIMCALL(void, registerHandle_5DKkEtHHnI8Ye7BLEnzI3g)(tyObject_SelectorImpl_jkoZicTBtYdKkYck5SFJEQ* s, int fd, tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg events, tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA data);
N_LIB_PRIVATE N_NIMCALL(void, unregister_pBjqh3yG0lBifavFSbVYxg)(tyObject_SelectorImpl_jkoZicTBtYdKkYck5SFJEQ* s, int fd);
tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* gDisp_yIbBArLUsg2pBJkilx4yvg;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_E9c1MI1V1IJorH9cqPQ36Hqg_;
TNimType NTI_V1aU9c9b1eMroa29cC237x0yQ_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
extern TNimType NTI_MXXHrE9aQTCHOO4Tm9bXvZnw_;
extern TNimType NTI_M89cHurEB0l2lhCwhToV4tw_;
extern TNimType NTI_oL07LSXp3QMM0uEpFQiyQg_;
TNimType NTI_pnVRciItPqJkU9bkmY2UaWQ_;
TNimType NTI_hOYUN4IOpj9adMwn6W7S2VA_;
TNimType NTI_9cnjNsE9aOh8FkRG9ccBKTpWg_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTI_58EFneeS9at7cA541QCoGAw_;
TNimType NTI_lBAKjtL5n9bzoWNSpC1Vu3A_;
extern TNimType NTI_Y5hK0M9cL3lXwccEV9cgR9cQw_;
TNimType NTI_LEZ1ZCj9cVMqh7s39cnMX6rw_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_yCEN9anxCD6mzBxGjuaRBdg_;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
extern TNimType NTI_IIomJ6ptE6vfJ5zRbATgkQ_;
extern TNimType NTI_z58cIdR0vOibqJ0QwYvB3Q_;
extern TNimType NTI_b0IIwghFQBADkB2c86kXQA_;
STRING_LITERAL(TM_gfe9a52b5gJr8GSrnr883iA_7, "len(gDisp.callbacks) == 0 ", 26);
STRING_LITERAL(TM_gfe9a52b5gJr8GSrnr883iA_9, "No handles or timers registered in dispatcher.", 46);
STRING_LITERAL(TM_gfe9a52b5gJr8GSrnr883iA_10, "Maximum number of descriptors is exhausted!", 43);
STRING_LITERAL(TM_gfe9a52b5gJr8GSrnr883iA_13, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_gfe9a52b5gJr8GSrnr883iA_21, "Empty deque.", 12);
STRING_LITERAL(TM_gfe9a52b5gJr8GSrnr883iA_25, "File descriptor not registered.", 31);
static N_NIMCALL(void, Marker_tySequence_lBAKjtL5n9bzoWNSpC1Vu3A)(void* p, NI op) {
	tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* a;
	NI T1_;
	a = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].ClE_0, op);
	}
}
static N_NIMCALL(void, Marker_tyRef_LEZ1ZCj9cVMqh7s39cnMX6rw)(void* p, NI op) {
	tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* a;
	a = (tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ*)p;
	nimGCvisit((void*)(*a).Sup.timers, op);
	nimGCvisit((void*)(*a).Sup.callbacks.data, op);
	nimGCvisit((void*)(*a).selector, op);
}
static N_NIMCALL(void, TM_gfe9a52b5gJr8GSrnr883iA_6)(void) {
	nimGCvisit((void*)gDisp_yIbBArLUsg2pBJkilx4yvg, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NI, len_eobMY9cShy0eccPQzqc9aNWAasyncdispatch)(tyObject_Deque_oL07LSXp3QMM0uEpFQiyQg* deq) {
	NI result;
	nimfr_("len", "deques.nim");
	result = (NI)0;
	nimln_(64, "deques.nim");
	result = (*deq).count;
	popFrame();
	return result;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		nimln_(185, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln_(218, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(396, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(264, "gc.nim");
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(396, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		nimln_(265, "gc.nim");
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}

static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem(p, ((int) 0), size);
}

N_LIB_PRIVATE N_NIMCALL(void, callSoon_CG9b1A8l29b5aBkZZ705M8Aw)(tyProc_IIomJ6ptE6vfJ5zRbATgkQ cbproc) {
	tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* T1_;
	nimfr_("callSoon", "asyncdispatch.nim");
	nimln_(1637, "asyncdispatch.nim");
	T1_ = (tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ*)0;
	T1_ = getGlobalDispatcher_9aj3b7Sd9ahqKV8UGXYgrIUg();
	addLast_SSmT9cggOhc9bhKPDkCvVUNQ((&(*T1_).Sup.callbacks), cbproc);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, initCallSoonProc_jSFKlHW9aWQ06mz9a6ZF5Ylw)(void) {
	nimfr_("initCallSoonProc", "asyncdispatch.nim");
	nimln_(200, "asyncdispatch.nim");
	{
		tyProc_Ig6kXMs9apW5862wHsbFhGw T3_;
		tyProc_Ig6kXMs9apW5862wHsbFhGw T6_;
		nimZeroMem((void*)(&T3_), sizeof(tyProc_Ig6kXMs9apW5862wHsbFhGw));
		getCallSoonProc_EMWMqpRRzDYLwdGrzAQBuA((&T3_));
		if (!(T3_.ClP_0 == 0)) goto LA4_;
		nimln_(201, "asyncdispatch.nim");
		nimZeroMem((void*)(&T6_), sizeof(tyProc_Ig6kXMs9apW5862wHsbFhGw));
		T6_.ClP_0 = ((TM_gfe9a52b5gJr8GSrnr883iA_8) (callSoon_CG9b1A8l29b5aBkZZ705M8Aw)); T6_.ClE_0 = NIM_NIL;
		setCallSoonProc_tp3fL2WDe4gS3fslj7T9aRQ(T6_);
	}
	LA4_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, setGlobalDispatcher_B0fc5XJSGCrNP8vJ8CrdTQ)(tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* disp) {
	nimfr_("setGlobalDispatcher", "asyncdispatch.nim");
	nimln_(1097, "asyncdispatch.nim");
	{
		if (!!((gDisp_yIbBArLUsg2pBJkilx4yvg == 0))) goto LA3_;
		nimln_(1098, "asyncdispatch.nim");
		{
			NI T7_;
			T7_ = (NI)0;
			T7_ = len_eobMY9cShy0eccPQzqc9aNWAasyncdispatch((&(*gDisp_yIbBArLUsg2pBJkilx4yvg).Sup.callbacks));
			if (!!((T7_ == ((NI) 0)))) goto LA8_;
			failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_gfe9a52b5gJr8GSrnr883iA_7));
		}
		LA8_: ;
	}
	LA3_: ;
	nimln_(1099, "asyncdispatch.nim");
	asgnRef((void**) (&gDisp_yIbBArLUsg2pBJkilx4yvg), disp);
	nimln_(1100, "asyncdispatch.nim");
	initCallSoonProc_jSFKlHW9aWQ06mz9a6ZF5Ylw();
	popFrame();
}

static N_INLINE(void, newHeapQueue_ewUAKSLI6qNWQ9cLOnliEVwasyncdispatch)(tySequence_M89cHurEB0l2lhCwhToV4tw** h) {
	nimfr_("newHeapQueue", "heapqueue.nim");
	nimln_(22, "heapqueue.nim");
	unsureAsgnRef((void**) (&(*h)), newSeq_Rm0ZTAicpkceAAB6E8ahHQ(((NI) 0)));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ*, newDispatcher_9aj3b7Sd9ahqKV8UGXYgrIUg_2)(void) {
	tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* result;
	nimfr_("newDispatcher", "asyncdispatch.nim");
	result = (tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ*)0;
	nimln_(1089, "asyncdispatch.nim");
	result = (tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ*) newObj((&NTI_LEZ1ZCj9cVMqh7s39cnMX6rw_), sizeof(tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ));
	(*result).Sup.Sup.m_type = (&NTI_pnVRciItPqJkU9bkmY2UaWQ_);
	nimln_(1090, "asyncdispatch.nim");
	asgnRef((void**) (&(*result).selector), newSelector_AXPs0bmJ1uqvbTr1L9cVwaQ());
	nimln_(1091, "asyncdispatch.nim");
	newHeapQueue_ewUAKSLI6qNWQ9cLOnliEVwasyncdispatch((&(*result).Sup.timers));
	nimln_(1092, "asyncdispatch.nim");
	initDeque_f4iX3P4fP4FRfjhhAZK9c2A(((NI) 64), (&(*result).Sup.callbacks));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ*, getGlobalDispatcher_9aj3b7Sd9ahqKV8UGXYgrIUg)(void) {
	tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* result;
	nimfr_("getGlobalDispatcher", "asyncdispatch.nim");
	result = (tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ*)0;
	nimln_(1103, "asyncdispatch.nim");
	{
		tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* T5_;
		if (!(gDisp_yIbBArLUsg2pBJkilx4yvg == 0)) goto LA3_;
		nimln_(1104, "asyncdispatch.nim");
		T5_ = (tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ*)0;
		T5_ = newDispatcher_9aj3b7Sd9ahqKV8UGXYgrIUg_2();
		setGlobalDispatcher_B0fc5XJSGCrNP8vJ8CrdTQ(T5_);
	}
	LA3_: ;
	nimln_(1105, "asyncdispatch.nim");
	result = gDisp_yIbBArLUsg2pBJkilx4yvg;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SelectorImpl_jkoZicTBtYdKkYck5SFJEQ*, getIoHandler_1cfqNcVKBrqucaxs09alXtg)(tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* disp) {
	tyObject_SelectorImpl_jkoZicTBtYdKkYck5SFJEQ* result;
	nimfr_("getIoHandler", "asyncdispatch.nim");
{	result = (tyObject_SelectorImpl_jkoZicTBtYdKkYck5SFJEQ*)0;
	nimln_(1108, "asyncdispatch.nim");
	result = (*disp).selector;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, addTimer_YxmGU9bAzUo0iGWEKPuPV6g)(NI timeout, NIM_BOOL oneshot, tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg cb) {
	tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* p;
	tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA data;
	NI T1_;
	NI T2_;
	nimfr_("addTimer", "asyncdispatch.nim");
	nimln_(1459, "asyncdispatch.nim");
	p = getGlobalDispatcher_9aj3b7Sd9ahqKV8UGXYgrIUg();
	nimZeroMem((void*)(&data), sizeof(tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA));
	nimln_(1460, "asyncdispatch.nim");
	chckNil((void*)(&data));
	nimZeroMem((void*)(&data), sizeof(tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA));
	nimln_(1084, "asyncdispatch.nim");
	data.readList = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)nimNewSeqOfCap((&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_), ((NI) 4));
	nimln_(1085, "asyncdispatch.nim");
	data.writeList = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)nimNewSeqOfCap((&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_), ((NI) 4));
	nimln_(1461, "asyncdispatch.nim");
	data.readList = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*) incrSeqV3(&(data.readList)->Sup, (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_));
	T1_ = data.readList->Sup.len++;
	asgnRef((void**) (&data.readList->data[T1_].ClE_0), cb.ClE_0);
	data.readList->data[T1_].ClP_0 = cb.ClP_0;
	nimln_(1462, "asyncdispatch.nim");
	T2_ = (NI)0;
	T2_ = registerTimer_EmLUmfNLO4HnzujSxzf9cGw((*p).selector, timeout, oneshot, data);
	popFrame();
}

static N_INLINE(NI, len_MbUHcYx9cYb9bcgf9c9bDUNdKwasyncdispatch)(tySequence_M89cHurEB0l2lhCwhToV4tw* h) {
	NI result;
	NI T1_;
	nimfr_("len", "heapqueue.nim");
	result = (NI)0;
	nimln_(24, "heapqueue.nim");
	T1_ = (h ? h->Sup.len : 0);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		nimln_(185, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln_(252, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, X5BX5D__cmoQguFTMZvztzMw2X8QZAasyncdispatch)(tySequence_M89cHurEB0l2lhCwhToV4tw* h, NI i, tyTuple_V1aU9c9b1eMroa29cC237x0yQ* Result) {
	nimfr_("[]", "heapqueue.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_V1aU9c9b1eMroa29cC237x0yQ_));
	nimln_(25, "heapqueue.nim");
	if (!h || (NU)(i) >= (NU)(h->Sup.len)) raiseIndexError();
	(*Result).Field0 = h->data[i].Field0;
	unsureAsgnRef((void**) (&(*Result).Field1), h->data[i].Field1);
	popFrame();
}

static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgasyncdispatch)(NI x, NI y) {
	NF result;
	nimfr_("/", "system.nim");
	result = (NF)0;
	nimln_(3473, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

static N_INLINE(NI, adjustedTimeout_LT9aDRhTy2nNhlVT0Hheu2Aasyncdispatch)(tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg* p, NI timeout) {
	NI result;
	nimfr_("adjustedTimeout", "asyncdispatch.nim");
	result = (NI)0;
	nimln_(189, "asyncdispatch.nim");
	result = timeout;
	nimln_(190, "asyncdispatch.nim");
	{
		NI T3_;
		NF timerTimeout;
		tyTuple_V1aU9c9b1eMroa29cC237x0yQ T6_;
		NF curTime;
		T3_ = (NI)0;
		T3_ = len_MbUHcYx9cYb9bcgf9c9bDUNdKwasyncdispatch((*p).timers);
		if (!(((NI) 0) < T3_)) goto LA4_;
		nimln_(191, "asyncdispatch.nim");
		nimZeroMem((void*)(&T6_), sizeof(tyTuple_V1aU9c9b1eMroa29cC237x0yQ));
		X5BX5D__cmoQguFTMZvztzMw2X8QZAasyncdispatch((*p).timers, ((NI) 0), (&T6_));
		timerTimeout = T6_.Field0;
		nimln_(192, "asyncdispatch.nim");
		curTime = ntepochTime();
		nimln_(193, "asyncdispatch.nim");
		{
			NIM_BOOL T9_;
			NF T11_;
			T9_ = (NIM_BOOL)0;
			T9_ = (timeout == ((NI) -1));
			if (T9_) goto LA10_;
			T11_ = (NF)0;
			T11_ = slash__fu0hCFNNw3xnGgcs2KwTWgasyncdispatch(timeout, ((NI) 1000));
			T9_ = (timerTimeout < ((NF)(curTime) + (NF)(T11_)));
			LA10_: ;
			if (!T9_) goto LA12_;
			nimln_(194, "asyncdispatch.nim");
			result = ((NI) (((NF)(((NF)(timerTimeout) - (NF)(curTime))) * (NF)(1.0000000000000000e+03))));
			nimln_(195, "asyncdispatch.nim");
			{
				if (!(result < ((NI) 0))) goto LA16_;
				result = ((NI) 0);
			}
			LA16_: ;
		}
		LA12_: ;
	}
	LA4_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_pMqMlNzgkWdYwQvvCFhCMgasyncdispatch)(tyObject_SelectorImpl_jkoZicTBtYdKkYck5SFJEQ* s, NI fd) {
	NIM_BOOL result;
	nimfr_("contains", "ioselectors_epoll.nim");
{	result = (NIM_BOOL)0;
	nimln_(485, "ioselectors_epoll.nim");
	nimln_(396, "system.nim");
	if (!(*s).fds || (NU)(fd) >= (NU)((*s).fds->Sup.len)) raiseIndexError();
	result = !(((*s).fds->data[fd].ident == ((NI) 0)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, processTimers_sL9cc2OYri9cNGOu9bRViHxdQasyncdispatch)(tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg* p, NIM_BOOL* didSomeWork) {
	NI count;
	NF t;
	nimfr_("processTimers", "asyncdispatch.nim");
	nimln_(173, "asyncdispatch.nim");
	count = len_MbUHcYx9cYb9bcgf9c9bDUNdKwasyncdispatch((*p).timers);
	nimln_(174, "asyncdispatch.nim");
	t = ntepochTime();
	{
		nimln_(175, "asyncdispatch.nim");
		while (1) {
			NIM_BOOL T3_;
			tyTuple_V1aU9c9b1eMroa29cC237x0yQ T5_;
			tyTuple_V1aU9c9b1eMroa29cC237x0yQ T6_;
			NI TM_gfe9a52b5gJr8GSrnr883iA_20;
			T3_ = (NIM_BOOL)0;
			T3_ = (((NI) 0) < count);
			if (!(T3_)) goto LA4_;
			nimZeroMem((void*)(&T5_), sizeof(tyTuple_V1aU9c9b1eMroa29cC237x0yQ));
			X5BX5D__cmoQguFTMZvztzMw2X8QZAasyncdispatch((*p).timers, ((NI) 0), (&T5_));
			T3_ = (T5_.Field0 <= t);
			LA4_: ;
			if (!T3_) goto LA2;
			nimln_(176, "asyncdispatch.nim");
			nimZeroMem((void*)(&T6_), sizeof(tyTuple_V1aU9c9b1eMroa29cC237x0yQ));
			pop_xtxhYsoSatoaHzG9caytweQ((&(*p).timers), (&T6_));
			complete_KZMQLA9buvYp8Ta72fC7GPQ(T6_.Field1);
			nimln_(177, "asyncdispatch.nim");
			TM_gfe9a52b5gJr8GSrnr883iA_20 = subInt(count, ((NI) 1));
			count = (NI)(TM_gfe9a52b5gJr8GSrnr883iA_20);
			nimln_(178, "asyncdispatch.nim");
			(*didSomeWork) = NIM_TRUE;
		} LA2: ;
	}
	popFrame();
}

static N_INLINE(void, popFirst_6o7f87XVqquM38FyoAMGhAasyncdispatch)(tyObject_Deque_oL07LSXp3QMM0uEpFQiyQg* deq, tyProc_IIomJ6ptE6vfJ5zRbATgkQ* Result) {
	NI TM_gfe9a52b5gJr8GSrnr883iA_22;
	NI TM_gfe9a52b5gJr8GSrnr883iA_23;
	nimfr_("popFirst", "deques.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_IIomJ6ptE6vfJ5zRbATgkQ_));
	nimln_(69, "deques.nim");
	{
		NIM_BOOL T3_;
		tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
		NimStringDesc* T6_;
		nimln_(3469, "system.nim");
		nimln_(69, "deques.nim");
		T3_ = (NIM_BOOL)0;
		T3_ = unlikely(((*deq).count < ((NI) 1)));
		if (!T3_) goto LA4_;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
		nimln_(2785, "system.nim");
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
		(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
		nimln_(70, "deques.nim");
		T6_ = (NimStringDesc*)0;
		T6_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_gfe9a52b5gJr8GSrnr883iA_21));
		if (T6_) nimGCunrefNoCycle(T6_);
		nimln_(2780, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(70, "deques.nim");
		raiseException((Exception*)e, "IndexError");
	}
	LA4_: ;
	nimln_(172, "deques.nim");
	TM_gfe9a52b5gJr8GSrnr883iA_22 = subInt((*deq).count, ((NI) 1));
	(*deq).count = (NI)(TM_gfe9a52b5gJr8GSrnr883iA_22);
	nimln_(173, "deques.nim");
	if (!(*deq).data || (NU)((*deq).head) >= (NU)((*deq).data->Sup.len)) raiseIndexError();
	unsureAsgnRef((void**) (&(*Result).ClE_0), (*deq).data->data[(*deq).head].ClE_0);
	(*Result).ClP_0 = (*deq).data->data[(*deq).head].ClP_0;
	nimln_(167, "deques.nim");
	if (!(*deq).data || (NU)((*deq).head) >= (NU)((*deq).data->Sup.len)) raiseIndexError();
	genericReset((void*)(&(*deq).data->data[(*deq).head]), (&NTI_IIomJ6ptE6vfJ5zRbATgkQ_));
	nimln_(175, "deques.nim");
	TM_gfe9a52b5gJr8GSrnr883iA_23 = addInt((*deq).head, ((NI) 1));
	(*deq).head = (NI)((NI)(TM_gfe9a52b5gJr8GSrnr883iA_23) & (*deq).mask);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, processPendingCallbacks_SmnbicdBxLog3d0rzfeG3w)(tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg* p, NIM_BOOL* didSomeWork) {
	nimfr_("processPendingCallbacks", "asyncdispatch.nim");
	{
		nimln_(181, "asyncdispatch.nim");
		while (1) {
			NI T3_;
			tyProc_IIomJ6ptE6vfJ5zRbATgkQ cb;
			T3_ = (NI)0;
			T3_ = len_eobMY9cShy0eccPQzqc9aNWAasyncdispatch((&(*p).callbacks));
			if (!(((NI) 0) < T3_)) goto LA2;
			nimZeroMem((void*)(&cb), sizeof(tyProc_IIomJ6ptE6vfJ5zRbATgkQ));
			nimln_(182, "asyncdispatch.nim");
			popFirst_6o7f87XVqquM38FyoAMGhAasyncdispatch((&(*p).callbacks), (&cb));
			nimln_(183, "asyncdispatch.nim");
			cb.ClE_0? cb.ClP_0(cb.ClE_0):((TM_gfe9a52b5gJr8GSrnr883iA_24)(cb.ClP_0))();
			nimln_(184, "asyncdispatch.nim");
			(*didSomeWork) = NIM_TRUE;
		} LA2: ;
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, runOnce_mXlNJtuWiqnwbU9ceoRo80w)(NI timeout) {
	NIM_BOOL result;
	tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* p;
	tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg customSet;
	tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg* T226_;
	tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg* T227_;
	nimfr_("runOnce", "asyncdispatch.nim");
	result = (NIM_BOOL)0;
	nimln_(1224, "asyncdispatch.nim");
	p = getGlobalDispatcher_9aj3b7Sd9ahqKV8UGXYgrIUg();
	nimln_(1226, "asyncdispatch.nim");
	customSet = 60;
	nimln_(1229, "asyncdispatch.nim");
	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NI T6_;
		NI T8_;
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
		NimStringDesc* T11_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = ((*(*p).selector).count == ((NI) 0));
		if (!(T4_)) goto LA5_;
		T6_ = (NI)0;
		T6_ = len_MbUHcYx9cYb9bcgf9c9bDUNdKwasyncdispatch((*p).Sup.timers);
		T4_ = (T6_ == ((NI) 0));
		LA5_: ;
		T3_ = T4_;
		if (!(T3_)) goto LA7_;
		T8_ = (NI)0;
		T8_ = len_eobMY9cShy0eccPQzqc9aNWAasyncdispatch((&(*p).Sup.callbacks));
		T3_ = (T8_ == ((NI) 0));
		LA7_: ;
		if (!T3_) goto LA9_;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		nimln_(2785, "system.nim");
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		nimln_(1231, "asyncdispatch.nim");
		T11_ = (NimStringDesc*)0;
		T11_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_gfe9a52b5gJr8GSrnr883iA_9));
		if (T11_) nimGCunrefNoCycle(T11_);
		nimln_(2780, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(1230, "asyncdispatch.nim");
		raiseException((Exception*)e, "ValueError");
	}
	LA9_: ;
	nimln_(1233, "asyncdispatch.nim");
	result = NIM_FALSE;
	nimln_(1234, "asyncdispatch.nim");
	{
		tyArray_ldWGqPJo6WgJz7q23H0LJQ keys;
		NI count;
		tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg* T16_;
		NI T17_;
		if (!!(((*(*p).selector).count == ((NI) 0)))) goto LA14_;
		nimZeroMem((void*)keys, sizeof(tyArray_ldWGqPJo6WgJz7q23H0LJQ));
		nimln_(1236, "asyncdispatch.nim");
		T16_ = (tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg*)0;
		T16_ = &p->Sup;
		T17_ = (NI)0;
		T17_ = adjustedTimeout_LT9aDRhTy2nNhlVT0Hheu2Aasyncdispatch(T16_, timeout);
		count = selectInto_BIf7EhnceBzzQiu9bhuSZTg((*p).selector, T17_, keys, 64);
		{
			NI i;
			NI i_2;
			i = (NI)0;
			nimln_(3494, "system.nim");
			i_2 = ((NI) 0);
			{
				nimln_(3495, "system.nim");
				while (1) {
					NIM_BOOL custom;
					NI fd;
					tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg events;
					NI rLength;
					NI wLength;
					NI TM_gfe9a52b5gJr8GSrnr883iA_19;
					if (!(i_2 < count)) goto LA20;
					nimln_(3496, "system.nim");
					i = i_2;
					nimln_(1238, "asyncdispatch.nim");
					custom = NIM_FALSE;
					nimln_(1239, "asyncdispatch.nim");
					if ((NU)(i) > (NU)(63)) raiseIndexError();
					fd = keys[(i)- 0].fd;
					nimln_(1240, "asyncdispatch.nim");
					if ((NU)(i) > (NU)(63)) raiseIndexError();
					events = keys[(i)- 0].events;
					nimln_(1241, "asyncdispatch.nim");
					rLength = ((NI) 0);
					nimln_(1242, "asyncdispatch.nim");
					wLength = ((NI) 0);
					nimln_(1244, "asyncdispatch.nim");
					{
						NIM_BOOL T23_;
						tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* curList;
						NI fdi;
						NI newLength;
						NI T36_;
						tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* newList;
						NI fdi_2;
						T23_ = (NIM_BOOL)0;
						T23_ = ((events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 0))&31U)))!=0);
						if (T23_) goto LA24_;
						T23_ = (events == 128);
						LA24_: ;
						if (!T23_) goto LA25_;
						curList = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)0;
						nimln_(503, "ioselectors_epoll.nim");
						fdi = fd;
						nimln_(504, "ioselectors_epoll.nim");
						{
							nimln_(131, "ioselectors_epoll.nim");
							if (!((*(*p).selector).maxFD <= fdi)) goto LA29_;
							nimln_(132, "ioselectors_epoll.nim");
							raiseIOSelectorsError_o9b1ajHBhCZ9cfHDVe9aM1OwA(((NimStringDesc*) &TM_gfe9a52b5gJr8GSrnr883iA_10));
						}
						LA29_: ;
						nimln_(1168, "asyncdispatch.nim");
						{
							NIM_BOOL T33_;
							tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA* adata;
							nimln_(505, "ioselectors_epoll.nim");
							T33_ = (NIM_BOOL)0;
							T33_ = contains_pMqMlNzgkWdYwQvvCFhCMgasyncdispatch((*p).selector, fdi);
							if (!T33_) goto LA34_;
							nimln_(506, "ioselectors_epoll.nim");
							adata = getData_FpLJNwB9bUrgExzpwKg6rew((*p).selector, fdi);
							nimln_(1169, "asyncdispatch.nim");
							curList = (*adata).readList;
							nimln_(1170, "asyncdispatch.nim");
							unsureAsgnRef((void**) (&(*adata).readList), (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)nimNewSeqOfCap((&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_), ((NI) 4)));
						}
						LA34_: ;
						nimln_(1172, "asyncdispatch.nim");
						T36_ = (curList ? curList->Sup.len : 0);
						newLength = ((T36_ >= ((NI) 4)) ? T36_ : ((NI) 4));
						nimln_(1173, "asyncdispatch.nim");
						newList = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)nimNewSeqOfCap((&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_), ((NI)chckRange(newLength, ((NI) 0), ((NI) IL64(9223372036854775807)))));
						{
							tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg cb;
							NI i_3;
							NI L;
							NI T38_;
							nimZeroMem((void*)(&cb), sizeof(tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg));
							nimln_(3782, "system.nim");
							i_3 = ((NI) 0);
							nimln_(3783, "system.nim");
							T38_ = (curList ? curList->Sup.len : 0);
							L = T38_;
							{
								nimln_(3784, "system.nim");
								while (1) {
									NI TM_gfe9a52b5gJr8GSrnr883iA_12;
									if (!(i_3 < L)) goto LA40;
									nimln_(3785, "system.nim");
									if (!curList || (NU)(i_3) >= (NU)(curList->Sup.len)) raiseIndexError();
									cb.ClE_0 = curList->data[i_3].ClE_0;
									cb.ClP_0 = curList->data[i_3].ClP_0;
									nimln_(1176, "asyncdispatch.nim");
									{
										NI T43_;
										NI T46_;
										T43_ = (newList ? newList->Sup.len : 0);
										if (!(((NI) 0) < T43_)) goto LA44_;
										nimln_(1179, "asyncdispatch.nim");
										newList = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*) incrSeqV3(&(newList)->Sup, (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_));
										T46_ = newList->Sup.len++;
										asgnRef((void**) (&newList->data[T46_].ClE_0), cb.ClE_0);
										newList->data[T46_].ClP_0 = cb.ClP_0;
									}
									goto LA41_;
									LA44_: ;
									{
										nimln_(1181, "asyncdispatch.nim");
										{
											NIM_BOOL T50_;
											NI T53_;
											T50_ = (NIM_BOOL)0;
											T50_ = cb.ClE_0? cb.ClP_0(((int)chckRange(fd, ((int) (-2147483647 -1)), ((int) 2147483647))), cb.ClE_0):((TM_gfe9a52b5gJr8GSrnr883iA_11)(cb.ClP_0))(((int)chckRange(fd, ((int) (-2147483647 -1)), ((int) 2147483647))));
											if (!!(T50_)) goto LA51_;
											nimln_(1183, "asyncdispatch.nim");
											newList = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*) incrSeqV3(&(newList)->Sup, (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_));
											T53_ = newList->Sup.len++;
											asgnRef((void**) (&newList->data[T53_].ClE_0), cb.ClE_0);
											newList->data[T53_].ClP_0 = cb.ClP_0;
										}
										LA51_: ;
									}
									LA41_: ;
									nimln_(3786, "system.nim");
									TM_gfe9a52b5gJr8GSrnr883iA_12 = addInt(i_3, ((NI) 1));
									i_3 = (NI)(TM_gfe9a52b5gJr8GSrnr883iA_12);
									nimln_(3787, "system.nim");
									{
										NI T56_;
										T56_ = (curList ? curList->Sup.len : 0);
										if (!!((T56_ == L))) goto LA57_;
										failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_gfe9a52b5gJr8GSrnr883iA_13));
									}
									LA57_: ;
								} LA40: ;
							}
						}
						nimln_(512, "ioselectors_epoll.nim");
						fdi_2 = fd;
						nimln_(513, "ioselectors_epoll.nim");
						{
							nimln_(131, "ioselectors_epoll.nim");
							if (!((*(*p).selector).maxFD <= fdi_2)) goto LA61_;
							nimln_(132, "ioselectors_epoll.nim");
							raiseIOSelectorsError_o9b1ajHBhCZ9cfHDVe9aM1OwA(((NimStringDesc*) &TM_gfe9a52b5gJr8GSrnr883iA_10));
						}
						LA61_: ;
						nimln_(1245, "asyncdispatch.nim");
						{
							NIM_BOOL T65_;
							tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA* adata_2;
							NI T68_;
							NI T69_;
							nimln_(514, "ioselectors_epoll.nim");
							T65_ = (NIM_BOOL)0;
							T65_ = contains_pMqMlNzgkWdYwQvvCFhCMgasyncdispatch((*p).selector, fdi_2);
							if (!T65_) goto LA66_;
							nimln_(515, "ioselectors_epoll.nim");
							adata_2 = getData_FpLJNwB9bUrgExzpwKg6rew((*p).selector, fdi_2);
							nimln_(1187, "asyncdispatch.nim");
							unsureAsgnRef((void**) (&(*adata_2).readList), amp__D4JPmvcY0m7CVNPd6sHPwA(newList, (*adata_2).readList));
							nimln_(1188, "asyncdispatch.nim");
							T68_ = ((*adata_2).readList ? (*adata_2).readList->Sup.len : 0);
							rLength = T68_;
							nimln_(1189, "asyncdispatch.nim");
							T69_ = ((*adata_2).writeList ? (*adata_2).writeList->Sup.len : 0);
							wLength = T69_;
						}
						goto LA63_;
						LA66_: ;
						{
							nimln_(1192, "asyncdispatch.nim");
							rLength = ((NI) -1);
							nimln_(1193, "asyncdispatch.nim");
							wLength = ((NI) -1);
						}
						LA63_: ;
						nimln_(1246, "asyncdispatch.nim");
						result = NIM_TRUE;
					}
					LA25_: ;
					nimln_(1248, "asyncdispatch.nim");
					{
						NIM_BOOL T73_;
						tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* curList_2;
						NI fdi_3;
						NI newLength_2;
						NI T86_;
						tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* newList_2;
						NI fdi_4;
						T73_ = (NIM_BOOL)0;
						T73_ = ((events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 1))&31U)))!=0);
						if (T73_) goto LA74_;
						T73_ = (events == 128);
						LA74_: ;
						if (!T73_) goto LA75_;
						curList_2 = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)0;
						nimln_(503, "ioselectors_epoll.nim");
						fdi_3 = fd;
						nimln_(504, "ioselectors_epoll.nim");
						{
							nimln_(131, "ioselectors_epoll.nim");
							if (!((*(*p).selector).maxFD <= fdi_3)) goto LA79_;
							nimln_(132, "ioselectors_epoll.nim");
							raiseIOSelectorsError_o9b1ajHBhCZ9cfHDVe9aM1OwA(((NimStringDesc*) &TM_gfe9a52b5gJr8GSrnr883iA_10));
						}
						LA79_: ;
						nimln_(1168, "asyncdispatch.nim");
						{
							NIM_BOOL T83_;
							tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA* adata_3;
							nimln_(505, "ioselectors_epoll.nim");
							T83_ = (NIM_BOOL)0;
							T83_ = contains_pMqMlNzgkWdYwQvvCFhCMgasyncdispatch((*p).selector, fdi_3);
							if (!T83_) goto LA84_;
							nimln_(506, "ioselectors_epoll.nim");
							adata_3 = getData_FpLJNwB9bUrgExzpwKg6rew((*p).selector, fdi_3);
							nimln_(1169, "asyncdispatch.nim");
							curList_2 = (*adata_3).writeList;
							nimln_(1170, "asyncdispatch.nim");
							unsureAsgnRef((void**) (&(*adata_3).writeList), (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)nimNewSeqOfCap((&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_), ((NI) 4)));
						}
						LA84_: ;
						nimln_(1172, "asyncdispatch.nim");
						T86_ = (curList_2 ? curList_2->Sup.len : 0);
						newLength_2 = ((T86_ >= ((NI) 4)) ? T86_ : ((NI) 4));
						nimln_(1173, "asyncdispatch.nim");
						newList_2 = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)nimNewSeqOfCap((&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_), ((NI)chckRange(newLength_2, ((NI) 0), ((NI) IL64(9223372036854775807)))));
						{
							tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg cb_2;
							NI i_4;
							NI L_2;
							NI T88_;
							nimZeroMem((void*)(&cb_2), sizeof(tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg));
							nimln_(3782, "system.nim");
							i_4 = ((NI) 0);
							nimln_(3783, "system.nim");
							T88_ = (curList_2 ? curList_2->Sup.len : 0);
							L_2 = T88_;
							{
								nimln_(3784, "system.nim");
								while (1) {
									NI TM_gfe9a52b5gJr8GSrnr883iA_15;
									if (!(i_4 < L_2)) goto LA90;
									nimln_(3785, "system.nim");
									if (!curList_2 || (NU)(i_4) >= (NU)(curList_2->Sup.len)) raiseIndexError();
									cb_2.ClE_0 = curList_2->data[i_4].ClE_0;
									cb_2.ClP_0 = curList_2->data[i_4].ClP_0;
									nimln_(1176, "asyncdispatch.nim");
									{
										NI T93_;
										NI T96_;
										T93_ = (newList_2 ? newList_2->Sup.len : 0);
										if (!(((NI) 0) < T93_)) goto LA94_;
										nimln_(1179, "asyncdispatch.nim");
										newList_2 = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*) incrSeqV3(&(newList_2)->Sup, (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_));
										T96_ = newList_2->Sup.len++;
										asgnRef((void**) (&newList_2->data[T96_].ClE_0), cb_2.ClE_0);
										newList_2->data[T96_].ClP_0 = cb_2.ClP_0;
									}
									goto LA91_;
									LA94_: ;
									{
										nimln_(1181, "asyncdispatch.nim");
										{
											NIM_BOOL T100_;
											NI T103_;
											T100_ = (NIM_BOOL)0;
											T100_ = cb_2.ClE_0? cb_2.ClP_0(((int)chckRange(fd, ((int) (-2147483647 -1)), ((int) 2147483647))), cb_2.ClE_0):((TM_gfe9a52b5gJr8GSrnr883iA_14)(cb_2.ClP_0))(((int)chckRange(fd, ((int) (-2147483647 -1)), ((int) 2147483647))));
											if (!!(T100_)) goto LA101_;
											nimln_(1183, "asyncdispatch.nim");
											newList_2 = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*) incrSeqV3(&(newList_2)->Sup, (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_));
											T103_ = newList_2->Sup.len++;
											asgnRef((void**) (&newList_2->data[T103_].ClE_0), cb_2.ClE_0);
											newList_2->data[T103_].ClP_0 = cb_2.ClP_0;
										}
										LA101_: ;
									}
									LA91_: ;
									nimln_(3786, "system.nim");
									TM_gfe9a52b5gJr8GSrnr883iA_15 = addInt(i_4, ((NI) 1));
									i_4 = (NI)(TM_gfe9a52b5gJr8GSrnr883iA_15);
									nimln_(3787, "system.nim");
									{
										NI T106_;
										T106_ = (curList_2 ? curList_2->Sup.len : 0);
										if (!!((T106_ == L_2))) goto LA107_;
										failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_gfe9a52b5gJr8GSrnr883iA_13));
									}
									LA107_: ;
								} LA90: ;
							}
						}
						nimln_(512, "ioselectors_epoll.nim");
						fdi_4 = fd;
						nimln_(513, "ioselectors_epoll.nim");
						{
							nimln_(131, "ioselectors_epoll.nim");
							if (!((*(*p).selector).maxFD <= fdi_4)) goto LA111_;
							nimln_(132, "ioselectors_epoll.nim");
							raiseIOSelectorsError_o9b1ajHBhCZ9cfHDVe9aM1OwA(((NimStringDesc*) &TM_gfe9a52b5gJr8GSrnr883iA_10));
						}
						LA111_: ;
						nimln_(1249, "asyncdispatch.nim");
						{
							NIM_BOOL T115_;
							tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA* adata_4;
							NI T118_;
							NI T119_;
							nimln_(514, "ioselectors_epoll.nim");
							T115_ = (NIM_BOOL)0;
							T115_ = contains_pMqMlNzgkWdYwQvvCFhCMgasyncdispatch((*p).selector, fdi_4);
							if (!T115_) goto LA116_;
							nimln_(515, "ioselectors_epoll.nim");
							adata_4 = getData_FpLJNwB9bUrgExzpwKg6rew((*p).selector, fdi_4);
							nimln_(1187, "asyncdispatch.nim");
							unsureAsgnRef((void**) (&(*adata_4).writeList), amp__D4JPmvcY0m7CVNPd6sHPwA(newList_2, (*adata_4).writeList));
							nimln_(1188, "asyncdispatch.nim");
							T118_ = ((*adata_4).readList ? (*adata_4).readList->Sup.len : 0);
							rLength = T118_;
							nimln_(1189, "asyncdispatch.nim");
							T119_ = ((*adata_4).writeList ? (*adata_4).writeList->Sup.len : 0);
							wLength = T119_;
						}
						goto LA113_;
						LA116_: ;
						{
							nimln_(1192, "asyncdispatch.nim");
							rLength = ((NI) -1);
							nimln_(1193, "asyncdispatch.nim");
							wLength = ((NI) -1);
						}
						LA113_: ;
						nimln_(1250, "asyncdispatch.nim");
						result = NIM_TRUE;
					}
					LA75_: ;
					nimln_(1252, "asyncdispatch.nim");
					{
						tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* curList_3;
						NI fdi_5;
						NI newLength_3;
						NI T134_;
						tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* newList_3;
						NI fdi_6;
						if (!((events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 6))&31U)))!=0)) goto LA123_;
						curList_3 = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)0;
						nimln_(503, "ioselectors_epoll.nim");
						fdi_5 = fd;
						nimln_(504, "ioselectors_epoll.nim");
						{
							nimln_(131, "ioselectors_epoll.nim");
							if (!((*(*p).selector).maxFD <= fdi_5)) goto LA127_;
							nimln_(132, "ioselectors_epoll.nim");
							raiseIOSelectorsError_o9b1ajHBhCZ9cfHDVe9aM1OwA(((NimStringDesc*) &TM_gfe9a52b5gJr8GSrnr883iA_10));
						}
						LA127_: ;
						nimln_(1168, "asyncdispatch.nim");
						{
							NIM_BOOL T131_;
							tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA* adata_5;
							nimln_(505, "ioselectors_epoll.nim");
							T131_ = (NIM_BOOL)0;
							T131_ = contains_pMqMlNzgkWdYwQvvCFhCMgasyncdispatch((*p).selector, fdi_5);
							if (!T131_) goto LA132_;
							nimln_(506, "ioselectors_epoll.nim");
							adata_5 = getData_FpLJNwB9bUrgExzpwKg6rew((*p).selector, fdi_5);
							nimln_(1169, "asyncdispatch.nim");
							curList_3 = (*adata_5).readList;
							nimln_(1170, "asyncdispatch.nim");
							unsureAsgnRef((void**) (&(*adata_5).readList), (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)nimNewSeqOfCap((&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_), ((NI) 4)));
						}
						LA132_: ;
						nimln_(1172, "asyncdispatch.nim");
						T134_ = (curList_3 ? curList_3->Sup.len : 0);
						newLength_3 = ((T134_ >= ((NI) 4)) ? T134_ : ((NI) 4));
						nimln_(1173, "asyncdispatch.nim");
						newList_3 = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)nimNewSeqOfCap((&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_), ((NI)chckRange(newLength_3, ((NI) 0), ((NI) IL64(9223372036854775807)))));
						{
							tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg cb_3;
							NI i_5;
							NI L_3;
							NI T136_;
							nimZeroMem((void*)(&cb_3), sizeof(tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg));
							nimln_(3782, "system.nim");
							i_5 = ((NI) 0);
							nimln_(3783, "system.nim");
							T136_ = (curList_3 ? curList_3->Sup.len : 0);
							L_3 = T136_;
							{
								nimln_(3784, "system.nim");
								while (1) {
									NI TM_gfe9a52b5gJr8GSrnr883iA_17;
									if (!(i_5 < L_3)) goto LA138;
									nimln_(3785, "system.nim");
									if (!curList_3 || (NU)(i_5) >= (NU)(curList_3->Sup.len)) raiseIndexError();
									cb_3.ClE_0 = curList_3->data[i_5].ClE_0;
									cb_3.ClP_0 = curList_3->data[i_5].ClP_0;
									nimln_(1176, "asyncdispatch.nim");
									{
										NI T141_;
										NI T144_;
										T141_ = (newList_3 ? newList_3->Sup.len : 0);
										if (!(((NI) 0) < T141_)) goto LA142_;
										nimln_(1179, "asyncdispatch.nim");
										newList_3 = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*) incrSeqV3(&(newList_3)->Sup, (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_));
										T144_ = newList_3->Sup.len++;
										asgnRef((void**) (&newList_3->data[T144_].ClE_0), cb_3.ClE_0);
										newList_3->data[T144_].ClP_0 = cb_3.ClP_0;
									}
									goto LA139_;
									LA142_: ;
									{
										nimln_(1181, "asyncdispatch.nim");
										{
											NIM_BOOL T148_;
											NI T151_;
											T148_ = (NIM_BOOL)0;
											T148_ = cb_3.ClE_0? cb_3.ClP_0(((int)chckRange(fd, ((int) (-2147483647 -1)), ((int) 2147483647))), cb_3.ClE_0):((TM_gfe9a52b5gJr8GSrnr883iA_16)(cb_3.ClP_0))(((int)chckRange(fd, ((int) (-2147483647 -1)), ((int) 2147483647))));
											if (!!(T148_)) goto LA149_;
											nimln_(1183, "asyncdispatch.nim");
											newList_3 = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*) incrSeqV3(&(newList_3)->Sup, (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_));
											T151_ = newList_3->Sup.len++;
											asgnRef((void**) (&newList_3->data[T151_].ClE_0), cb_3.ClE_0);
											newList_3->data[T151_].ClP_0 = cb_3.ClP_0;
										}
										LA149_: ;
									}
									LA139_: ;
									nimln_(3786, "system.nim");
									TM_gfe9a52b5gJr8GSrnr883iA_17 = addInt(i_5, ((NI) 1));
									i_5 = (NI)(TM_gfe9a52b5gJr8GSrnr883iA_17);
									nimln_(3787, "system.nim");
									{
										NI T154_;
										T154_ = (curList_3 ? curList_3->Sup.len : 0);
										if (!!((T154_ == L_3))) goto LA155_;
										failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_gfe9a52b5gJr8GSrnr883iA_13));
									}
									LA155_: ;
								} LA138: ;
							}
						}
						nimln_(512, "ioselectors_epoll.nim");
						fdi_6 = fd;
						nimln_(513, "ioselectors_epoll.nim");
						{
							nimln_(131, "ioselectors_epoll.nim");
							if (!((*(*p).selector).maxFD <= fdi_6)) goto LA159_;
							nimln_(132, "ioselectors_epoll.nim");
							raiseIOSelectorsError_o9b1ajHBhCZ9cfHDVe9aM1OwA(((NimStringDesc*) &TM_gfe9a52b5gJr8GSrnr883iA_10));
						}
						LA159_: ;
						nimln_(1253, "asyncdispatch.nim");
						{
							NIM_BOOL T163_;
							tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA* adata_6;
							NI T166_;
							NI T167_;
							nimln_(514, "ioselectors_epoll.nim");
							T163_ = (NIM_BOOL)0;
							T163_ = contains_pMqMlNzgkWdYwQvvCFhCMgasyncdispatch((*p).selector, fdi_6);
							if (!T163_) goto LA164_;
							nimln_(515, "ioselectors_epoll.nim");
							adata_6 = getData_FpLJNwB9bUrgExzpwKg6rew((*p).selector, fdi_6);
							nimln_(1187, "asyncdispatch.nim");
							unsureAsgnRef((void**) (&(*adata_6).readList), amp__D4JPmvcY0m7CVNPd6sHPwA(newList_3, (*adata_6).readList));
							nimln_(1188, "asyncdispatch.nim");
							T166_ = ((*adata_6).readList ? (*adata_6).readList->Sup.len : 0);
							rLength = T166_;
							nimln_(1189, "asyncdispatch.nim");
							T167_ = ((*adata_6).writeList ? (*adata_6).writeList->Sup.len : 0);
							wLength = T167_;
						}
						goto LA161_;
						LA164_: ;
						{
							nimln_(1192, "asyncdispatch.nim");
							rLength = ((NI) -1);
							nimln_(1193, "asyncdispatch.nim");
							wLength = ((NI) -1);
						}
						LA161_: ;
						nimln_(1254, "asyncdispatch.nim");
						custom = NIM_TRUE;
						nimln_(1255, "asyncdispatch.nim");
						{
							if (!(rLength == ((NI) 0))) goto LA171_;
							nimln_(1256, "asyncdispatch.nim");
							unregister_hmdECQbyOCuscYhV5uVu2A((*p).selector, fd);
						}
						LA171_: ;
						nimln_(1257, "asyncdispatch.nim");
						result = NIM_TRUE;
					}
					LA123_: ;
					nimln_(1260, "asyncdispatch.nim");
					{
						tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* curList_4;
						NI fdi_7;
						NI newLength_4;
						NI T186_;
						tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* newList_4;
						tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg cb_4;
						NI fdi_8;
						nimln_(396, "system.nim");
						nimln_(1260, "asyncdispatch.nim");
						if (!!(((customSet & events) == 0))) goto LA175_;
						nimln_(1261, "asyncdispatch.nim");
						custom = NIM_TRUE;
						curList_4 = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)0;
						nimln_(503, "ioselectors_epoll.nim");
						fdi_7 = fd;
						nimln_(504, "ioselectors_epoll.nim");
						{
							nimln_(131, "ioselectors_epoll.nim");
							if (!((*(*p).selector).maxFD <= fdi_7)) goto LA179_;
							nimln_(132, "ioselectors_epoll.nim");
							raiseIOSelectorsError_o9b1ajHBhCZ9cfHDVe9aM1OwA(((NimStringDesc*) &TM_gfe9a52b5gJr8GSrnr883iA_10));
						}
						LA179_: ;
						nimln_(1202, "asyncdispatch.nim");
						{
							NIM_BOOL T183_;
							tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA* adata_7;
							nimln_(505, "ioselectors_epoll.nim");
							T183_ = (NIM_BOOL)0;
							T183_ = contains_pMqMlNzgkWdYwQvvCFhCMgasyncdispatch((*p).selector, fdi_7);
							if (!T183_) goto LA184_;
							nimln_(506, "ioselectors_epoll.nim");
							adata_7 = getData_FpLJNwB9bUrgExzpwKg6rew((*p).selector, fdi_7);
							nimln_(1203, "asyncdispatch.nim");
							curList_4 = (*adata_7).readList;
							nimln_(1204, "asyncdispatch.nim");
							unsureAsgnRef((void**) (&(*adata_7).readList), (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)nimNewSeqOfCap((&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_), ((NI) 4)));
						}
						LA184_: ;
						nimln_(1206, "asyncdispatch.nim");
						T186_ = (curList_4 ? curList_4->Sup.len : 0);
						newLength_4 = T186_;
						nimln_(1207, "asyncdispatch.nim");
						newList_4 = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)nimNewSeqOfCap((&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_), ((NI)chckRange(newLength_4, ((NI) 0), ((NI) IL64(9223372036854775807)))));
						nimZeroMem((void*)(&cb_4), sizeof(tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg));
						nimln_(1209, "asyncdispatch.nim");
						if (!curList_4 || (NU)(((NI) 0)) >= (NU)(curList_4->Sup.len)) raiseIndexError();
						cb_4.ClE_0 = curList_4->data[((NI) 0)].ClE_0;
						cb_4.ClP_0 = curList_4->data[((NI) 0)].ClP_0;
						nimln_(1210, "asyncdispatch.nim");
						{
							NIM_BOOL T189_;
							NI T192_;
							T189_ = (NIM_BOOL)0;
							T189_ = cb_4.ClE_0? cb_4.ClP_0(((int)chckRange(fd, ((int) (-2147483647 -1)), ((int) 2147483647))), cb_4.ClE_0):((TM_gfe9a52b5gJr8GSrnr883iA_18)(cb_4.ClP_0))(((int)chckRange(fd, ((int) (-2147483647 -1)), ((int) 2147483647))));
							if (!!(T189_)) goto LA190_;
							nimln_(1211, "asyncdispatch.nim");
							newList_4 = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*) incrSeqV3(&(newList_4)->Sup, (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_));
							T192_ = newList_4->Sup.len++;
							asgnRef((void**) (&newList_4->data[T192_].ClE_0), cb_4.ClE_0);
							newList_4->data[T192_].ClP_0 = cb_4.ClP_0;
						}
						LA190_: ;
						nimln_(512, "ioselectors_epoll.nim");
						fdi_8 = fd;
						nimln_(513, "ioselectors_epoll.nim");
						{
							nimln_(131, "ioselectors_epoll.nim");
							if (!((*(*p).selector).maxFD <= fdi_8)) goto LA195_;
							nimln_(132, "ioselectors_epoll.nim");
							raiseIOSelectorsError_o9b1ajHBhCZ9cfHDVe9aM1OwA(((NimStringDesc*) &TM_gfe9a52b5gJr8GSrnr883iA_10));
						}
						LA195_: ;
						nimln_(1262, "asyncdispatch.nim");
						{
							NIM_BOOL T199_;
							tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA* adata_8;
							nimln_(514, "ioselectors_epoll.nim");
							T199_ = (NIM_BOOL)0;
							T199_ = contains_pMqMlNzgkWdYwQvvCFhCMgasyncdispatch((*p).selector, fdi_8);
							if (!T199_) goto LA200_;
							nimln_(515, "ioselectors_epoll.nim");
							adata_8 = getData_FpLJNwB9bUrgExzpwKg6rew((*p).selector, fdi_8);
							nimln_(1215, "asyncdispatch.nim");
							unsureAsgnRef((void**) (&(*adata_8).readList), amp__D4JPmvcY0m7CVNPd6sHPwA(newList_4, (*adata_8).readList));
							nimln_(1216, "asyncdispatch.nim");
							{
								NI T204_;
								T204_ = ((*adata_8).readList ? (*adata_8).readList->Sup.len : 0);
								if (!(T204_ == ((NI) 0))) goto LA205_;
								nimln_(1218, "asyncdispatch.nim");
								unregister_hmdECQbyOCuscYhV5uVu2A((*p).selector, fd);
							}
							LA205_: ;
						}
						goto LA197_;
						LA200_: ;
						{
						}
						LA197_: ;
						nimln_(1263, "asyncdispatch.nim");
						result = NIM_TRUE;
					}
					LA175_: ;
					nimln_(1267, "asyncdispatch.nim");
					{
						tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg newEvents;
						if (!!(custom)) goto LA210_;
						nimln_(1268, "asyncdispatch.nim");
						newEvents = 0;
						nimln_(1269, "asyncdispatch.nim");
						{
							NIM_BOOL T214_;
							T214_ = (NIM_BOOL)0;
							nimln_(396, "system.nim");
							T214_ = !((rLength == ((NI) -1)));
							if (!(T214_)) goto LA215_;
							nimln_(1269, "asyncdispatch.nim");
							nimln_(396, "system.nim");
							T214_ = !((wLength == ((NI) -1)));
							LA215_: ;
							if (!T214_) goto LA216_;
							nimln_(1270, "asyncdispatch.nim");
							{
								if (!(((NI) 0) < rLength)) goto LA220_;
								newEvents |= ((NU32)1)<<((((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 0))%(sizeof(NU32)*8));
							}
							LA220_: ;
							nimln_(1271, "asyncdispatch.nim");
							{
								if (!(((NI) 0) < wLength)) goto LA224_;
								newEvents |= ((NU32)1)<<((((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 1))%(sizeof(NU32)*8));
							}
							LA224_: ;
							nimln_(1272, "asyncdispatch.nim");
							updateHandle_rfvt9cp8cKSo9adyku8uXZCQ((*p).selector, ((int)chckRange(fd, ((int) (-2147483647 -1)), ((int) 2147483647))), newEvents);
						}
						LA216_: ;
					}
					LA210_: ;
					nimln_(3497, "system.nim");
					TM_gfe9a52b5gJr8GSrnr883iA_19 = addInt(i_2, ((NI) 1));
					i_2 = (NI)(TM_gfe9a52b5gJr8GSrnr883iA_19);
				} LA20: ;
			}
		}
	}
	LA14_: ;
	nimln_(1275, "asyncdispatch.nim");
	T226_ = (tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg*)0;
	T226_ = &p->Sup;
	processTimers_sL9cc2OYri9cNGOu9bRViHxdQasyncdispatch(T226_, (&result));
	nimln_(1277, "asyncdispatch.nim");
	T227_ = (tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg*)0;
	T227_ = &p->Sup;
	processPendingCallbacks_SmnbicdBxLog3d0rzfeG3w(T227_, (&result));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, poll_xqmRQXNU6QTg1bhi3gWITA)(NI timeout) {
	NIM_BOOL T1_;
	nimfr_("poll", "asyncdispatch.nim");
	nimln_(1511, "asyncdispatch.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = runOnce_mXlNJtuWiqnwbU9ceoRo80w(timeout);
	T1_;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, register_ZDbSqnhs9bTboienLLZUQ9ag)(int fd) {
	tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* p;
	tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA data;
	nimfr_("register", "asyncdispatch.nim");
	nimln_(1111, "asyncdispatch.nim");
	p = getGlobalDispatcher_9aj3b7Sd9ahqKV8UGXYgrIUg();
	nimZeroMem((void*)(&data), sizeof(tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA));
	nimln_(1112, "asyncdispatch.nim");
	chckNil((void*)(&data));
	nimZeroMem((void*)(&data), sizeof(tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA));
	nimln_(1084, "asyncdispatch.nim");
	data.readList = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)nimNewSeqOfCap((&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_), ((NI) 4));
	nimln_(1085, "asyncdispatch.nim");
	data.writeList = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)nimNewSeqOfCap((&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_), ((NI) 4));
	nimln_(1113, "asyncdispatch.nim");
	registerHandle_5DKkEtHHnI8Ye7BLEnzI3g((*p).selector, fd, 0, data);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, addRead_VrAQoa5RC42jZTEskfkaDw)(int fd, tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg cb) {
	tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* p;
	tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg newEvents;
	NI fdi;
	nimfr_("addRead", "asyncdispatch.nim");
	nimln_(1130, "asyncdispatch.nim");
	p = getGlobalDispatcher_9aj3b7Sd9ahqKV8UGXYgrIUg();
	nimln_(1131, "asyncdispatch.nim");
	newEvents = 1;
	nimln_(512, "ioselectors_epoll.nim");
	fdi = ((NI) (fd));
	nimln_(513, "ioselectors_epoll.nim");
	{
		nimln_(131, "ioselectors_epoll.nim");
		if (!((*(*p).selector).maxFD <= fdi)) goto LA3_;
		nimln_(132, "ioselectors_epoll.nim");
		raiseIOSelectorsError_o9b1ajHBhCZ9cfHDVe9aM1OwA(((NimStringDesc*) &TM_gfe9a52b5gJr8GSrnr883iA_10));
	}
	LA3_: ;
	nimln_(1132, "asyncdispatch.nim");
	{
		NIM_BOOL T7_;
		tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA* adata;
		NI T10_;
		nimln_(514, "ioselectors_epoll.nim");
		T7_ = (NIM_BOOL)0;
		T7_ = contains_pMqMlNzgkWdYwQvvCFhCMgasyncdispatch((*p).selector, fdi);
		if (!T7_) goto LA8_;
		nimln_(515, "ioselectors_epoll.nim");
		adata = getData_FpLJNwB9bUrgExzpwKg6rew((*p).selector, fdi);
		nimln_(1133, "asyncdispatch.nim");
		(*adata).readList = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*) incrSeqV3(&((*adata).readList)->Sup, (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_));
		T10_ = (*adata).readList->Sup.len++;
		asgnRef((void**) (&(*adata).readList->data[T10_].ClE_0), cb.ClE_0);
		(*adata).readList->data[T10_].ClP_0 = cb.ClP_0;
		nimln_(1134, "asyncdispatch.nim");
		newEvents |= ((NU32)1)<<((((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 0))%(sizeof(NU32)*8));
		nimln_(1135, "asyncdispatch.nim");
		{
			NI T13_;
			nimln_(396, "system.nim");
			nimln_(1135, "asyncdispatch.nim");
			T13_ = ((*adata).writeList ? (*adata).writeList->Sup.len : 0);
			if (!!((T13_ == ((NI) 0)))) goto LA14_;
			newEvents |= ((NU32)1)<<((((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 1))%(sizeof(NU32)*8));
		}
		LA14_: ;
	}
	goto LA5_;
	LA8_: ;
	{
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
		NimStringDesc* T17_;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		nimln_(2785, "system.nim");
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		nimln_(1137, "asyncdispatch.nim");
		T17_ = (NimStringDesc*)0;
		T17_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_gfe9a52b5gJr8GSrnr883iA_25));
		if (T17_) nimGCunrefNoCycle(T17_);
		nimln_(2780, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(1137, "asyncdispatch.nim");
		raiseException((Exception*)e, "ValueError");
	}
	LA5_: ;
	nimln_(1138, "asyncdispatch.nim");
	updateHandle_rfvt9cp8cKSo9adyku8uXZCQ((*p).selector, fd, newEvents);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, unregister_ZDbSqnhs9bTboienLLZUQ9ag_2)(int fd) {
	tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* T1_;
	nimfr_("unregister", "asyncdispatch.nim");
	nimln_(1121, "asyncdispatch.nim");
	T1_ = (tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ*)0;
	T1_ = getGlobalDispatcher_9aj3b7Sd9ahqKV8UGXYgrIUg();
	unregister_pBjqh3yG0lBifavFSbVYxg((*T1_).selector, fd);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_asyncdispatchInit000)(void) {
	nimfr_("asyncdispatch", "asyncdispatch.nim");
nimRegisterThreadLocalMarker(TM_gfe9a52b5gJr8GSrnr883iA_6);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_asyncdispatchDatInit000)(void) {
static TNimNode* TM_gfe9a52b5gJr8GSrnr883iA_2[2];
static TNimNode* TM_gfe9a52b5gJr8GSrnr883iA_3[2];
static TNimNode* TM_gfe9a52b5gJr8GSrnr883iA_4[2];
static TNimNode* TM_gfe9a52b5gJr8GSrnr883iA_5[2];
static TNimNode TM_gfe9a52b5gJr8GSrnr883iA_0[13];
NTI_E9c1MI1V1IJorH9cqPQ36Hqg_.size = sizeof(tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg);
NTI_E9c1MI1V1IJorH9cqPQ36Hqg_.kind = 17;
NTI_E9c1MI1V1IJorH9cqPQ36Hqg_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_gfe9a52b5gJr8GSrnr883iA_2[0] = &TM_gfe9a52b5gJr8GSrnr883iA_0[1];
NTI_V1aU9c9b1eMroa29cC237x0yQ_.size = sizeof(tyTuple_V1aU9c9b1eMroa29cC237x0yQ);
NTI_V1aU9c9b1eMroa29cC237x0yQ_.kind = 18;
NTI_V1aU9c9b1eMroa29cC237x0yQ_.base = 0;
TM_gfe9a52b5gJr8GSrnr883iA_3[0] = &TM_gfe9a52b5gJr8GSrnr883iA_0[3];
TM_gfe9a52b5gJr8GSrnr883iA_0[3].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[3].offset = offsetof(tyTuple_V1aU9c9b1eMroa29cC237x0yQ, Field0);
TM_gfe9a52b5gJr8GSrnr883iA_0[3].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_gfe9a52b5gJr8GSrnr883iA_0[3].name = "Field0";
TM_gfe9a52b5gJr8GSrnr883iA_3[1] = &TM_gfe9a52b5gJr8GSrnr883iA_0[4];
TM_gfe9a52b5gJr8GSrnr883iA_0[4].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[4].offset = offsetof(tyTuple_V1aU9c9b1eMroa29cC237x0yQ, Field1);
TM_gfe9a52b5gJr8GSrnr883iA_0[4].typ = (&NTI_MXXHrE9aQTCHOO4Tm9bXvZnw_);
TM_gfe9a52b5gJr8GSrnr883iA_0[4].name = "Field1";
TM_gfe9a52b5gJr8GSrnr883iA_0[2].len = 2; TM_gfe9a52b5gJr8GSrnr883iA_0[2].kind = 2; TM_gfe9a52b5gJr8GSrnr883iA_0[2].sons = &TM_gfe9a52b5gJr8GSrnr883iA_3[0];
NTI_V1aU9c9b1eMroa29cC237x0yQ_.node = &TM_gfe9a52b5gJr8GSrnr883iA_0[2];
TM_gfe9a52b5gJr8GSrnr883iA_0[1].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[1].offset = offsetof(tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg, timers);
TM_gfe9a52b5gJr8GSrnr883iA_0[1].typ = (&NTI_M89cHurEB0l2lhCwhToV4tw_);
TM_gfe9a52b5gJr8GSrnr883iA_0[1].name = "timers";
TM_gfe9a52b5gJr8GSrnr883iA_2[1] = &TM_gfe9a52b5gJr8GSrnr883iA_0[5];
TM_gfe9a52b5gJr8GSrnr883iA_0[5].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[5].offset = offsetof(tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg, callbacks);
TM_gfe9a52b5gJr8GSrnr883iA_0[5].typ = (&NTI_oL07LSXp3QMM0uEpFQiyQg_);
TM_gfe9a52b5gJr8GSrnr883iA_0[5].name = "callbacks";
TM_gfe9a52b5gJr8GSrnr883iA_0[0].len = 2; TM_gfe9a52b5gJr8GSrnr883iA_0[0].kind = 2; TM_gfe9a52b5gJr8GSrnr883iA_0[0].sons = &TM_gfe9a52b5gJr8GSrnr883iA_2[0];
NTI_E9c1MI1V1IJorH9cqPQ36Hqg_.node = &TM_gfe9a52b5gJr8GSrnr883iA_0[0];
NTI_pnVRciItPqJkU9bkmY2UaWQ_.size = sizeof(tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ);
NTI_pnVRciItPqJkU9bkmY2UaWQ_.kind = 17;
NTI_pnVRciItPqJkU9bkmY2UaWQ_.base = (&NTI_E9c1MI1V1IJorH9cqPQ36Hqg_);
NTI_hOYUN4IOpj9adMwn6W7S2VA_.size = sizeof(tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA);
NTI_hOYUN4IOpj9adMwn6W7S2VA_.kind = 18;
NTI_hOYUN4IOpj9adMwn6W7S2VA_.base = 0;
TM_gfe9a52b5gJr8GSrnr883iA_4[0] = &TM_gfe9a52b5gJr8GSrnr883iA_0[8];
NTI_9cnjNsE9aOh8FkRG9ccBKTpWg_.size = sizeof(tyTuple_2uzTbg8jwom7zHhmM2RgHg);
NTI_9cnjNsE9aOh8FkRG9ccBKTpWg_.kind = 18;
NTI_9cnjNsE9aOh8FkRG9ccBKTpWg_.base = 0;
TM_gfe9a52b5gJr8GSrnr883iA_5[0] = &TM_gfe9a52b5gJr8GSrnr883iA_0[10];
TM_gfe9a52b5gJr8GSrnr883iA_0[10].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[10].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field0);
TM_gfe9a52b5gJr8GSrnr883iA_0[10].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_gfe9a52b5gJr8GSrnr883iA_0[10].name = "Field0";
TM_gfe9a52b5gJr8GSrnr883iA_5[1] = &TM_gfe9a52b5gJr8GSrnr883iA_0[11];
TM_gfe9a52b5gJr8GSrnr883iA_0[11].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[11].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field1);
TM_gfe9a52b5gJr8GSrnr883iA_0[11].typ = (&NTI_58EFneeS9at7cA541QCoGAw_);
TM_gfe9a52b5gJr8GSrnr883iA_0[11].name = "Field1";
TM_gfe9a52b5gJr8GSrnr883iA_0[9].len = 2; TM_gfe9a52b5gJr8GSrnr883iA_0[9].kind = 2; TM_gfe9a52b5gJr8GSrnr883iA_0[9].sons = &TM_gfe9a52b5gJr8GSrnr883iA_5[0];
NTI_9cnjNsE9aOh8FkRG9ccBKTpWg_.node = &TM_gfe9a52b5gJr8GSrnr883iA_0[9];
NTI_lBAKjtL5n9bzoWNSpC1Vu3A_.size = sizeof(tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*);
NTI_lBAKjtL5n9bzoWNSpC1Vu3A_.kind = 24;
NTI_lBAKjtL5n9bzoWNSpC1Vu3A_.base = (&NTI_9cnjNsE9aOh8FkRG9ccBKTpWg_);
NTI_lBAKjtL5n9bzoWNSpC1Vu3A_.marker = Marker_tySequence_lBAKjtL5n9bzoWNSpC1Vu3A;
TM_gfe9a52b5gJr8GSrnr883iA_0[8].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[8].offset = offsetof(tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA, readList);
TM_gfe9a52b5gJr8GSrnr883iA_0[8].typ = (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_);
TM_gfe9a52b5gJr8GSrnr883iA_0[8].name = "readList";
TM_gfe9a52b5gJr8GSrnr883iA_4[1] = &TM_gfe9a52b5gJr8GSrnr883iA_0[12];
TM_gfe9a52b5gJr8GSrnr883iA_0[12].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[12].offset = offsetof(tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA, writeList);
TM_gfe9a52b5gJr8GSrnr883iA_0[12].typ = (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_);
TM_gfe9a52b5gJr8GSrnr883iA_0[12].name = "writeList";
TM_gfe9a52b5gJr8GSrnr883iA_0[7].len = 2; TM_gfe9a52b5gJr8GSrnr883iA_0[7].kind = 2; TM_gfe9a52b5gJr8GSrnr883iA_0[7].sons = &TM_gfe9a52b5gJr8GSrnr883iA_4[0];
NTI_hOYUN4IOpj9adMwn6W7S2VA_.node = &TM_gfe9a52b5gJr8GSrnr883iA_0[7];
TM_gfe9a52b5gJr8GSrnr883iA_0[6].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[6].offset = offsetof(tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ, selector);
TM_gfe9a52b5gJr8GSrnr883iA_0[6].typ = (&NTI_Y5hK0M9cL3lXwccEV9cgR9cQw_);
TM_gfe9a52b5gJr8GSrnr883iA_0[6].name = "selector";
NTI_pnVRciItPqJkU9bkmY2UaWQ_.node = &TM_gfe9a52b5gJr8GSrnr883iA_0[6];
NTI_LEZ1ZCj9cVMqh7s39cnMX6rw_.size = sizeof(tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ*);
NTI_LEZ1ZCj9cVMqh7s39cnMX6rw_.kind = 22;
NTI_LEZ1ZCj9cVMqh7s39cnMX6rw_.base = (&NTI_pnVRciItPqJkU9bkmY2UaWQ_);
NTI_LEZ1ZCj9cVMqh7s39cnMX6rw_.marker = Marker_tyRef_LEZ1ZCj9cVMqh7s39cnMX6rw;
}

