/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/benji/.nim/lib -o /home/benji/dev/nim/website/src/nimcache/stdlib_os.c.o /home/benji/dev/nim/website/src/nimcache/stdlib_os.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_IndexError_b0IIwghFQBADkB2c86kXQA tyObject_IndexError_b0IIwghFQBADkB2c86kXQA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct TSafePoint TSafePoint;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
NU raise_id;
Exception* up;
};
struct tyObject_IndexError_b0IIwghFQBADkB2c86kXQA {
  Exception Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef long tyArray_QS4edQct6fXoghbs69aZ9a8w[3];
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
typedef long tyArray_TcvIiMAJvcwzNLsZkfnFnQ[25];
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef NU8 tyEnum_FilePermission_uTVeDpjCH6aWw9c74YkAskA;
typedef NU16 tySet_tyEnum_FilePermission_uTVeDpjCH6aWw9c74YkAskA;
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getApplAux_Cd6LaCdd4j2y8pff6G0r9aw)(NimStringDesc* procPath);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getApplHeuristic_Mvl1mQZZxpEWtJIYJ85UWw)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, paramStr_eYicl3uwirn1ppNz7OCowg)(NI i);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getEnv_9b1nh9cAHhSLlHOPz8lCk5FA)(NimStringDesc* key, NimStringDesc* default_0);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosjoinPath)(NimStringDesc* head, NimStringDesc* tail);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, tryMoveFSObject_kAUHL0UShtIjkMl3w2BG3A)(NimStringDesc* source, NimStringDesc* dest);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError_tNPXXFl9cb3BG0pJKzUn9bew)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError_bEwAamo1N7TKcaU9akpiyIg)(NI32 errorCode, NimStringDesc* additionalInfo);
N_LIB_PRIVATE N_NIMCALL(void, noscopyFile)(NimStringDesc* source, NimStringDesc* dest);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, open_sEp0GH2306oGo9bqBpj5oTQ)(FILE** f, NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
N_LIB_PRIVATE N_NIMCALL(void, close_BWnr8V7RERYno9bIdPmw8Hw_3)(FILE* f);
N_LIB_PRIVATE N_NOCONV(void*, alloc_sVm4rDImKK2ZDdylByayiA)(NI size);
N_LIB_PRIVATE N_NIMCALL(NI, readBuffer_1qjbrvfnPD4PaIieHVDvhw_2)(FILE* f, void* buffer, NI len);
N_LIB_PRIVATE N_NIMCALL(NI, writeBuffer_1qjbrvfnPD4PaIieHVDvhw)(FILE* f, void* buffer, NI len);
N_LIB_PRIVATE N_NOCONV(void, dealloc_RCjNtRnHdRYntrcE7YtwWw)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, flushFile_BWnr8V7RERYno9bIdPmw8Hw_2)(FILE* f);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_LIB_PRIVATE N_NIMCALL(void, nosremoveFile)(NimStringDesc* file);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nostryRemoveFile)(NimStringDesc* file);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(TFrame*, getFrame)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(NIM_BOOL, eqeq__9ccNWqrTIE9bcAqE2Q0ro7zgospaths)(NCSTRING x, NCSTRING y);
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, nosnormalizePath)(NimStringDesc** path);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringDesc* path);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQlogging)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
static N_INLINE(NimStringDesc**, X5BX5D__xFULIkGrri8iJzi40N9ahqwos)(NimStringDesc** s, NI sLen_0, NI i);
static N_INLINE(NimStringDesc*, pop_9cDsfK2acP02vJ9bhxIE9caEAos)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ** s);
N_NIMCALL(TGenericSeq*, setLengthSeqV2)(TGenericSeq* s, TNimType* typ, NI newLen);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a, NI aLen_0, NimStringDesc* sep);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(NI64, getFileSize_XePgC9ccBXCgb9bEHXZpnMqA)(FILE* f);
extern int cmdCount;
extern NCSTRING* cmdLine;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_z58cIdR0vOibqJ0QwYvB3Q_;
extern TNimType NTI_b0IIwghFQBADkB2c86kXQA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
extern Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
TNimType NTI_uTVeDpjCH6aWw9c74YkAskA_;
TNimType NTI_4dCEsVAKwboFfqH37oiA9bQ_;
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_3, "/proc/self/exe", 14);
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_4, "invalid index", 13);
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_5, "PATH", 4);
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_6, "", 0);
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_12, "\0120 <= bufsize lib/pure/os.nim(282) ", 35);
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_15, ".", 1);
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_16, "..", 2);
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_21, "/", 1);

static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == NIM_NIL);
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getApplAux_Cd6LaCdd4j2y8pff6G0r9aw)(NimStringDesc* procPath) {
	NimStringDesc* result;
	NI len;
	nimfr_("getApplAux", "os.nim");
	result = (NimStringDesc*)0;
	nimln_(1428, "os.nim");
	result = mnewString(((NI) 256));
	nimln_(1429, "os.nim");
	len = readlink(nimToCStringConv(procPath), nimToCStringConv(result), ((NI) 256));
	nimln_(1430, "os.nim");
	{
		NI TM_yu6cxgKBBXbNsTkT9cyMd4g_2;
		if (!(((NI) 256) < len)) goto LA3_;
		nimln_(1431, "os.nim");
		TM_yu6cxgKBBXbNsTkT9cyMd4g_2 = addInt(len, ((NI) 1));
		result = mnewString(((NI)chckRange((NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_2), ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln_(1432, "os.nim");
		len = readlink(nimToCStringConv(procPath), nimToCStringConv(result), len);
	}
	LA3_: ;
	nimln_(1433, "os.nim");
	result = setLengthStr(result, ((NI)chckRange(len, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		nimln_(185, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln_(252, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		nimln_(185, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln_(218, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(396, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(264, "gc.nim");
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(396, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		nimln_(265, "gc.nim");
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, paramStr_eYicl3uwirn1ppNz7OCowg)(NI i) {
	NimStringDesc* result;
	tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
	NimStringDesc* T7_;
	nimfr_("paramStr", "os.nim");
{	result = (NimStringDesc*)0;
	nimln_(1365, "os.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (i < ((NI) (cmdCount)));
		if (!(T3_)) goto LA4_;
		T3_ = (((NI) 0) <= i);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = cstrToNimstr(cmdLine[(i)- 0]);
		goto BeforeRet_;
	}
	LA5_: ;
	e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
	nimln_(2785, "system.nim");
	e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
	(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
	nimln_(1366, "os.nim");
	T7_ = (NimStringDesc*)0;
	T7_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_4));
	if (T7_) nimGCunrefNoCycle(T7_);
	nimln_(2780, "system.nim");
	asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
	nimln_(1366, "os.nim");
	raiseException((Exception*)e, "IndexError");
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}

static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem(p, ((int) 0), size);
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename) {
	NIM_BOOL result;
	struct stat res;
	NIM_BOOL T1_;
	int T2_;
	nimfr_("existsFile", "os.nim");
{	result = (NIM_BOOL)0;
	nimZeroMem((void*)(&res), sizeof(struct stat));
	nimln_(88, "os.nim");
	T1_ = (NIM_BOOL)0;
	T2_ = (int)0;
	T2_ = stat(nimToCStringConv(filename), (&res));
	T1_ = (((NI32) 0) <= T2_);
	if (!(T1_)) goto LA3_;
	T1_ = S_ISREG(res.st_mode);
	LA3_: ;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getApplHeuristic_Mvl1mQZZxpEWtJIYJ85UWw)(void) {
	NimStringDesc* result;
	nimfr_("getApplHeuristic", "os.nim");
{	result = (NimStringDesc*)0;
	nimln_(1438, "os.nim");
	result = paramStr_eYicl3uwirn1ppNz7OCowg(((NI) 0));
	nimln_(1441, "os.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) < (result ? result->Sup.len : 0));
		if (!(T3_)) goto LA4_;
		nimln_(396, "system.nim");
		if (!result || (NU)(((NI) 0)) >= (NU)(result->Sup.len)) raiseIndexError();
		T3_ = !(((NU8)(result->data[((NI) 0)]) == (NU8)(47)));
		LA4_: ;
		if (!T3_) goto LA5_;
		{
			NimStringDesc* p;
			NimStringDesc* colontmp_;
			NI last;
			NI splits;
			p = (NimStringDesc*)0;
			colontmp_ = (NimStringDesc*)0;
			nimln_(1443, "os.nim");
			colontmp_ = getEnv_9b1nh9cAHhSLlHOPz8lCk5FA(((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_5), ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_6));
			nimln_(389, "strutils.nim");
			last = ((NI) 0);
			nimln_(390, "strutils.nim");
			splits = ((NI) -1);
			{
				nimln_(458, "strutils.nim");
				while (1) {
					NI first;
					NI TM_yu6cxgKBBXbNsTkT9cyMd4g_8;
					NimStringDesc* x;
					NI TM_yu6cxgKBBXbNsTkT9cyMd4g_9;
					NI TM_yu6cxgKBBXbNsTkT9cyMd4g_10;
					nimln_(392, "strutils.nim");
					if (!(last <= (colontmp_ ? colontmp_->Sup.len : 0))) goto LA9;
					nimln_(393, "strutils.nim");
					first = last;
					{
						nimln_(394, "strutils.nim");
						while (1) {
							NIM_BOOL T12_;
							NI TM_yu6cxgKBBXbNsTkT9cyMd4g_7;
							T12_ = (NIM_BOOL)0;
							T12_ = (last < (colontmp_ ? colontmp_->Sup.len : 0));
							if (!(T12_)) goto LA13_;
							if (!colontmp_ || (NU)(last) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
							T12_ = !((((NU8)(colontmp_->data[last])) == ((NU8)(58))));
							LA13_: ;
							if (!T12_) goto LA11;
							nimln_(395, "strutils.nim");
							TM_yu6cxgKBBXbNsTkT9cyMd4g_7 = addInt(last, ((NI) 1));
							last = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_7);
						} LA11: ;
					}
					nimln_(396, "strutils.nim");
					{
						if (!(splits == ((NI) 0))) goto LA16_;
						last = (colontmp_ ? colontmp_->Sup.len : 0);
					}
					LA16_: ;
					nimln_(397, "strutils.nim");
					TM_yu6cxgKBBXbNsTkT9cyMd4g_8 = subInt(last, ((NI) 1));
					p = copyStrLast(colontmp_, first, (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_8));
					nimln_(1444, "os.nim");
					x = nosjoinPath(p, result);
					nimln_(1445, "os.nim");
					{
						NIM_BOOL T20_;
						T20_ = (NIM_BOOL)0;
						T20_ = nosexistsFile(x);
						if (!T20_) goto LA21_;
						result = copyString(x);
						goto BeforeRet_;
					}
					LA21_: ;
					nimln_(398, "strutils.nim");
					{
						if (!(splits == ((NI) 0))) goto LA25_;
						goto LA8;
					}
					LA25_: ;
					nimln_(399, "strutils.nim");
					TM_yu6cxgKBBXbNsTkT9cyMd4g_9 = subInt(splits, ((NI) 1));
					splits = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_9);
					nimln_(400, "strutils.nim");
					TM_yu6cxgKBBXbNsTkT9cyMd4g_10 = addInt(last, ((NI) 1));
					last = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_10);
				} LA9: ;
			} LA8: ;
		}
	}
	LA5_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosgetAppFilename)(void) {
	NimStringDesc* result;
	nimfr_("getAppFilename", "os.nim");
	result = (NimStringDesc*)0;
	nimln_(1508, "os.nim");
	result = getApplAux_Cd6LaCdd4j2y8pff6G0r9aw(((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_3));
	nimln_(1516, "os.nim");
	{
		if (!((result ? result->Sup.len : 0) == ((NI) 0))) goto LA3_;
		nimln_(1517, "os.nim");
		result = getApplHeuristic_Mvl1mQZZxpEWtJIYJ85UWw();
	}
	LA3_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, tryMoveFSObject_kAUHL0UShtIjkMl3w2BG3A)(NimStringDesc* source, NimStringDesc* dest) {
	NIM_BOOL result;
	nimfr_("tryMoveFSObject", "os.nim");
{	result = (NIM_BOOL)0;
	nimln_(677, "os.nim");
	{
		int T3_;
		NI32 err;
		nimln_(396, "system.nim");
		nimln_(677, "os.nim");
		T3_ = (int)0;
		T3_ = rename(nimToCStringConv(source), nimToCStringConv(dest));
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		nimln_(678, "os.nim");
		err = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		nimln_(679, "os.nim");
		{
			if (!(err == ((NI32) 18))) goto LA8_;
			nimln_(680, "os.nim");
			result = NIM_FALSE;
			goto BeforeRet_;
		}
		goto LA6_;
		LA8_: ;
		{
			NCSTRING T11_;
			NimStringDesc* T12_;
			nimln_(682, "os.nim");
			T11_ = (NCSTRING)0;
			T11_ = strerror(errno);
			T12_ = (NimStringDesc*)0;
			T12_ = cstrToNimstr(T11_);
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(err, T12_);
		}
		LA6_: ;
	}
	LA4_: ;
	nimln_(683, "os.nim");
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, noscopyFile)(NimStringDesc* source, NimStringDesc* dest) {
	FILE* d;
	FILE* s;
	void* buf;
	nimfr_("copyFile", "os.nim");
	d = (FILE*)0;
	s = (FILE*)0;
	nimln_(596, "os.nim");
	{
		NIM_BOOL T3_;
		NI32 T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = open_sEp0GH2306oGo9bqBpj5oTQ(&s, source, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
		if (!!(T3_)) goto LA4_;
		T6_ = (NI32)0;
		T6_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_6));
	}
	LA4_: ;
	nimln_(597, "os.nim");
	{
		NIM_BOOL T9_;
		NI32 T12_;
		T9_ = (NIM_BOOL)0;
		T9_ = open_sEp0GH2306oGo9bqBpj5oTQ(&d, dest, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 1), ((NI) -1));
		if (!!(T9_)) goto LA10_;
		nimln_(598, "os.nim");
		close_BWnr8V7RERYno9bIdPmw8Hw_3(s);
		nimln_(599, "os.nim");
		T12_ = (NI32)0;
		T12_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T12_, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_6));
	}
	LA10_: ;
	nimln_(600, "os.nim");
	buf = alloc_sVm4rDImKK2ZDdylByayiA(((NI) 8000));
	{
		nimln_(601, "os.nim");
		while (1) {
			NI bytesread;
			nimln_(602, "os.nim");
			bytesread = readBuffer_1qjbrvfnPD4PaIieHVDvhw_2(s, buf, ((NI) 8000));
			nimln_(603, "os.nim");
			{
				NI byteswritten;
				if (!(((NI) 0) < bytesread)) goto LA17_;
				nimln_(604, "os.nim");
				byteswritten = writeBuffer_1qjbrvfnPD4PaIieHVDvhw(d, buf, ((NI)chckRange(bytesread, ((NI) 0), ((NI) IL64(9223372036854775807)))));
				nimln_(605, "os.nim");
				{
					NI32 T23_;
					nimln_(396, "system.nim");
					if (!!((bytesread == byteswritten))) goto LA21_;
					nimln_(606, "os.nim");
					dealloc_RCjNtRnHdRYntrcE7YtwWw(buf);
					nimln_(607, "os.nim");
					close_BWnr8V7RERYno9bIdPmw8Hw_3(s);
					nimln_(608, "os.nim");
					close_BWnr8V7RERYno9bIdPmw8Hw_3(d);
					nimln_(609, "os.nim");
					T23_ = (NI32)0;
					T23_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
					raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T23_, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_6));
				}
				LA21_: ;
			}
			LA17_: ;
			nimln_(610, "os.nim");
			{
				nimln_(396, "system.nim");
				if (!!((bytesread == ((NI) 8000)))) goto LA26_;
				nimln_(610, "os.nim");
				goto LA13;
			}
			LA26_: ;
		}
	} LA13: ;
	nimln_(611, "os.nim");
	dealloc_RCjNtRnHdRYntrcE7YtwWw(buf);
	nimln_(612, "os.nim");
	close_BWnr8V7RERYno9bIdPmw8Hw_3(s);
	nimln_(613, "os.nim");
	flushFile_BWnr8V7RERYno9bIdPmw8Hw_2(d);
	nimln_(614, "os.nim");
	close_BWnr8V7RERYno9bIdPmw8Hw_3(d);
	popFrame();
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nostryRemoveFile)(NimStringDesc* file) {
	NIM_BOOL result;
	nimfr_("tryRemoveFile", "os.nim");
	result = (NIM_BOOL)0;
	nimln_(636, "os.nim");
	result = NIM_TRUE;
	nimln_(652, "os.nim");
	{
		NIM_BOOL T3_;
		int T4_;
		T3_ = (NIM_BOOL)0;
		nimln_(396, "system.nim");
		nimln_(652, "os.nim");
		T4_ = (int)0;
		T4_ = remove(nimToCStringConv(file));
		T3_ = !((T4_ == ((NI32) 0)));
		if (!(T3_)) goto LA5_;
		nimln_(396, "system.nim");
		T3_ = !((errno == ((int) 2)));
		LA5_: ;
		if (!T3_) goto LA6_;
		nimln_(653, "os.nim");
		result = NIM_FALSE;
	}
	LA6_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, nosremoveFile)(NimStringDesc* file) {
	nimfr_("removeFile", "os.nim");
	nimln_(659, "os.nim");
	{
		NIM_BOOL T3_;
		NI32 T6_;
		NCSTRING T7_;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = nostryRemoveFile(file);
		if (!!(T3_)) goto LA4_;
		nimln_(663, "os.nim");
		T6_ = (NI32)0;
		T6_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		T7_ = (NCSTRING)0;
		T7_ = strerror(errno);
		T8_ = (NimStringDesc*)0;
		T8_ = cstrToNimstr(T7_);
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, T8_);
	}
	LA4_: ;
	popFrame();
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(TFrame*, getFrame)(void) {
	TFrame* result;
	result = (TFrame*)0;
	result = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	return result;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException_9bVPeDJlYTi9bQApZpfH8wjg), (*currException_9bVPeDJlYTi9bQApZpfH8wjg).up);
}

N_LIB_PRIVATE N_NIMCALL(void, nosmoveFile)(NimStringDesc* source, NimStringDesc* dest) {
	TFrame* _nimCurFrame;
	nimfr_("moveFile", "os.nim");
	_nimCurFrame = getFrame();
	nimln_(689, "os.nim");
	{
		NIM_BOOL T3_;
		TSafePoint TM_yu6cxgKBBXbNsTkT9cyMd4g_11;
		T3_ = (NIM_BOOL)0;
		T3_ = tryMoveFSObject_kAUHL0UShtIjkMl3w2BG3A(source, dest);
		if (!!(T3_)) goto LA4_;
		nimln_(692, "os.nim");
		noscopyFile(source, dest);
		nimln_(693, "os.nim");
		pushSafePoint(&TM_yu6cxgKBBXbNsTkT9cyMd4g_11);
		TM_yu6cxgKBBXbNsTkT9cyMd4g_11.status = setjmp(TM_yu6cxgKBBXbNsTkT9cyMd4g_11.context);
		if (TM_yu6cxgKBBXbNsTkT9cyMd4g_11.status == 0) {
			nimln_(694, "os.nim");
			nosremoveFile(source);
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame(_nimCurFrame);
			{
				NIM_BOOL T9_;
				TM_yu6cxgKBBXbNsTkT9cyMd4g_11.status = 0;
				nimln_(696, "os.nim");
				T9_ = (NIM_BOOL)0;
				T9_ = nostryRemoveFile(dest);
				T9_;
				nimln_(697, "os.nim");
				reraiseException();
				popCurrentException();
			}
		}
		if (TM_yu6cxgKBBXbNsTkT9cyMd4g_11.status != 0) reraiseException();
	}
	LA4_: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, eqeq__9ccNWqrTIE9bcAqE2Q0ro7zgospaths)(NCSTRING x, NCSTRING y) {
	NIM_BOOL result;
	nimfr_("==", "system.nim");
	result = (NIM_BOOL)0;
	nimln_(4053, "system.nim");
	{
		if (!(((void*) (x)) == ((void*) (y)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA3_: ;
	{
		NIM_BOOL T6_;
		nimln_(4054, "system.nim");
		T6_ = (NIM_BOOL)0;
		T6_ = (x == 0);
		if (T6_) goto LA7_;
		T6_ = (y == 0);
		LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
	LA8_: ;
	{
		int T11_;
		nimln_(4055, "system.nim");
		T11_ = (int)0;
		T11_ = strcmp(x, y);
		result = (T11_ == ((NI32) 0));
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosgetCurrentDir)(void) {
	NimStringDesc* result;
	NI bufsize;
	nimfr_("getCurrentDir", "os.nim");
	result = (NimStringDesc*)0;
	nimln_(272, "os.nim");
	bufsize = ((NI) 1024);
	nimln_(273, "os.nim");
	result = mnewString(((NI)chckRange(bufsize, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		nimln_(274, "os.nim");
		while (1) {
			nimln_(275, "os.nim");
			{
				NCSTRING T5_;
				NIM_BOOL T6_;
				int T9_;
				nimln_(396, "system.nim");
				nimln_(275, "os.nim");
				T5_ = (NCSTRING)0;
				T5_ = getcwd(nimToCStringConv(result), bufsize);
				T6_ = (NIM_BOOL)0;
				T6_ = eqeq__9ccNWqrTIE9bcAqE2Q0ro7zgospaths(T5_, NIM_NIL);
				if (!!(T6_)) goto LA7_;
				nimln_(276, "os.nim");
				T9_ = (int)0;
				T9_ = strlen(nimToCStringConv(result));
				result = setLengthStr(result, ((NI)chckRange(T9_, ((NI) 0), ((NI) IL64(9223372036854775807)))));
				nimln_(277, "os.nim");
				goto LA1;
			}
			goto LA3_;
			LA7_: ;
			{
				NI32 err;
				nimln_(279, "os.nim");
				err = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
				nimln_(280, "os.nim");
				{
					if (!(err == ((int) 34))) goto LA13_;
					nimln_(281, "os.nim");
					bufsize = (NI)((NU64)(bufsize) << (NU64)(((NI) 1)));
					nimln_(282, "os.nim");
					{
						if (!!((((NI) 0) <= bufsize))) goto LA17_;
						raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_12));
					}
					LA17_: ;
					nimln_(283, "os.nim");
					result = mnewString(((NI)chckRange(bufsize, ((NI) 0), ((NI) IL64(9223372036854775807)))));
				}
				goto LA11_;
				LA13_: ;
				{
					NI32 T20_;
					nimln_(285, "os.nim");
					T20_ = (NI32)0;
					T20_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
					raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T20_, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_6));
				}
				LA11_: ;
			}
			LA3_: ;
		}
	} LA1: ;
	popFrame();
	return result;
}

static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQlogging)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NI alen;
	NI blen;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		if (!(a == NIM_NIL)) goto LA7_;
		alen = ((NI) 0);
	}
	goto LA5_;
	LA7_: ;
	{
		alen = (*a).Sup.len;
	}
	LA5_: ;
	{
		if (!(b == NIM_NIL)) goto LA12_;
		blen = ((NI) 0);
	}
	goto LA10_;
	LA12_: ;
	{
		blen = (*b).Sup.len;
	}
	LA10_: ;
	{
		if (!(alen == blen)) goto LA17_;
		{
			if (!(alen == ((NI) 0))) goto LA21_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA21_: ;
		result = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQlogging(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) (alen)));
		goto BeforeRet_;
	}
	LA17_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NimStringDesc**, X5BX5D__xFULIkGrri8iJzi40N9ahqwos)(NimStringDesc** s, NI sLen_0, NI i) {
	NimStringDesc** result;
	NI TM_yu6cxgKBBXbNsTkT9cyMd4g_17;
	nimfr_("[]", "system.nim");
	result = (NimStringDesc**)0;
	nimln_(3604, "system.nim");
	TM_yu6cxgKBBXbNsTkT9cyMd4g_17 = subInt(sLen_0, i);
	if ((NU)((NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_17)) >= (NU)(sLen_0)) raiseIndexError();
	result = (&s[(NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_17)]);
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, pop_9cDsfK2acP02vJ9bhxIE9caEAos)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ** s) {
	NimStringDesc* result;
	NI L;
	NI T1_;
	NI TM_yu6cxgKBBXbNsTkT9cyMd4g_18;
	nimfr_("pop", "system.nim");
	result = (NimStringDesc*)0;
	nimln_(2410, "system.nim");
	T1_ = ((*s) ? (*s)->Sup.len : 0);
	TM_yu6cxgKBBXbNsTkT9cyMd4g_18 = subInt(T1_, ((NI) 1));
	L = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_18);
	nimln_(2411, "system.nim");
	if (!(*s) || (NU)(L) >= (NU)((*s)->Sup.len)) raiseIndexError();
	result = copyString((*s)->data[L]);
	nimln_(2412, "system.nim");
	(*s) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) setLengthSeqV2(&((*s))->Sup, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == NIM_NIL))) goto LA3_;
		copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, nosnormalizePath)(NimStringDesc** path) {
	NIM_BOOL isAbs;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* stack;
	nimfr_("normalizePath", "os.nim");
	nimln_(371, "os.nim");
	isAbs = nosisAbsolute((*path));
	nimln_(372, "os.nim");
	stack = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	{
		NimStringDesc* p;
		NimStringDesc* colontmp_;
		NI last;
		NI splits;
		p = (NimStringDesc*)0;
		colontmp_ = (NimStringDesc*)0;
		nimln_(373, "os.nim");
		colontmp_ = (*path);
		nimln_(389, "strutils.nim");
		last = ((NI) 0);
		nimln_(390, "strutils.nim");
		splits = ((NI) -1);
		{
			nimln_(458, "strutils.nim");
			while (1) {
				NI first;
				NI TM_yu6cxgKBBXbNsTkT9cyMd4g_14;
				NI TM_yu6cxgKBBXbNsTkT9cyMd4g_19;
				NI TM_yu6cxgKBBXbNsTkT9cyMd4g_20;
				nimln_(392, "strutils.nim");
				if (!(last <= (colontmp_ ? colontmp_->Sup.len : 0))) goto LA3;
				nimln_(393, "strutils.nim");
				first = last;
				{
					nimln_(394, "strutils.nim");
					while (1) {
						NIM_BOOL T6_;
						NI TM_yu6cxgKBBXbNsTkT9cyMd4g_13;
						T6_ = (NIM_BOOL)0;
						T6_ = (last < (colontmp_ ? colontmp_->Sup.len : 0));
						if (!(T6_)) goto LA7_;
						if (!colontmp_ || (NU)(last) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
						T6_ = !((((NU8)(colontmp_->data[last])) == ((NU8)(47))));
						LA7_: ;
						if (!T6_) goto LA5;
						nimln_(395, "strutils.nim");
						TM_yu6cxgKBBXbNsTkT9cyMd4g_13 = addInt(last, ((NI) 1));
						last = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_13);
					} LA5: ;
				}
				nimln_(396, "strutils.nim");
				{
					if (!(splits == ((NI) 0))) goto LA10_;
					last = (colontmp_ ? colontmp_->Sup.len : 0);
				}
				LA10_: ;
				nimln_(397, "strutils.nim");
				TM_yu6cxgKBBXbNsTkT9cyMd4g_14 = subInt(last, ((NI) 1));
				p = copyStrLast(colontmp_, first, (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_14));
				{
					nimln_(374, "os.nim");
					if (eqStrings(p, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_6))) goto LA13_;
					if (eqStrings(p, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_15))) goto LA13_;
					if (eqStrings(p, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_16))) goto LA14_;
					goto LA15_;
					LA13_: ;
					{
						nimln_(376, "os.nim");
						goto LA12;
					}
					goto LA16_;
					LA14_: ;
					{
						nimln_(378, "os.nim");
						{
							NI T21_;
							T21_ = (stack ? stack->Sup.len : 0);
							if (!(T21_ == ((NI) 0))) goto LA22_;
							nimln_(379, "os.nim");
							{
								if (!isAbs) goto LA26_;
							}
							goto LA24_;
							LA26_: ;
							{
								NI T29_;
								NimStringDesc* T30_;
								nimln_(382, "os.nim");
								stack = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV3(&(stack)->Sup, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
								T29_ = stack->Sup.len++;
								T30_ = (NimStringDesc*)0;
								T30_ = stack->data[T29_]; stack->data[T29_] = copyStringRC1(p);
								if (T30_) nimGCunrefNoCycle(T30_);
							}
							LA24_: ;
						}
						goto LA19_;
						LA22_: ;
						{
							NimStringDesc** T32_;
							NI T35_;
							NimStringDesc* T36_;
							nimln_(383, "os.nim");
							T32_ = (NimStringDesc**)0;
							T32_ = X5BX5D__xFULIkGrri8iJzi40N9ahqwos(stack->data, (stack ? stack->Sup.len : 0), ((NI) 1));
							if (!eqStrings((*T32_), ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_16))) goto LA33_;
							nimln_(384, "os.nim");
							stack = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV3(&(stack)->Sup, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
							T35_ = stack->Sup.len++;
							T36_ = (NimStringDesc*)0;
							T36_ = stack->data[T35_]; stack->data[T35_] = copyStringRC1(p);
							if (T36_) nimGCunrefNoCycle(T36_);
						}
						goto LA19_;
						LA33_: ;
						{
							NimStringDesc* T38_;
							nimln_(386, "os.nim");
							T38_ = (NimStringDesc*)0;
							T38_ = pop_9cDsfK2acP02vJ9bhxIE9caEAos((&stack));
							T38_;
						}
						LA19_: ;
					}
					goto LA16_;
					LA15_: ;
					{
						NI T40_;
						NimStringDesc* T41_;
						nimln_(388, "os.nim");
						stack = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV3(&(stack)->Sup, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
						T40_ = stack->Sup.len++;
						T41_ = (NimStringDesc*)0;
						T41_ = stack->data[T40_]; stack->data[T40_] = copyStringRC1(p);
						if (T41_) nimGCunrefNoCycle(T41_);
					}
					LA16_: ;
				} LA12: ;
				nimln_(398, "strutils.nim");
				{
					if (!(splits == ((NI) 0))) goto LA44_;
					goto LA2;
				}
				LA44_: ;
				nimln_(399, "strutils.nim");
				TM_yu6cxgKBBXbNsTkT9cyMd4g_19 = subInt(splits, ((NI) 1));
				splits = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_19);
				nimln_(400, "strutils.nim");
				TM_yu6cxgKBBXbNsTkT9cyMd4g_20 = addInt(last, ((NI) 1));
				last = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_20);
			} LA3: ;
		} LA2: ;
	}
	nimln_(390, "os.nim");
	{
		NimStringDesc* T50_;
		NimStringDesc* T51_;
		if (!isAbs) goto LA48_;
		nimln_(391, "os.nim");
		T50_ = (NimStringDesc*)0;
		T51_ = (NimStringDesc*)0;
		T51_ = nsuJoinSep(stack->data, (stack ? stack->Sup.len : 0), ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_21));
		T50_ = rawNewString((T51_ ? T51_->Sup.len : 0) + 1);
appendChar(T50_, 47);
appendString(T50_, T51_);
		unsureAsgnRef((void**) (&(*path)), T50_);
	}
	goto LA46_;
	LA48_: ;
	{
		NI T53_;
		nimln_(392, "os.nim");
		T53_ = (stack ? stack->Sup.len : 0);
		if (!(((NI) 0) < T53_)) goto LA54_;
		nimln_(393, "os.nim");
		unsureAsgnRef((void**) (&(*path)), nsuJoinSep(stack->data, (stack ? stack->Sup.len : 0), ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_21)));
	}
	goto LA46_;
	LA54_: ;
	{
		nimln_(395, "os.nim");
		unsureAsgnRef((void**) (&(*path)), copyString(((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_15)));
	}
	LA46_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosnormalizedPath)(NimStringDesc* path) {
	NimStringDesc* result;
	nimfr_("normalizedPath", "os.nim");
	result = (NimStringDesc*)0;
	nimln_(399, "os.nim");
	result = copyString(path);
	nimln_(400, "os.nim");
	nosnormalizePath((&result));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsDir)(NimStringDesc* dir) {
	NIM_BOOL result;
	struct stat res;
	NIM_BOOL T1_;
	int T2_;
	nimfr_("existsDir", "os.nim");
{	result = (NIM_BOOL)0;
	nimZeroMem((void*)(&res), sizeof(struct stat));
	nimln_(102, "os.nim");
	T1_ = (NIM_BOOL)0;
	T2_ = (int)0;
	T2_ = stat(nimToCStringConv(dir), (&res));
	T1_ = (((NI32) 0) <= T2_);
	if (!(T1_)) goto LA3_;
	T1_ = S_ISDIR(res.st_mode);
	LA3_: ;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySet_tyEnum_FilePermission_uTVeDpjCH6aWw9c74YkAskA, nosgetFilePermissions)(NimStringDesc* filename) {
	tySet_tyEnum_FilePermission_uTVeDpjCH6aWw9c74YkAskA result;
	struct stat a;
	nimfr_("getFilePermissions", "os.nim");
	nimZeroMem((void*)(&result), sizeof(tySet_tyEnum_FilePermission_uTVeDpjCH6aWw9c74YkAskA));
	nimZeroMem((void*)(&a), sizeof(struct stat));
	nimln_(512, "os.nim");
	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = stat(nimToCStringConv(filename), (&a));
		if (!(T3_ < ((NI32) 0))) goto LA4_;
		T6_ = (NI32)0;
		T6_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_6));
	}
	LA4_: ;
	nimln_(513, "os.nim");
	result = 0;
	nimln_(514, "os.nim");
	{
		nimln_(396, "system.nim");
		nimln_(514, "os.nim");
		if (!!(((NI32)(a.st_mode & ((int) 256)) == ((NI32) 0)))) goto LA9_;
		result |= ((NU16)1)<<((((tyEnum_FilePermission_uTVeDpjCH6aWw9c74YkAskA) 2))%(sizeof(NU16)*8));
	}
	LA9_: ;
	nimln_(515, "os.nim");
	{
		nimln_(396, "system.nim");
		nimln_(515, "os.nim");
		if (!!(((NI32)(a.st_mode & ((int) 128)) == ((NI32) 0)))) goto LA13_;
		result |= ((NU16)1)<<((((tyEnum_FilePermission_uTVeDpjCH6aWw9c74YkAskA) 1))%(sizeof(NU16)*8));
	}
	LA13_: ;
	nimln_(516, "os.nim");
	{
		nimln_(396, "system.nim");
		nimln_(516, "os.nim");
		if (!!(((NI32)(a.st_mode & ((int) 64)) == ((NI32) 0)))) goto LA17_;
		result |= ((NU16)1)<<((((tyEnum_FilePermission_uTVeDpjCH6aWw9c74YkAskA) 0))%(sizeof(NU16)*8));
	}
	LA17_: ;
	nimln_(518, "os.nim");
	{
		nimln_(396, "system.nim");
		nimln_(518, "os.nim");
		if (!!(((NI32)(a.st_mode & ((int) 32)) == ((NI32) 0)))) goto LA21_;
		result |= ((NU16)1)<<((((tyEnum_FilePermission_uTVeDpjCH6aWw9c74YkAskA) 5))%(sizeof(NU16)*8));
	}
	LA21_: ;
	nimln_(519, "os.nim");
	{
		nimln_(396, "system.nim");
		nimln_(519, "os.nim");
		if (!!(((NI32)(a.st_mode & ((int) 16)) == ((NI32) 0)))) goto LA25_;
		result |= ((NU16)1)<<((((tyEnum_FilePermission_uTVeDpjCH6aWw9c74YkAskA) 4))%(sizeof(NU16)*8));
	}
	LA25_: ;
	nimln_(520, "os.nim");
	{
		nimln_(396, "system.nim");
		nimln_(520, "os.nim");
		if (!!(((NI32)(a.st_mode & ((int) 8)) == ((NI32) 0)))) goto LA29_;
		result |= ((NU16)1)<<((((tyEnum_FilePermission_uTVeDpjCH6aWw9c74YkAskA) 3))%(sizeof(NU16)*8));
	}
	LA29_: ;
	nimln_(522, "os.nim");
	{
		nimln_(396, "system.nim");
		nimln_(522, "os.nim");
		if (!!(((NI32)(a.st_mode & ((int) 4)) == ((NI32) 0)))) goto LA33_;
		result |= ((NU16)1)<<((((tyEnum_FilePermission_uTVeDpjCH6aWw9c74YkAskA) 8))%(sizeof(NU16)*8));
	}
	LA33_: ;
	nimln_(523, "os.nim");
	{
		nimln_(396, "system.nim");
		nimln_(523, "os.nim");
		if (!!(((NI32)(a.st_mode & ((int) 2)) == ((NI32) 0)))) goto LA37_;
		result |= ((NU16)1)<<((((tyEnum_FilePermission_uTVeDpjCH6aWw9c74YkAskA) 7))%(sizeof(NU16)*8));
	}
	LA37_: ;
	nimln_(524, "os.nim");
	{
		nimln_(396, "system.nim");
		nimln_(524, "os.nim");
		if (!!(((NI32)(a.st_mode & ((int) 1)) == ((NI32) 0)))) goto LA41_;
		result |= ((NU16)1)<<((((tyEnum_FilePermission_uTVeDpjCH6aWw9c74YkAskA) 6))%(sizeof(NU16)*8));
	}
	LA41_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI64, nosgetFileSize)(NimStringDesc* file) {
	NI64 result;
	FILE* f;
	nimfr_("getFileSize", "os.nim");
	result = (NI64)0;
	f = (FILE*)0;
	nimln_(1545, "os.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = open_sEp0GH2306oGo9bqBpj5oTQ(&f, file, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
		if (!T3_) goto LA4_;
		nimln_(1546, "os.nim");
		result = getFileSize_XePgC9ccBXCgb9bEHXZpnMqA(f);
		nimln_(1547, "os.nim");
		close_BWnr8V7RERYno9bIdPmw8Hw_3(f);
	}
	goto LA1_;
	LA4_: ;
	{
		NI32 T7_;
		nimln_(1548, "os.nim");
		T7_ = (NI32)0;
		T7_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T7_, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_6));
	}
	LA1_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_osInit000)(void) {
	nimfr_("os", "os.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_osDatInit000)(void) {
static TNimNode* TM_yu6cxgKBBXbNsTkT9cyMd4g_22[9];
NI TM_yu6cxgKBBXbNsTkT9cyMd4g_24;
static char* NIM_CONST TM_yu6cxgKBBXbNsTkT9cyMd4g_23[9] = {
"fpUserExec", 
"fpUserWrite", 
"fpUserRead", 
"fpGroupExec", 
"fpGroupWrite", 
"fpGroupRead", 
"fpOthersExec", 
"fpOthersWrite", 
"fpOthersRead"};
static TNimNode TM_yu6cxgKBBXbNsTkT9cyMd4g_0[11];
NTI_uTVeDpjCH6aWw9c74YkAskA_.size = sizeof(tyEnum_FilePermission_uTVeDpjCH6aWw9c74YkAskA);
NTI_uTVeDpjCH6aWw9c74YkAskA_.kind = 14;
NTI_uTVeDpjCH6aWw9c74YkAskA_.base = 0;
NTI_uTVeDpjCH6aWw9c74YkAskA_.flags = 3;
for (TM_yu6cxgKBBXbNsTkT9cyMd4g_24 = 0; TM_yu6cxgKBBXbNsTkT9cyMd4g_24 < 9; TM_yu6cxgKBBXbNsTkT9cyMd4g_24++) {
TM_yu6cxgKBBXbNsTkT9cyMd4g_0[TM_yu6cxgKBBXbNsTkT9cyMd4g_24+0].kind = 1;
TM_yu6cxgKBBXbNsTkT9cyMd4g_0[TM_yu6cxgKBBXbNsTkT9cyMd4g_24+0].offset = TM_yu6cxgKBBXbNsTkT9cyMd4g_24;
TM_yu6cxgKBBXbNsTkT9cyMd4g_0[TM_yu6cxgKBBXbNsTkT9cyMd4g_24+0].name = TM_yu6cxgKBBXbNsTkT9cyMd4g_23[TM_yu6cxgKBBXbNsTkT9cyMd4g_24];
TM_yu6cxgKBBXbNsTkT9cyMd4g_22[TM_yu6cxgKBBXbNsTkT9cyMd4g_24] = &TM_yu6cxgKBBXbNsTkT9cyMd4g_0[TM_yu6cxgKBBXbNsTkT9cyMd4g_24+0];
}
TM_yu6cxgKBBXbNsTkT9cyMd4g_0[9].len = 9; TM_yu6cxgKBBXbNsTkT9cyMd4g_0[9].kind = 2; TM_yu6cxgKBBXbNsTkT9cyMd4g_0[9].sons = &TM_yu6cxgKBBXbNsTkT9cyMd4g_22[0];
NTI_uTVeDpjCH6aWw9c74YkAskA_.node = &TM_yu6cxgKBBXbNsTkT9cyMd4g_0[9];
NTI_4dCEsVAKwboFfqH37oiA9bQ_.size = sizeof(tySet_tyEnum_FilePermission_uTVeDpjCH6aWw9c74YkAskA);
NTI_4dCEsVAKwboFfqH37oiA9bQ_.kind = 19;
NTI_4dCEsVAKwboFfqH37oiA9bQ_.base = (&NTI_uTVeDpjCH6aWw9c74YkAskA_);
NTI_4dCEsVAKwboFfqH37oiA9bQ_.flags = 3;
TM_yu6cxgKBBXbNsTkT9cyMd4g_0[10].len = 0; TM_yu6cxgKBBXbNsTkT9cyMd4g_0[10].kind = 0;
NTI_4dCEsVAKwboFfqH37oiA9bQ_.node = &TM_yu6cxgKBBXbNsTkT9cyMd4g_0[10];
}

