/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/benji/.nim/lib -o /home/benji/dev/nim/website/src/nimcache/stdlib_uri.c.o /home/benji/dev/nim/website/src/nimcache/stdlib_uri.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, handleHexChar_g0Mc9bquhMvGhJuSAXY34qguri)(NIM_CHAR c, NI* x);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_VzbRQH9cb1xm1tSKH4PwBSw_7, "false ", 6);

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, handleHexChar_g0Mc9bquhMvGhJuSAXY34qguri)(NIM_CHAR c, NI* x) {
	nimfr_("handleHexChar", "uri.nim");
	nimln_(79, "uri.nim");
	switch (((NU8)(c))) {
	case 48 ... 57:
	{
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_2;
		nimln_(80, "uri.nim");
		TM_VzbRQH9cb1xm1tSKH4PwBSw_2 = subInt(((NU8)(c)), ((NI) 48));
		(*x) = (NI)((NI)((NU64)((*x)) << (NU64)(((NI) 4))) | (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_2));
	}
	break;
	case 97 ... 102:
	{
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_3;
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_4;
		nimln_(81, "uri.nim");
		TM_VzbRQH9cb1xm1tSKH4PwBSw_3 = subInt(((NU8)(c)), ((NI) 97));
		TM_VzbRQH9cb1xm1tSKH4PwBSw_4 = addInt((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_3), ((NI) 10));
		(*x) = (NI)((NI)((NU64)((*x)) << (NU64)(((NI) 4))) | (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_4));
	}
	break;
	case 65 ... 70:
	{
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_5;
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_6;
		nimln_(82, "uri.nim");
		TM_VzbRQH9cb1xm1tSKH4PwBSw_5 = subInt(((NU8)(c)), ((NI) 65));
		TM_VzbRQH9cb1xm1tSKH4PwBSw_6 = addInt((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_5), ((NI) 10));
		(*x) = (NI)((NI)((NU64)((*x)) << (NU64)(((NI) 4))) | (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_6));
	}
	break;
	default:
	{
		nimln_(83, "uri.nim");
		{
			if (!NIM_TRUE) goto LA7_;
			failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_7));
		}
		LA7_: ;
	}
	break;
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, decodeUrl_hsKocnpPoled0HQ1nt3uyA)(NimStringDesc* s, NIM_BOOL decodePlus) {
	NimStringDesc* result;
	NI i;
	NI j;
	nimfr_("decodeUrl", "uri.nim");
	result = (NimStringDesc*)0;
	nimln_(85, "uri.nim");
	result = mnewString(((NI)chckRange((s ? s->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(86, "uri.nim");
	i = ((NI) 0);
	nimln_(87, "uri.nim");
	j = ((NI) 0);
	{
		nimln_(88, "uri.nim");
		while (1) {
			NI TM_VzbRQH9cb1xm1tSKH4PwBSw_11;
			NI TM_VzbRQH9cb1xm1tSKH4PwBSw_12;
			if (!(i < (s ? s->Sup.len : 0))) goto LA2;
			nimln_(89, "uri.nim");
			if (!s || (NU)(i) >= (NU)(s->Sup.len)) raiseIndexError();
			switch (((NU8)(s->data[i]))) {
			case 37:
			{
				NI x;
				NI TM_VzbRQH9cb1xm1tSKH4PwBSw_8;
				NI TM_VzbRQH9cb1xm1tSKH4PwBSw_9;
				NI TM_VzbRQH9cb1xm1tSKH4PwBSw_10;
				nimln_(91, "uri.nim");
				x = ((NI) 0);
				nimln_(92, "uri.nim");
				TM_VzbRQH9cb1xm1tSKH4PwBSw_8 = addInt(i, ((NI) 1));
				if (!s || (NU)((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_8)) >= (NU)(s->Sup.len)) raiseIndexError();
				handleHexChar_g0Mc9bquhMvGhJuSAXY34qguri(s->data[(NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_8)], (&x));
				nimln_(93, "uri.nim");
				TM_VzbRQH9cb1xm1tSKH4PwBSw_9 = addInt(i, ((NI) 2));
				if (!s || (NU)((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_9)) >= (NU)(s->Sup.len)) raiseIndexError();
				handleHexChar_g0Mc9bquhMvGhJuSAXY34qguri(s->data[(NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_9)], (&x));
				nimln_(94, "uri.nim");
				TM_VzbRQH9cb1xm1tSKH4PwBSw_10 = addInt(i, ((NI) 2));
				i = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_10);
				if (!result || (NU)(j) >= (NU)(result->Sup.len)) raiseIndexError();
				nimln_(95, "uri.nim");
				result->data[j] = ((NIM_CHAR) (((NI)chckRange(x, ((NI) 0), ((NI) 255)))));
			}
			break;
			case 43:
			{
				nimln_(97, "uri.nim");
				{
					if (!decodePlus) goto LA7_;
					if (!result || (NU)(j) >= (NU)(result->Sup.len)) raiseIndexError();
					nimln_(98, "uri.nim");
					result->data[j] = 32;
				}
				goto LA5_;
				LA7_: ;
				{
					if (!result || (NU)(j) >= (NU)(result->Sup.len)) raiseIndexError();
					nimln_(100, "uri.nim");
					if (!s || (NU)(i) >= (NU)(s->Sup.len)) raiseIndexError();
					result->data[j] = s->data[i];
				}
				LA5_: ;
			}
			break;
			default:
			{
				if (!result || (NU)(j) >= (NU)(result->Sup.len)) raiseIndexError();
				nimln_(101, "uri.nim");
				if (!s || (NU)(i) >= (NU)(s->Sup.len)) raiseIndexError();
				result->data[j] = s->data[i];
			}
			break;
			}
			nimln_(102, "uri.nim");
			TM_VzbRQH9cb1xm1tSKH4PwBSw_11 = addInt(i, ((NI) 1));
			i = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_11);
			nimln_(103, "uri.nim");
			TM_VzbRQH9cb1xm1tSKH4PwBSw_12 = addInt(j, ((NI) 1));
			j = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_12);
		} LA2: ;
	}
	nimln_(104, "uri.nim");
	result = setLengthStr(result, ((NI)chckRange(j, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_uriInit000)(void) {
	nimfr_("uri", "uri.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_uriDatInit000)(void) {
}

